(function(){
  const VERSION=window.BUILD_VERSION||'unknown',SAVE_KEY='one-building-game-v1',CYCLE_MS=20000,GARDEN_MS=60000,PRIMARY_MS=300000,DAY_MS=600000,PREGNANCY_DAYS=9,PREGNANCY_MS=DAY_MS*PREGNANCY_DAYS,DAYS_PER_YEAR=12,CLINIC_MS=60000,MEAL_TIMES=[6,12,20],MILK_TIMES=[6,20];
  const SKILLS=['食品','物流','技术','艺术','服务','科研'];
  const CATEGORIES=['全部','居住类','食品类','满意类','经济类','技能类','服务类'];
  const SURNAMES=['林','周','陈','陆','许','顾','沈','江','苏','叶','唐','程','赵','钱','孙','李','吴','郑','王','冯','韩','秦','白','宋','季','乔','段','袁','徐','陶','姜','谢','邵','余','杜','罗','高','梁','夏','魏'];
  const GIVEN_NAMES={男:['川','野','远','舟','安','一','辰','泽','然','航','昊','宇','轩','朗','越','嘉','墨','言','景','修','鸣','屿','青','柏','星河','晨宇','子安','景川','云舟','明远','知行','亦辰','嘉树','望舒','清和'],女:['夏','禾','月','晴','宁','岚','秋','棠','悦','念','瑶','露','音','雪','竹','萤','微','舒','简','遥','芷','晚','溪','星','安然','星月','清欢','知夏','若宁','云舒','南枝','雨棠','书瑶','静姝','初晴']};
  const ROOMS={
    dorm:{name:'宿舍',category:'居住类',cost:600,description:'最多可供 6 名居民入住。新建宿舍为空。'},
    garden:{name:'菜园',category:'食品类',cost:400,description:'最多 2 名员工，每人每 20 秒收获 1 份蔬菜。',production:{vegetables:1,label:'🥬 蔬菜'}},
    farm:{name:'牧场',category:'食品类',cost:500,description:'最多 2 名员工，每人每 20 秒产出 1 份肉和 1 份牛奶。',production:{meat:1,milk:1,label:'🥩 肉＋🥛 奶'}},
    park:{name:'花园',category:'满意类',cost:300,capacity:4,description:'最多容纳 4 人，每 60 秒为其中每人增加 5 满意度。',effect:{satisfaction:5,label:'♥ 满意度 +5'}},
    clinic:{name:'诊所',category:'满意类',cost:600,description:'医生需要服务技能至少 3 且科研技能达到 5；病人治疗 60 秒后康复。'},
    maternity:{name:'助产室',category:'服务类',cost:800,description:'安排 1 名合格医生，并在临产前让父母一同入住；足月 2 天内未生产会流产。'},
    market:{name:'超市',category:'经济类',cost:500,description:'最多 2 名员工，每人每 20 秒赚取 €10。',production:{money:10,label:'💶 收入 €10'}},
    clothing:{name:'服装店',category:'经济类',cost:650,description:'最多 2 名员工，服务技能至少 3；每名员工每 60 秒制作 1 件衣服，多余库存自动按 €50 出售。'},
    school:{name:'社区学校',category:'技能类',cost:450,description:'接收 13 岁及以上居民进修；设置 1 名教师和一门课程，最多 3 名学生同时学习。'},
    primary:{name:'小学',category:'技能类',cost:550,description:'只接收 12 岁及以下儿童；最多 4 名学生，每 5 分钟将所选技能提升至 1。'},
    barber:{name:'理发店',category:'服务类',cost:350,description:'设置 1 名理发师，每 20 秒服务 1 名顾客；完成后满意度增加 5。'}
  };
  const $=id=>document.getElementById(id),random=array=>array[Math.floor(Math.random()*array.length)],euro=n=>'€'+Math.round(n).toLocaleString('en-US');

  function randomName(gender,used=[],surname=random(SURNAMES)){let name;for(let attempts=0;attempts<100;attempts++){name=surname+random(GIVEN_NAMES[gender]);if(!used.includes(name))return name}const fallback=['安','宁','青','禾','川','月','云','星'];return surname+random(fallback)+random(fallback)}
  function createResident(index,used,forcedTalent,forcedSurname,forcedEducation='社区学校'){const gender=Math.random()<.5?'男':'女',surname=forcedSurname||random(SURNAMES),name=randomName(gender,used,surname),talent=forcedTalent||random(SKILLS),matchingSprites=gender==='男'?[0,2,4,6]:[1,3,5,7];return{id:`p-${Date.now()}-${index}`,name,surname,gender,age:20,education:forcedEducation,talent,satisfaction:50,satiety:100,satietyZeroSince:null,deathPending:false,foodPreference:'auto',milkPreference:'auto',lastMealSlot:0,lastMilkSlot:0,spouseId:null,pregnancy:null,sick:false,sickCause:null,sickUntil:null,clinicFloorId:null,skills:Object.fromEntries(SKILLS.map(skill=>[skill,skill===talent?5:1])),sprite:matchingSprites[index%4]}}
  function floorId(index){return`floor-${index+1}-${Date.now()}`}
  function mealSlotAt(now,createdAt){const elapsed=Math.max(0,now-createdAt),days=Math.floor(elapsed/DAY_MS),dayElapsed=elapsed%DAY_MS,mealsToday=MEAL_TIMES.filter(hour=>dayElapsed>=DAY_MS*hour/24).length;return days*MEAL_TIMES.length+mealsToday}
  function milkSlotAt(now,createdAt){const elapsed=Math.max(0,now-createdAt),days=Math.floor(elapsed/DAY_MS),dayElapsed=elapsed%DAY_MS,milkToday=MILK_TIMES.filter(hour=>dayElapsed>=DAY_MS*hour/24).length;return days*MILK_TIMES.length+milkToday}
  function migrateFoodStock(data){if(data.foodStockMigrated)return;const garden=data.floors.find(floor=>floor.type==='garden'),farm=data.floors.find(floor=>floor.type==='farm');if(garden)garden.stock.vegetables+=data.inventory.vegetables||0;if(farm){farm.stock.meat+=data.inventory.meat||0;farm.stock.milk+=data.inventory.milk||0}data.foodStockMigrated=true;syncInventory(data)}
  function syncInventory(target=state){target.inventory={vegetables:0,meat:0,milk:0};target.floors.forEach(floor=>{target.inventory.vegetables+=floor.stock?.vegetables||0;target.inventory.meat+=floor.stock?.meat||0;target.inventory.milk+=floor.stock?.milk||0})}
  function freshGame(){const people=[],startingTalents=[...SKILLS],startingSurnames=[...SURNAMES].sort(()=>Math.random()-.5),startingEducation=['社区学校','社区学校','社区学校','社区学校','硕士','博士'].sort(()=>Math.random()-.5),createdAt=Date.now();for(let i=0;i<startingTalents.length;i++)people.push(createResident(i,people.map(p=>p.name),startingTalents[i],startingSurnames[i],startingEducation[i]));return{money:1000,people,inventory:{vegetables:0,meat:0,milk:0},ageYear:0,lastSicknessDay:0,floors:[{id:floorId(0),type:'dorm',residents:people.map(p=>p.id),workerIds:[],cycleStartedAt:null,teacherId:null,studentIds:[],taughtSkill:null,schoolStartedAt:null,barberId:null,barberQueue:[],currentClientId:null,barberStartedAt:null,stock:{vegetables:0,meat:0,milk:0}}],createdAt}}
  function normalizeState(data){data.inventory=Object.assign({vegetables:0,meat:0,milk:0},data.inventory||{});const now=Date.now(),currentSlot=mealSlotAt(now,data.createdAt||now),currentMilkSlot=milkSlotAt(now,data.createdAt||now),scheduleChanged=data.mealScheduleVersion!==1,milkScheduleChanged=data.milkScheduleVersion!==1;data.people=(data.people||[]).map(person=>{const normalized=Object.assign({surname:person.name?.slice(0,1)||random(SURNAMES),satisfaction:0,satiety:100,foodPreference:'auto',milkPreference:'auto',lastMealSlot:currentSlot,lastMilkSlot:currentMilkSlot,spouseId:null,pregnancy:null},person);if(scheduleChanged)normalized.lastMealSlot=currentSlot;if(milkScheduleChanged)normalized.lastMilkSlot=currentMilkSlot;return normalized});data.mealScheduleVersion=1;data.milkScheduleVersion=1;data.floors=(data.floors||[]).map((floor,index)=>{const normalized=Object.assign({id:`floor-${index+1}-${data.createdAt||Date.now()}`,residents:[],workerIds:[],cycleStartedAt:null,teacherId:null,studentIds:[],taughtSkill:null,schoolStartedAt:null,barberId:null,barberQueue:[],currentClientId:null,barberStartedAt:null,stock:{vegetables:0,meat:0,milk:0}},floor);normalized.stock=Object.assign({vegetables:0,meat:0,milk:0},floor.stock||{});if(!Array.isArray(floor.workerIds))normalized.workerIds=floor.workerId?[floor.workerId]:[];if(normalized.type==='school'){if(!normalized.teacherId&&normalized.workerIds.length)normalized.teacherId=normalized.workerIds[0];if(!normalized.studentIds.length&&normalized.workerIds.length>1)normalized.studentIds=normalized.workerIds.slice(1,4);normalized.workerIds=[]}if(normalized.type==='barber'&&!normalized.barberId&&normalized.workerIds.length){normalized.barberId=normalized.workerIds[0];normalized.workerIds=[]}delete normalized.workerId;return normalized});migrateFoodStock(data);return data}
  function loadGame(){try{return normalizeState(JSON.parse(localStorage.getItem(SAVE_KEY))||freshGame())}catch{return freshGame()}}
  let state=loadGame(),activeRoomIndex=null,activeCategory='全部',toastQueue=[],toastShowing=false,elevator={floor:0,queue:[],trip:null};
  if(state.pregnancyDurationVersion!==2){const now=Date.now();state.people.filter(person=>person.pregnancy).forEach(person=>person.pregnancy.dueAt=now+PREGNANCY_MS);state.pregnancyDurationVersion=2}
  if(!Number.isInteger(state.ageYear))state.ageYear=Math.floor(Math.max(0,Date.now()-state.createdAt)/(DAY_MS*DAYS_PER_YEAR));if(!Number.isInteger(state.lastSicknessDay))state.lastSicknessDay=Math.floor(Math.max(0,Date.now()-state.createdAt)/DAY_MS);state.people.forEach(person=>{if(person.sick===undefined)person.sick=false;if(person.sickCause===undefined)person.sickCause=null;if(person.sickUntil===undefined)person.sickUntil=null;if(person.clinicFloorId===undefined)person.clinicFloorId=null;if(person.satietyZeroSince===undefined)person.satietyZeroSince=null;if(person.deathPending===undefined)person.deathPending=false});
  state.floors.forEach(floor=>{if(!Array.isArray(floor.maternityFamilyIds))floor.maternityFamilyIds=[]});
  state.floors.forEach(floor=>{if(!Number.isFinite(floor.clothingStock))floor.clothingStock=0;if(!Number.isFinite(floor.clothingReserve))floor.clothingReserve=2});state.people.forEach(person=>{if(person.hasClothes===undefined)person.hasClothes=false;if(!Number.isFinite(person.clothingBonus))person.clothingBonus=person.hasClothes?10:0});
  function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
  function residentById(id){return state.people.find(person=>person.id===id)}
  function workerFloor(id){return state.floors.find(floor=>(floor.workerIds||[]).includes(id)||floor.teacherId===id||(floor.studentIds||[]).includes(id)||floor.barberId===id||(floor.maternityFamilyIds||[]).includes(id))}
  function assignedPersonIds(){const ids=new Set();state.floors.forEach(floor=>{floor.workerIds.forEach(id=>ids.add(id));if(floor.teacherId)ids.add(floor.teacherId);floor.studentIds.forEach(id=>ids.add(id));if(floor.barberId)ids.add(floor.barberId);(floor.maternityFamilyIds||[]).forEach(id=>ids.add(id))});return ids}
  function removePersonAssignments(id,exceptFloor=null){state.floors.forEach(floor=>{if(floor===exceptFloor)return;const before=floor.workerIds.length;floor.workerIds=floor.workerIds.filter(workerId=>workerId!==id);if(before!==floor.workerIds.length)floor.cycleStartedAt=floor.workerIds.length?Date.now():null;if(floor.teacherId===id){floor.teacherId=null;floor.schoolStartedAt=null}if(floor.studentIds.includes(id)){floor.studentIds=floor.studentIds.filter(studentId=>studentId!==id);floor.schoolStartedAt=floor.teacherId&&floor.studentIds.length&&floor.taughtSkill?Date.now():null}if(floor.barberId===id){floor.barberId=null;if(floor.currentClientId)floor.barberQueue.unshift(floor.currentClientId);floor.currentClientId=null;floor.barberStartedAt=null}floor.barberQueue=(floor.barberQueue||[]).filter(personId=>personId!==id);if(floor.currentClientId===id){floor.currentClientId=null;floor.barberStartedAt=null}if((floor.maternityFamilyIds||[]).includes(id))floor.maternityFamilyIds=floor.maternityFamilyIds.filter(personId=>personId!==id)})}
  function roomCapacity(floor){return ROOMS[floor.type].capacity||2}
  function workerRequirement(floor){const category=ROOMS[floor.type]?.category;if(category==='食品类')return{skill:'食品',min:3};if(floor.type==='market')return{skill:'物流',min:3};if(floor.type==='clothing')return{skill:'服务',min:3};if(category==='服务类')return{skill:'服务',min:3};return null}
  function meetsWorkerSkill(person,floor){if(!person)return false;if(floor.type==='clinic'||floor.type==='maternity')return(person.skills['服务']||0)>=3&&(person.skills['科研']||0)===5;const requirement=workerRequirement(floor);return !requirement||(person.skills[requirement.skill]||0)>=requirement.min}
  function requirementText(floor){if(floor.type==='clinic'||floor.type==='maternity')return'服务技能至少 3 且科研技能达到 5';const requirement=workerRequirement(floor);return requirement?`${requirement.skill}技能至少 ${requirement.min}`:'无技能门槛'}
  function eligibleFirst(people,isEligible){return[...people].sort((a,b)=>Number(!isEligible(a))-Number(!isEligible(b))||a.name.localeCompare(b.name,'zh-CN'))}
  function sanitizeWorkerSkills(){state.floors.forEach(floor=>{const before=floor.workerIds.length;floor.workerIds=floor.workerIds.filter(id=>{const person=residentById(id);return person&&meetsWorkerSkill(person,floor)});if(before!==floor.workerIds.length)floor.cycleStartedAt=floor.workerIds.length?Date.now():null;if(floor.barberId&&!meetsWorkerSkill(residentById(floor.barberId),floor)){floor.barberId=null;if(floor.currentClientId)floor.barberQueue.unshift(floor.currentClientId);floor.currentClientId=null;floor.barberStartedAt=null}})}
  sanitizeWorkerSkills();
  function bedCapacity(){return state.floors.filter(floor=>floor.type==='dorm').length*6}
  function activePregnancies(){return state.people.filter(person=>person.pregnancy).length}
  function spritePosition(variant){const col=variant%4,row=Math.floor(variant/4);return`${col*(100/3)}% ${row*100}%`}
  function toast(message){toastQueue.push(message);if(toastShowing)return;const showNext=()=>{const next=toastQueue.shift();if(!next){toastShowing=false;return}toastShowing=true;$('toast').textContent=next;$('toast').classList.add('show');setTimeout(()=>{$('toast').classList.remove('show');setTimeout(showNext,220)},1600)};showNext()}
  let celebrationTimer=null;function celebrate(ids,title){const people=[...new Set(ids)].map(residentById).filter(Boolean);if(!people.length)return;clearTimeout(celebrationTimer);$('celebrationTitle').textContent=title;$('celebrationPeople').innerHTML=people.map((person,index)=>`<i class="celebration-person" style="background-position:${spritePosition(person.sprite)};--delay:${index%8*0.04}s" title="${person.name}"></i>`).join('');$('celebrationConfetti').innerHTML=Array.from({length:32},(_,index)=>`<i style="--x:${(index*37)%100}%;--delay:${(index%9)*.06}s;--spin:${index%2?1:-1}">${index%3===0?'★':index%3===1?'■':'●'}</i>`).join('');$('celebration').classList.remove('show');void $('celebration').offsetWidth;$('celebration').classList.add('show');document.querySelectorAll('[data-person]').forEach(button=>button.classList.toggle('cheering',ids.includes(button.dataset.person)));celebrationTimer=setTimeout(()=>{$('celebration').classList.remove('show');document.querySelectorAll('.cheering').forEach(node=>node.classList.remove('cheering'))},2400)}
  function showView(name){document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.id===`view-${name}`));document.querySelectorAll('nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===name));window.scrollTo(0,0)}

  function buildRoom(type){const room=ROOMS[type];if(!room)return;if(state.money<room.cost)return toast('资金不足');state.money-=room.cost;state.floors.push({id:floorId(state.floors.length),type,residents:[],workerIds:[],cycleStartedAt:null,teacherId:null,studentIds:[],taughtSkill:null,schoolStartedAt:null,barberId:null,barberQueue:[],currentClientId:null,barberStartedAt:null,maternityFamilyIds:[],clothingStock:0,clothingReserve:2,stock:{vegetables:0,meat:0,milk:0}});save();render();showView('building');toast(`F${state.floors.length} ${room.name}建造完成`)}
  function roomStockLabel(floor){if(floor.type==='garden')return`库存 🥬${floor.stock.vegetables}`;if(floor.type==='farm')return`库存 🥩${floor.stock.meat} 🥛${floor.stock.milk}`;return''}
  function productionMarkup(floor,index){const room=ROOMS[floor.type],production=room.production,effect=room.effect,workerCount=floor.workerIds.length;if(floor.type==='clothing'){const active=workerCount>0,progress=active&&floor.cycleStartedAt?Math.min(100,(Date.now()-floor.cycleStartedAt)/GARDEN_MS*100):0;return`<div class="production-ui" data-production-floor="${index}"><div class="production-label"><span>👕 库存 ${floor.clothingStock} · 预留 ${floor.clothingReserve}</span><span class="production-time">${active?Math.max(0,Math.ceil((GARDEN_MS-(Date.now()-floor.cycleStartedAt))/1000))+'s':'待命'}</span></div><div class="production-track"><i class="production-fill" style="width:${progress}%"></i></div></div>`}if(floor.type==='school'){const active=floor.teacherId&&floor.taughtSkill&&floor.studentIds.length,progress=active&&floor.schoolStartedAt?Math.min(100,(Date.now()-floor.schoolStartedAt)/GARDEN_MS*100):0;return`<div class="production-ui" data-production-floor="${index}"><div class="production-label"><span>${active?`📚 ${floor.taughtSkill} · ${floor.studentIds.length}人`:'点击设置课程'}</span><span class="production-time">${active?Math.max(0,Math.ceil((GARDEN_MS-(Date.now()-floor.schoolStartedAt))/1000))+'s':'待命'}</span></div><div class="production-track"><i class="production-fill" style="width:${progress}%"></i></div></div>`}if(floor.type==='barber'){const active=floor.barberId&&floor.currentClientId,progress=active&&floor.barberStartedAt?Math.min(100,(Date.now()-floor.barberStartedAt)/CYCLE_MS*100):0;return`<div class="production-ui" data-production-floor="${index}"><div class="production-label"><span>${active?'✂ 理发中':floor.barberId?`排队 ${floor.barberQueue.length} 人`:'选择理发师'}</span><span class="production-time">${active?Math.max(0,Math.ceil((CYCLE_MS-(Date.now()-floor.barberStartedAt))/1000))+'s':'待命'}</span></div><div class="production-track"><i class="production-fill" style="width:${progress}%"></i></div></div>`}if(!production&&!effect)return`<span class="room-worker-hint">${workerCount?`${workerCount}/${roomCapacity(floor)} 人工作`:'点击选择员工'}</span>`;const duration=effect?GARDEN_MS:CYCLE_MS,progress=workerCount&&floor.cycleStartedAt?Math.min(100,(Date.now()-floor.cycleStartedAt)/duration*100):0,label=effect?`${effect.label} · ${workerCount}人`:`${production.label} ×${workerCount||0}`,stock=roomStockLabel(floor);return`<div class="production-ui" data-production-floor="${index}"><div class="production-label"><span>${stock||label}</span><span class="production-time">${workerCount?Math.max(0,Math.ceil((duration-(Date.now()-floor.cycleStartedAt))/1000))+'s':'待命'}</span></div><div class="production-track"><i class="production-fill" style="width:${progress}%"></i></div></div>`}
  function personButton(person,role=''){const roleClass=['teacher','student'].includes(role)?` school-person role-${role}`:(['barber','client'].includes(role)?` barber-person role-${role}`:(['doctor','patient'].includes(role)?` clinic-person role-${role}`:(['mother','father'].includes(role)?` maternity-person role-${role}`:''))),clothingClass=person.hasClothes?' dressed':' no-clothes';return`<button class="person sprite-row-${Math.floor(person.sprite/4)}${roleClass}${clothingClass}" data-person="${person.id}" style="background-position:${spritePosition(person.sprite)}" aria-label="查看 ${person.name}"></button>`}
  function renderPrimaryFloors(){state.floors.forEach((floor,index)=>{if(floor.type!=='primary')return;const article=document.querySelector(`[data-room="${index}"]`),body=article?.querySelector('.floor-body'),teacher=residentById(floor.teacherId),students=floor.studentIds.map(residentById).filter(Boolean),active=primaryReady(floor),elapsed=active&&floor.schoolStartedAt?Date.now()-floor.schoolStartedAt:0;if(!article||!body)return;article.querySelector('.floor-head span').textContent=`教师 ${teacher?.name||'未选'} · 学生 ${students.length}/4`;body.innerHTML=`${teacher?personButton(teacher,'teacher'):''}${teacher&&students.length?'<span class="school-divider" aria-hidden="true"></span>':''}${students.map(student=>personButton(student,'student')).join('')}<div class="production-ui" data-primary-floor="${index}"><div class="production-label"><span>${active?`📖 ${floor.taughtSkill} · ${students.length}人`:'点击设置小学课程'}</span><span class="production-time">${active?Math.max(0,Math.ceil((PRIMARY_MS-elapsed)/1000))+'s':'待命'}</span></div><div class="production-track"><i class="production-fill" style="width:${active?Math.min(100,elapsed/PRIMARY_MS*100):0}%"></i></div></div>`})}
  function remapFloorNumber(number,a,b){return number===a?b:number===b?a:number}
  function moveFloor(index,direction){const target=index+direction;if(target<0||target>=state.floors.length)return;[state.floors[index],state.floors[target]]=[state.floors[target],state.floors[index]];const remapTrip=trip=>{if(!trip)return;if(Number.isInteger(trip.originFloor))trip.originFloor=remapFloorNumber(trip.originFloor,index,target);if(Number.isInteger(trip.foodFloor))trip.foodFloor=remapFloorNumber(trip.foodFloor,index,target)};elevator.queue.forEach(remapTrip);remapTrip(elevator.trip);activeRoomIndex=null;closeSheets();save();render();toast(`${ROOMS[state.floors[target].type].name} 已移动到 F${target+1}`)}
  function renderFloorControls(){document.querySelectorAll('.floor').forEach((article,index)=>{article.insertAdjacentHTML('afterbegin',`<div class="floor-move-controls"><button type="button" data-floor-up="${index}" ${index===state.floors.length-1?'disabled':''} aria-label="楼层上移">▲</button><button type="button" data-floor-down="${index}" ${index===0?'disabled':''} aria-label="楼层下移">▼</button></div>`)});document.querySelectorAll('[data-floor-up]').forEach(button=>button.onclick=event=>{event.stopPropagation();moveFloor(Number(button.dataset.floorUp),1)});document.querySelectorAll('[data-floor-down]').forEach(button=>button.onclick=event=>{event.stopPropagation();moveFloor(Number(button.dataset.floorDown),-1)})}
  function renderClinicFloors(){state.floors.forEach((floor,index)=>{if(floor.type!=='clinic')return;const article=document.querySelector(`[data-room="${index}"]`),body=article?.querySelector('.floor-body'),doctors=floor.workerIds.map(residentById).filter(Boolean),patients=state.people.filter(person=>person.sick&&person.clinicFloorId===floor.id);if(!article||!body)return;article.querySelector('.floor-head span').textContent=`医生 ${doctors.length} · 病人 ${patients.length}`;body.innerHTML=`${doctors.map(person=>personButton(person,'doctor')).join('')}${doctors.length&&patients.length?'<span class="school-divider" aria-hidden="true"></span>':''}${patients.map(person=>personButton(person,'patient')).join('')}<div class="production-ui"><div class="production-label"><span>${doctors.length?'诊所开放':'至少需要1名医生'}</span><span class="production-time">${patients.length?Math.max(0,Math.ceil((Math.min(...patients.map(person=>person.sickUntil||Date.now()))-Date.now())/1000))+'s':'待命'}</span></div><div class="production-track"><i class="production-fill" style="width:${patients.length?Math.min(100,(1-Math.max(0,Math.min(...patients.map(person=>person.sickUntil||Date.now()))-Date.now())/CLINIC_MS)*100):0}%"></i></div></div>`})}
  function renderMaternityFloors(){state.floors.forEach((floor,index)=>{if(floor.type!=='maternity')return;const article=document.querySelector(`[data-room="${index}"]`),body=article?.querySelector('.floor-body'),doctor=floor.workerIds.map(residentById).find(person=>person&&meetsWorkerSkill(person,floor)),family=floor.maternityFamilyIds.map(residentById).filter(Boolean),mother=family.find(person=>person.gender==='女'),father=family.find(person=>person.gender==='男');if(!article||!body)return;article.querySelector('.floor-head span').textContent=`医生 ${doctor?.name||'未选'} · 待产家庭 ${mother&&father?'1':'0'}`;body.innerHTML=`${doctor?personButton(doctor,'doctor'):''}${doctor&&family.length?'<span class="school-divider" aria-hidden="true"></span>':''}${mother?personButton(mother,'mother'):''}${father?personButton(father,'father'):''}<div class="production-ui"><div class="production-label"><span>${doctor&&mother&&father?'待产准备完成':doctor?'等待父母入住':'需要合格医生'}</span><span class="production-time">${mother?.pregnancy?Math.max(0,Math.ceil((mother.pregnancy.dueAt-Date.now())/DAY_MS))+'天':'待命'}</span></div><div class="production-track"><i class="production-fill" style="width:${mother?.pregnancy?Math.min(100,Math.max(0,1-(mother.pregnancy.dueAt-Date.now())/PREGNANCY_MS)*100):0}%"></i></div></div>`})}
  function renderTower(){
    const assigned=assignedPersonIds(),travelingId=elevator.trip?.personId,haircutIds=new Set(state.floors.map(floor=>floor.currentClientId).filter(Boolean));$('tower').innerHTML=state.floors.map((floor,index)=>{const room=ROOMS[floor.type],residents=(floor.residents||[]).map(residentById).filter(Boolean),regularWorkers=(floor.workerIds||[]).map(residentById).filter(Boolean),teacher=residentById(floor.teacherId),students=(floor.studentIds||[]).map(residentById).filter(Boolean),barber=residentById(floor.barberId),client=residentById(floor.currentClientId),schoolPeople=[teacher,...students].filter(Boolean),workers=(floor.type==='school'?schoolPeople:regularWorkers).filter(person=>person.id!==travelingId&&!haircutIds.has(person.id)),visible=floor.type==='dorm'?residents.filter(person=>!assigned.has(person.id)&&person.id!==travelingId&&!haircutIds.has(person.id)):workers,role=floor.type==='park'?'休闲':'员工',status=floor.type==='dorm'?`在宿舍 ${visible.length} · 入住 ${residents.length}/6`:(floor.type==='school'?`教师 ${teacher?.name||'未选'} · 学生 ${students.length}/3`:(floor.type==='barber'?`理发师 ${barber?.name||'未选'} · 排队 ${floor.barberQueue.length}`:`${role} ${regularWorkers.length}/${roomCapacity(floor)}${regularWorkers.length?' · '+regularWorkers.map(worker=>worker.name).join('、'):''}`)),peopleHtml=floor.type==='school'?`${teacher&&teacher.id!==travelingId&&!haircutIds.has(teacher.id)?personButton(teacher,'teacher'):''}${teacher&&students.length?'<span class="school-divider" aria-hidden="true"></span>':''}${students.filter(student=>student.id!==travelingId&&!haircutIds.has(student.id)).map(student=>personButton(student,'student')).join('')}`:(floor.type==='barber'?`${barber?personButton(barber,'barber'):''}${client?personButton(client,'client'):''}`:visible.map(person=>personButton(person)).join(''));return`<article class="floor room-${floor.type}" ${floor.type!=='dorm'?`data-room="${index}"`:''}><div class="floor-head"><b>F${index+1} · ${room.name}</b><span>${status}</span></div><div class="floor-body">${peopleHtml}${floor.type!=='dorm'?productionMarkup(floor,index):''}</div><span class="elevator-door" aria-hidden="true">F${index+1}</span></article>`}).join('')+`<div id="elevatorCar" class="elevator-car" style="--elevator-floor:${elevator.floor}"><span id="elevatorPassenger" class="elevator-passenger" hidden></span></div>`;
    renderPrimaryFloors();renderClinicFloors();renderMaternityFloors();renderFloorControls();const awayIds=new Set([...document.querySelectorAll('.floor:not(.room-dorm) [data-person]')].map(button=>button.dataset.person));document.querySelectorAll('.room-dorm [data-person]').forEach(button=>{if(awayIds.has(button.dataset.person))button.remove()});
    document.querySelectorAll('[data-person]').forEach(button=>button.onclick=event=>{event.stopPropagation();const person=residentById(button.dataset.person);openPerson(button.dataset.person);if(person){$('sheetMeta').textContent+=` · 学历 ${person.education||'无'}`;renderServiceChoices(person)}});document.querySelectorAll('[data-room]').forEach(room=>room.onclick=()=>{const index=Number(room.dataset.room),type=state.floors[index]?.type;type==='barber'?openBarber(index):type==='primary'?openPrimary(index):type==='maternity'?openMaternity(index):openRoom(index)});updateElevatorVisual();
  }
  function renderCatalog(){$('categoryTabs').innerHTML=CATEGORIES.map(category=>`<button type="button" class="${activeCategory===category?'active':''}" data-category="${category}">${category}</button>`).join('');const rooms=Object.entries(ROOMS).filter(([,room])=>activeCategory==='全部'||room.category===activeCategory);$('roomCatalog').innerHTML=rooms.map(([type,room])=>`<article class="room-card"><div class="room-thumb room-${type}" aria-hidden="true"></div><div><h3>${room.name} · ${room.category}</h3><p>${room.description}</p></div><button type="button" data-build="${type}" ${state.money<room.cost?'disabled':''}>${euro(room.cost)}</button></article>`).join('');document.querySelectorAll('[data-category]').forEach(button=>button.onclick=()=>{activeCategory=button.dataset.category;renderCatalog()});document.querySelectorAll('[data-build]').forEach(button=>button.onclick=()=>buildRoom(button.dataset.build))}
  function renderTasks(){
    const peopleCount=state.people.length||1,average=key=>Math.round(state.people.reduce((sum,person)=>sum+(person[key]||0),0)/peopleCount),assigned=assignedPersonIds(),students=state.floors.reduce((sum,floor)=>sum+floor.studentIds.length,0),waiting=state.floors.reduce((sum,floor)=>sum+floor.barberQueue.length+(floor.currentClientId?1:0),0),lowSatiety=state.people.filter(person=>person.satiety<35).length,lowSatisfaction=state.people.filter(person=>person.satisfaction<35).length;
    const floorsBy=category=>state.floors.filter(floor=>ROOMS[floor.type].category===category),workersIn=floors=>floors.reduce((sum,floor)=>sum+floor.workerIds.length+(floor.teacherId?1:0)+(floor.barberId?1:0),0),badge=(level,text)=>`<span class="health-badge ${level}">${text}</span>`,report=(category,level,text,detail)=>`<article class="category-report"><h4>${category}</h4>${badge(level,text)}<p>${detail}</p></article>`;
    const dorms=floorsBy('居住类'),food=floorsBy('食品类'),economic=floorsBy('经济类'),markets=economic.filter(f=>f.type==='market'),clothingStores=economic.filter(f=>f.type==='clothing'),parks=floorsBy('满意类'),schools=floorsBy('技能类'),services=floorsBy('服务类'),beds=dorms.length*6,foodWorkers=workersIn(food),vegRate=food.filter(f=>f.type==='garden').reduce((sum,f)=>sum+f.workerIds.length,0),farmRate=food.filter(f=>f.type==='farm').reduce((sum,f)=>sum+f.workerIds.length,0),parkPeople=parks.reduce((sum,f)=>sum+f.workerIds.length,0),incomeRate=markets.reduce((sum,f)=>sum+f.workerIds.length*10,0),clothingStock=clothingStores.reduce((sum,f)=>sum+f.clothingStock,0),studentCount=schools.reduce((sum,f)=>sum+f.studentIds.length,0),barberRooms=services.filter(f=>f.type==='barber'),maternityRooms=services.filter(f=>f.type==='maternity'),barbers=barberRooms.filter(f=>f.barberId).length,maternityDoctors=maternityRooms.filter(f=>f.workerIds.some(id=>meetsWorkerSkill(residentById(id),f))).length;
    const residentHtml=`<section class="status-section"><h3>人物状态</h3><div class="status-grid"><div class="status-metric"><span>平均满意度</span><b>${average('satisfaction')}</b></div><div class="status-metric"><span>平均饱腹感</span><b>${average('satiety')}</b></div><div class="status-metric"><span>已安排／总人口</span><b>${assigned.size}/${state.people.length}</b></div><div class="status-metric"><span>在学／待理发</span><b>${students}/${waiting}</b></div></div>${lowSatiety||lowSatisfaction?`<article class="category-report"><h4>居民预警</h4>${badge('weak','需关注')}<p>${lowSatiety} 人饱腹感低于 35，${lowSatisfaction} 人满意度低于 35。</p></article>`:''}</section>`;
    const reports=[report('居住类',beds<=state.people.length?'weak':beds-state.people.length<=2?'watch':'good',beds<=state.people.length?'已住满':beds-state.people.length<=2?'接近满员':'正常',`${dorms.length} 间宿舍 · 床位 ${state.people.length}/${beds} · 空余 ${Math.max(0,beds-state.people.length)}`),report('食品类',!food.length||!foodWorkers?'weak':state.inventory.vegetables+state.inventory.meat<state.people.length?'watch':'good',!food.length||!foodWorkers?'供给薄弱':state.inventory.vegetables+state.inventory.meat<state.people.length?'库存偏低':'正常',`${food.length} 个房间 · ${foodWorkers} 名员工 · 每20秒：蔬菜 ${vegRate}、肉 ${farmRate}、牛奶 ${farmRate} · 当前餐食 ${state.inventory.vegetables+state.inventory.meat}`),report('满意类',!parks.length?'weak':parkPeople?'good':'watch',!parks.length?'尚未建设':parkPeople?'运转中':'无人使用',`${parks.length} 个花园 · ${parkPeople} 人休闲 · 每60秒合计满意度＋${parkPeople*5}`),report('经济类',!economic.length?'weak':incomeRate||clothingStores.some(f=>f.workerIds.length)?'good':'watch',!economic.length?'尚未建设':incomeRate||clothingStores.some(f=>f.workerIds.length)?'运转中':'无人工作',`${markets.length} 个超市（每20秒 €${incomeRate}）· ${clothingStores.length} 间服装店 · 成衣库存 ${clothingStock}`),report('技能类',!schools.length?'weak':studentCount&&schools.some(f=>schoolReady(f))?'good':'watch',!schools.length?'尚未建设':studentCount?'教学中':'没有学生',`${schools.length} 所学校 · ${studentCount} 名学生 · 每分钟最多增加 ${studentCount} 技能点`),report('服务类',!services.length?'weak':barbers||maternityDoctors?'good':'watch',!services.length?'尚未建设':barbers||maternityDoctors?'部分营业':'缺少专业人员',`${barberRooms.length} 间理发店（${barbers} 名理发师）· ${maternityRooms.length} 间助产室（${maternityDoctors} 名医生）· 待理发 ${waiting} 人`)];
    $('taskList').innerHTML=residentHtml+`<section class="status-section"><h3>六类房间产出</h3>${reports.join('')}</section>`
  }
  function renderInventory(){$('vegetableCount').textContent=state.inventory.vegetables;$('meatCount').textContent=state.inventory.meat;$('milkCount').textContent=state.inventory.milk}
  function renderOverview(){const counts=Object.entries(ROOMS).map(([type,room])=>`${room.name} ${state.floors.filter(f=>f.type===type).length}`).join(' · '),working=state.floors.filter(f=>f.type!=='park').reduce((total,floor)=>total+floor.workerIds.length+(floor.teacherId?1:0),0),students=state.floors.reduce((total,floor)=>total+floor.studentIds.length,0),couples=state.people.filter(person=>person.spouseId).length/2;$('overview').innerHTML=`<div class="overview-card"><span>当前资金</span><b>${euro(state.money)}</b></div><div class="overview-card"><span>大楼层数</span><b>${state.floors.length}</b></div><div class="overview-card"><span>居民／床位</span><b>${state.people.length}/${bedCapacity()}</b></div><div class="overview-card"><span>在职／在学</span><b>${working}/${students}</b></div><div class="overview-card"><span>已婚家庭</span><b>${couples}</b></div><div class="overview-card"><span>怀孕人数</span><b>${activePregnancies()}</b></div><div class="overview-card room-summary"><span>食物库存</span><b>蔬菜 ${state.inventory.vegetables} · 肉 ${state.inventory.meat} · 牛奶 ${state.inventory.milk}</b></div><div class="overview-card room-summary"><span>房间组成</span><b>${counts}</b></div>`}
  function render(){const beds=state.floors.filter(f=>f.type==='dorm').length*6;$('headerMoney').textContent=euro(state.money);$('floorCount').textContent=state.floors.length;$('populationCount').textContent=state.people.length;$('bedCount').textContent=Math.max(0,beds-state.people.length);$('shortVersion').textContent=VERSION.replace(/^v/,'').split('+')[0];$('currentVersion').textContent=VERSION;renderClock();renderInventory();renderTower();renderCatalog();renderTasks();renderOverview()}

  function openPerson(id){const person=residentById(id);if(!person)return;const job=workerFloor(id),floorIndex=job?state.floors.indexOf(job):-1,spouse=residentById(person.spouseId),place=job?(job.type==='park'?`F${floorIndex+1} 花园休闲`:(job.type==='school'?(job.teacherId===id?`F${floorIndex+1} 任教`:`F${floorIndex+1} 上学`):`F${floorIndex+1} ${ROOMS[job.type].name}`)):'未安排';$('sheetSprite').style.backgroundPosition=spritePosition(person.sprite);$('sheetName').textContent=person.name;$('sheetMeta').textContent=`${person.gender} · ${person.age} 岁 · ${place}${spouse?` · 配偶 ${spouse.name}`:''}${person.pregnancy?` · 怀孕中（${Math.max(0,Math.ceil((person.pregnancy.dueAt-Date.now())/60000))}分钟）`:''}`;$('sheetSkills').innerHTML=`<h3>当前状态</h3><div class="vital-grid"><div class="skill-row vital"><span>饱腹</span><div class="skill-track"><i style="width:${person.satiety}%"></i></div><b>${person.satiety}</b></div><div class="skill-row vital"><span>满意</span><div class="skill-track"><i style="width:${person.satisfaction}%"></i></div><b>${person.satisfaction}</b></div></div><h3>能力</h3><div class="ability-grid">${SKILLS.map(skill=>`<div class="ability-item"><span>${skill}</span><b>${person.skills[skill]}</b><div class="skill-track"><i style="width:${Math.min(100,person.skills[skill]*20)}%"></i></div></div>`).join('')}</div>`;$('dietChoices').innerHTML=`<h3>餐食</h3><div class="diet-buttons"><button data-diet="auto" class="${person.foodPreference==='auto'?'selected':''}">自动</button><button data-diet="vegetables" class="${person.foodPreference==='vegetables'?'selected':''}">蔬菜</button><button data-diet="meat" class="${person.foodPreference==='meat'?'selected':''}">肉类</button></div>`;const milkPreference=person.milkPreference==='auto'?'both':person.milkPreference;$('milkChoices').innerHTML=`<h3>牛奶 <small>每次满意＋1</small></h3><div class="milk-buttons"><button data-milk="both" class="${milkPreference==='both'?'selected':''}"><b>早晚</b><small>06 · 20</small></button><button data-milk="morning" class="${milkPreference==='morning'?'selected':''}"><b>早</b><small>06:00</small></button><button data-milk="evening" class="${milkPreference==='evening'?'selected':''}"><b>晚</b><small>20:00</small></button><button data-milk="none" class="${milkPreference==='none'?'selected':''}"><b>关闭</b><small>不饮用</small></button></div>`;document.querySelectorAll('[data-diet]').forEach(button=>button.onclick=()=>setFoodPreference(person.id,button.dataset.diet));document.querySelectorAll('[data-milk]').forEach(button=>button.onclick=()=>setMilkPreference(person.id,button.dataset.milk));closeSheets();$('personSheet').classList.add('show');$('backdrop').classList.add('show')}
  function setFoodPreference(id,preference){const person=residentById(id);if(!person)return;person.foodPreference=preference;save();openPerson(id);toast(`${person.name} 的餐食选择已更新`)}
  function setMilkPreference(id,preference){const person=residentById(id);if(!person)return;person.milkPreference=preference;save();openPerson(id);toast(`${person.name} 的牛奶安排已更新`)}
  function haircutFloorFor(id){return state.floors.find(floor=>floor.type==='barber'&&(floor.currentClientId===id||floor.barberQueue.includes(id)))}
  function removeHaircutAppointments(id){state.floors.filter(floor=>floor.type==='barber').forEach(floor=>{floor.barberQueue=floor.barberQueue.filter(clientId=>clientId!==id);if(floor.currentClientId===id){floor.currentClientId=null;floor.barberStartedAt=null}})}
  function renderServiceChoices(person){const appointment=haircutFloorFor(person.id),floorIndex=appointment?state.floors.indexOf(appointment):-1,isBarber=state.floors.some(floor=>floor.barberId===person.id),isCurrent=appointment?.currentClientId===person.id;$('serviceChoices').innerHTML=`<h3>服务</h3><div class="diet-buttons">${isBarber?'<button disabled>理发师工作中</button>':(person.age<18?'<button disabled>未成年暂不理发</button>':(appointment?`<button class="selected" disabled>${isCurrent?'正在理发':`已预约 F${floorIndex+1} · 前方 ${appointment.barberQueue.indexOf(person.id)} 人`}</button>${isCurrent?'':`<button class="service-button" data-cancel-haircut="${person.id}">取消预约</button>`}`:`<button class="service-button" data-book-haircut="${person.id}">预约理发</button>`))}</div>`;document.querySelector('[data-book-haircut]')?.addEventListener('click',()=>bookHaircut(person.id));document.querySelector('[data-cancel-haircut]')?.addEventListener('click',()=>cancelHaircut(person.id))}
  const renderServicePanel=renderServiceChoices;renderServiceChoices=function(person){const spouse=residentById(person.spouseId),sharedGarden=state.floors.find(floor=>floor.type==='park'&&floor.workerIds.includes(person.id)&&floor.workerIds.includes(person.spouseId)),pregnancyBlocked=person.gender==='女'&&person.age<=40&&!person.pregnancy&&spouse&&person.satisfaction>=100&&spouse.satisfaction>=100&&sharedGarden&&state.people.length+activePregnancies()>=bedCapacity(),notice=$('sheetNotice'),children=state.people.filter(child=>(child.parentIds||[]).includes(person.id)),sons=children.filter(child=>child.gender==='男').length,daughters=children.filter(child=>child.gender==='女').length,parents=(person.parentIds||[]).map(residentById).filter(Boolean),father=parents.find(parent=>parent.gender==='男'),mother=parents.find(parent=>parent.gender==='女'),childLabel=children.length?`${sons?sons+'子':''}${sons&&daughters?' ':''}${daughters?daughters+'女':''}`:'无子女';notice.hidden=!pregnancyBlocked;notice.textContent=pregnancyBlocked?'床位不足，暂时无法怀孕。增建宿舍后会自动恢复。':'';$('sheetFamily').innerHTML=`<h3>亲属</h3><div class="family-list"><span><small>子女</small><b>${childLabel}</b></span>${father?`<span><small>父亲</small><b>${father.name} · ${father.age}岁</b></span>`:''}${mother?`<span><small>母亲</small><b>${mother.name} · ${mother.age}岁</b></span>`:''}</div>`;renderServicePanel(person)}
  const renderFamilyPanel=renderServiceChoices;renderServiceChoices=function(person){renderFamilyPanel(person);if(person.pregnancy){const days=Math.max(0,Math.ceil((person.pregnancy.dueAt-Date.now())/DAY_MS));$('sheetMeta').textContent=$('sheetMeta').textContent.replace(/怀孕中（.*?分钟）/,`怀孕中（约${days}天）`)}}
  const renderPregnancyPanel=renderServiceChoices;renderServiceChoices=function(person){renderPregnancyPanel(person);$('sheetSprite').classList.toggle('no-clothes',!person.hasClothes);$('sheetSprite').classList.toggle('dressed',person.hasClothes);$('sheetMeta').textContent+=person.hasClothes?' · 穿衣：已着装（满意＋10）':' · 穿衣：背心内衣'}
  function bookHaircut(id){const person=residentById(id);if(!person||person.age<18)return;if(state.floors.some(floor=>floor.barberId===id))return toast('理发师不能给自己预约');if(haircutFloorFor(id))return toast('已经预约过理发');const origin=personFloorIndex(person),candidates=state.floors.map((floor,index)=>({floor,index})).filter(entry=>entry.floor.type==='barber'&&entry.floor.barberId).sort((a,b)=>Math.abs(a.index-origin)-Math.abs(b.index-origin));if(!candidates.length)return toast('暂无已安排理发师的理发店');candidates[0].floor.barberQueue.push(id);save();render();openPerson(id);renderServiceChoices(person);toast(`${person.name} 已预约 F${candidates[0].index+1} 理发店`)}
  function cancelHaircut(id){const person=residentById(id),floor=haircutFloorFor(id);if(!floor||floor.currentClientId===id)return;floor.barberQueue=floor.barberQueue.filter(clientId=>clientId!==id);save();render();openPerson(id);renderServiceChoices(person);toast(`${person.name} 已取消理发预约`)}
  function openBarber(index){const floor=state.floors[index],canWork=person=>person.age>16&&!person.sick&&meetsWorkerSkill(person,floor)&&floor.currentClientId!==person.id;activeRoomIndex=index;$('roomSheetName').textContent=`F${index+1} · 理发店`;$('roomSheetMeta').textContent=`需要服务技能至少 3 · 理发师：${residentById(floor.barberId)?.name||'未选择'} · 当前顾客：${residentById(floor.currentClientId)?.name||'无'} · 排队：${floor.barberQueue.length}`;$('workerOptions').innerHTML=`<button class="worker-option ${!floor.barberId?'selected':''}" data-barber-worker=""><span class="room-sheet-icon" style="width:36px;height:36px;margin:0;font-size:16px">休</span><span><strong>不安排理发师</strong><small>停止接待新顾客</small></span><em>${!floor.barberId?'✓':''}</em></button>`+eligibleFirst(state.people,canWork).map(person=>{const selected=floor.barberId===person.id,job=workerFloor(person.id),eligible=canWork(person),status=floor.currentClientId===person.id?'正在理发，不能任职':person.sick?'生病中':person.age<=16?'需要超过16岁':!meetsWorkerSkill(person,floor)?`服务技能 ${person.skills['服务']||0}/3`:(selected?'本店理发师':job?`当前在 F${state.floors.indexOf(job)+1} ${ROOMS[job.type].name}`:'目前未安排');return`<button class="worker-option ${selected?'selected':''} ${!eligible?'compact-ineligible':''}" data-barber-worker="${person.id}" ${!eligible?'disabled':''}><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name}</strong><small>${status}</small></span><em>${selected?'取消':'选择'}</em></button>`}).join('');document.querySelectorAll('[data-barber-worker]').forEach(button=>button.onclick=()=>setBarber(button.dataset.barberWorker||null));closeSheets();$('roomSheet').classList.add('show');$('backdrop').classList.add('show')}
  function setBarber(id){const floor=state.floors[activeRoomIndex],previous=residentById(floor.barberId);if(!id||floor.barberId===id){floor.barberId=null;if(floor.currentClientId)floor.barberQueue.unshift(floor.currentClientId);floor.currentClientId=null;floor.barberStartedAt=null;save();render();openBarber(activeRoomIndex);return toast(previous?`${previous.name} 已停止理发工作`:'尚未安排理发师')}const person=residentById(id);if(!person||person.age<=16||person.sick)return toast('理发师需要超过16岁且健康');if(!meetsWorkerSkill(person,floor))return toast('理发师需要服务技能至少达到 3');removeHaircutAppointments(id);removePersonAssignments(id,floor);floor.barberId=id;save();render();openBarber(activeRoomIndex);toast(`${person.name} 成为理发师`)}
  function openMaternity(index){const floor=state.floors[index],canDoctor=person=>person.age>16&&!person.sick&&meetsWorkerSkill(person,floor),doctor=floor.workerIds.map(residentById).find(Boolean),pregnant=state.people.filter(person=>person.pregnancy);activeRoomIndex=index;$('roomSheetName').textContent=`F${index+1} · 助产室`;$('roomSheetMeta').textContent=`医生：${doctor?.name||'未选择'} · 门槛：服务≥3、科研=5 · 一次接待一个家庭`;$('workerOptions').innerHTML=`<div class="school-section"><h3>1. 安排医生</h3>${eligibleFirst(state.people,canDoctor).map(person=>{const eligible=canDoctor(person),selected=floor.workerIds.includes(person.id),reason=person.sick?'生病中':person.age<=16?'需要超过16岁':!meetsWorkerSkill(person,floor)?requirementText(floor):currentPosition(person,floor);return`<button class="worker-option ${selected?'selected':''} ${!eligible?'compact-ineligible':''}" data-maternity-doctor="${person.id}" ${!eligible?'disabled':''}><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name}</strong><small>${reason}</small></span><em>${selected?'取消':'选择'}</em></button>`}).join('')}</div><div class="school-section"><h3>2. 安排待产家庭</h3>${pregnant.length?pregnant.map(mother=>{const father=residentById(mother.pregnancy.fatherId),remaining=mother.pregnancy.dueAt-Date.now(),canAdmit=remaining<=DAY_MS,selected=floor.maternityFamilyIds.includes(mother.id)&&floor.maternityFamilyIds.includes(father?.id),label=remaining>0?`距足月约 ${Math.ceil(remaining/DAY_MS)} 天`:`已足月 ${Math.floor(Math.abs(remaining)/DAY_MS)} 天`;return`<button class="worker-option ${selected?'selected':''} ${!canAdmit&&!selected?'compact-ineligible':''}" data-maternity-family="${mother.id}" ${!father||(!canAdmit&&!selected)?'disabled':''}><span class="worker-mini" style="background-position:${spritePosition(mother.sprite)}"></span><span><strong>${mother.name} ＋ ${father?.name||'父亲缺失'}</strong><small>${canAdmit||selected?label:'足月前 1 天可入住'}</small></span><em>${selected?'离院':'入住'}</em></button>`}).join(''):'<small>当前没有孕妇。</small>'}</div>`;document.querySelectorAll('[data-maternity-doctor]').forEach(button=>button.onclick=()=>setMaternityDoctor(button.dataset.maternityDoctor));document.querySelectorAll('[data-maternity-family]').forEach(button=>button.onclick=()=>toggleMaternityFamily(button.dataset.maternityFamily));closeSheets();$('roomSheet').classList.add('show');$('backdrop').classList.add('show')}
  function setMaternityDoctor(id){const floor=state.floors[activeRoomIndex],person=residentById(id),selected=floor.workerIds.includes(id);if(selected)floor.workerIds=[];else{if(!person||person.age<=16||person.sick||!meetsWorkerSkill(person,floor))return toast('助产医生需要服务至少 3 且科研达到 5');removePersonAssignments(id,floor);floor.workerIds=[id]}save();render();openMaternity(activeRoomIndex);toast(selected?'助产医生已离岗':`${person.name} 成为助产医生`)}
  function toggleMaternityFamily(motherId){const floor=state.floors[activeRoomIndex],mother=residentById(motherId),father=residentById(mother?.pregnancy?.fatherId);if(!mother?.pregnancy||!father)return toast('待产家庭信息不完整');const selected=floor.maternityFamilyIds.includes(mother.id)&&floor.maternityFamilyIds.includes(father.id);if(selected)floor.maternityFamilyIds=[];else{if(mother.pregnancy.dueAt-Date.now()>DAY_MS)return toast('足月前 1 天才可进入助产室');[mother,father].forEach(person=>removePersonAssignments(person.id,floor));state.floors.filter(room=>room.type==='maternity'&&room!==floor).forEach(room=>room.maternityFamilyIds=room.maternityFamilyIds.filter(id=>id!==mother.id&&id!==father.id));floor.maternityFamilyIds=[mother.id,father.id]}save();render();openMaternity(activeRoomIndex);toast(selected?`${mother.name} 与 ${father.name} 已离开助产室`:`${mother.name} 与 ${father.name} 已入住待产`)}
  function openRoom(index){
    const floor=state.floors[index],room=ROOMS[floor?.type];if(!floor||floor.type==='dorm')return;if(floor.type==='school')return openSchool(index);const capacity=roomCapacity(floor),isGarden=floor.type==='park';if(isGarden&&checkRelationships(Date.now())){save();render()}activeRoomIndex=index;$('roomSheetName').textContent=`F${index+1} · ${room.name}（${floor.workerIds.length}/${capacity}）`;$('roomSheetMeta').textContent=isGarden?`${room.description} 结婚门槛：同一花园内一男一女均为未婚，且双方满意度达到 100。`:(room.production?`${room.description} 生产只在有人工作时进行。`:`最多选择 ${capacity} 名居民在这里工作。`);
    const none=`<button class="worker-option ${!floor.workerIds.length?'selected':''}" data-worker=""><span class="room-sheet-icon" style="width:36px;height:36px;margin:0;font-size:16px">休</span><span><strong>清空员工</strong><small>取消本房间的全部安排</small></span><em>${!floor.workerIds.length?'✓':''}</em></button>`;
    const canWork=person=>!person.sick&&(isGarden||(person.age>16&&meetsWorkerSkill(person,floor)));$('workerOptions').innerHTML=none+eligibleFirst(state.people,canWork).map(person=>{const selected=floor.workerIds.includes(person.id),job=workerFloor(person.id),jobIndex=job?state.floors.indexOf(job):-1,tooYoung=person.age<=16&&!isGarden,lacksSkill=!isGarden&&!meetsWorkerSkill(person,floor),unavailable=!canWork(person),status=person.sick?'生病中，不能工作':(tooYoung?'需要超过16岁':(lacksSkill?`技能不足：需要${requirementText(floor)}`:(job?(job===floor?(isGarden?'正在花园休闲':'本房间员工'):`当前在 F${jobIndex+1} ${ROOMS[job.type].name}`):'目前未安排'))),detail=isGarden?`${person.gender} · ${person.age}岁 · 满意 ${person.satisfaction}/100 · ${person.spouseId?'已婚':'单身'}`:`${requirementText(floor)} · 满意 ${person.satisfaction}`;return`<button class="worker-option ${selected?'selected':''} ${unavailable?'compact-ineligible':''}" data-worker="${person.id}" ${unavailable?'disabled':''}><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name}</strong><small>${unavailable?status:`${detail} · ${status}`}</small></span><em>${selected?'取消':'选择'}</em></button>`}).join('');document.querySelectorAll('[data-worker]').forEach(button=>button.onclick=()=>assignWorker(button.dataset.worker||null));closeSheets();$('roomSheet').classList.add('show');$('backdrop').classList.add('show');
  }
  const renderWorkerRoom=openRoom;openRoom=function(index){renderWorkerRoom(index);const floor=state.floors[index];if(floor?.type!=='clothing')return;const reserveOptions=[0,1,2,3,5,10],people=eligibleFirst(state.people,person=>!person.hasClothes);$('workerOptions').insertAdjacentHTML('beforeend',`<div class="school-section clothing-settings"><h3>分配模式</h3><small>店内保留指定数量，超过的衣服自动按 €50/件出售。</small><div class="skill-choices">${reserveOptions.map(value=>`<button class="${floor.clothingReserve===value?'selected':''}" data-clothing-reserve="${value}">预留 ${value}</button>`).join('')}</div></div><div class="school-section"><h3>居民领取 · 当前库存 ${floor.clothingStock}</h3>${people.map(person=>`<button class="worker-option ${person.hasClothes?'compact-ineligible':''}" data-claim-clothing="${person.id}" ${person.hasClothes||floor.clothingStock<=0?'disabled':''}><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name}</strong><small>${person.hasClothes?'已有衣服 · 永久满意度＋10':'领取 1 件衣服并永久增加 10 满意度'}</small></span><em>${person.hasClothes?'已领取':'领取'}</em></button>`).join('')}</div>`);document.querySelectorAll('[data-clothing-reserve]').forEach(button=>button.onclick=()=>setClothingReserve(Number(button.dataset.clothingReserve)));document.querySelectorAll('[data-claim-clothing]').forEach(button=>button.onclick=()=>claimClothing(button.dataset.claimClothing))}
  function setClothingReserve(value){const floor=state.floors[activeRoomIndex];if(floor?.type!=='clothing')return;floor.clothingReserve=Math.max(0,value);const sold=Math.max(0,floor.clothingStock-floor.clothingReserve);if(sold){floor.clothingStock-=sold;state.money+=sold*50}save();render();openRoom(activeRoomIndex);toast(sold?`预留已更新，售出 ${sold} 件衣服，收入 ${euro(sold*50)}`:`服装店预留数量改为 ${floor.clothingReserve}`)}
  function claimClothing(id){const floor=state.floors[activeRoomIndex],person=residentById(id);if(floor?.type!=='clothing'||!person||person.hasClothes||floor.clothingStock<=0)return;floor.clothingStock-=1;person.hasClothes=true;person.clothingBonus=10;person.satisfaction=Math.min(100,person.satisfaction+10);save();render();openRoom(activeRoomIndex);toast(`${person.name} 穿上了新衣服，永久满意度＋10`)}
  function educationAtLeast(person,minimum='社区学校'){const levels=['无','小学','社区学校','硕士','博士'];return levels.indexOf(person?.education||'无')>=levels.indexOf(minimum)}
  function masteredSkills(person){return person?SKILLS.filter(skill=>(person.skills[skill]||0)>=5):[]}
  function canTeachSchool(person,skill=null){return Boolean(person&&person.age>16&&!person.sick&&educationAtLeast(person)&&masteredSkills(person).length&&(!skill||masteredSkills(person).includes(skill)))}
  function canTeachPrimary(person){return Boolean(person&&person.age>16&&!person.sick&&educationAtLeast(person)&&(person.skills['科研']||0)>=1)}
  function schoolReady(floor){const teacher=residentById(floor.teacherId);return Boolean(canTeachSchool(teacher,floor.taughtSkill)&&floor.studentIds.length)}
  function resetSchoolTimer(floor){floor.schoolStartedAt=schoolReady(floor)?Date.now():null}
  function personChoice(person,role,selected,disabled=false){const status=currentPosition(person),tooYoung=person.age<13;return`<button class="worker-option ${selected?'selected':''}" data-school-${role}="${person.id}" ${disabled||tooYoung?'disabled':''}><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name} · ${person.age}岁</strong><small>${person.talent} ${person.skills[person.talent]} · 当前：${status}${tooYoung?' · 请就读小学':''}</small></span><em>${selected?'取消':'选择'}</em></button>`}
  function currentPosition(person,exceptFloor=null){const job=workerFloor(person.id);if(!job||job===exceptFloor)return job===exceptFloor?'本房间已安排':'目前未安排';const index=state.floors.indexOf(job),role=job.type==='school'||job.type==='primary'?(job.teacherId===person.id?'教师':'学生'):(job.type==='park'?'花园休闲':job.type==='barber'?'理发师':'员工');return`F${index+1} ${ROOMS[job.type].name} · ${role}`}
  function schoolTeacherOption(person,floor){const selected=floor.teacherId===person.id,skills=masteredSkills(person).join('、');return`<button class="worker-option ${selected?'selected':''}" data-school-teacher="${person.id}"><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name} · ${person.education}</strong><small>满级：${skills} · 当前：${currentPosition(person,floor)}</small></span><em>${selected?'取消':'选择'}</em></button>`}
  function openSchool(index){
    const floor=state.floors[index];activeRoomIndex=index;$('roomSheetName').textContent=`F${index+1} · 社区学校`;$('roomSheetMeta').textContent=`教师：${residentById(floor.teacherId)?.name||'未选择'} · 课程：${floor.taughtSkill||'未选择'} · 学生：${floor.studentIds.length}/3 · 仅限13岁及以上`;
    const teacher=residentById(floor.teacherId),teachable=masteredSkills(teacher),teacherCandidates=state.people.filter(person=>canTeachSchool(person,floor.taughtSkill));$('workerOptions').innerHTML=`<div class="school-section"><h3>1. 选择教授技能</h3><div class="skill-choices">${SKILLS.map(skill=>`<button class="${floor.taughtSkill===skill?'selected':''}" data-school-skill="${skill}" ${teacher&&!teachable.includes(skill)?'disabled':''}>${skill}</button>`).join('')}</div><small>${teacher?`${teacher.name} 只能教授满级技能：${teachable.join('、')}`:'先选课程会筛选教师；先选教师会筛选课程。'}</small></div><div class="school-section"><h3>2. 可任教人物（学历≥社区学校，${teacherCandidates.length}名）</h3>${teacherCandidates.length?teacherCandidates.map(person=>schoolTeacherOption(person,floor)).join(''):'<small>当前没有符合该课程的教师。</small>'}</div><div class="school-section"><h3>3. 选择学生（13岁及以上，${floor.studentIds.length}/3）</h3>${state.people.map(person=>personChoice(person,'student',floor.studentIds.includes(person.id),floor.teacherId===person.id)).join('')}</div>`;
    document.querySelectorAll('[data-school-skill]').forEach(button=>button.onclick=()=>setSchoolSkill(button.dataset.schoolSkill));document.querySelectorAll('[data-school-teacher]').forEach(button=>button.onclick=()=>setSchoolTeacher(button.dataset.schoolTeacher));document.querySelectorAll('[data-school-student]').forEach(button=>button.onclick=()=>toggleSchoolStudent(button.dataset.schoolStudent));closeSheets();$('roomSheet').classList.add('show');$('backdrop').classList.add('show');
  }
  function setSchoolSkill(skill){const floor=state.floors[activeRoomIndex],teacher=residentById(floor.teacherId);if(teacher&&!masteredSkills(teacher).includes(skill))return toast(`${teacher.name} 的${skill}技能未达到 5 级，不能教授`);floor.taughtSkill=skill;resetSchoolTimer(floor);save();render();openSchool(activeRoomIndex);toast(`课程已改为${skill}`)}
  function setSchoolTeacher(id){const floor=state.floors[activeRoomIndex],person=residentById(id);if(!canTeachSchool(person,floor.taughtSkill))return toast('教师需要学历至少为社区学校，并拥有可教授的满级技能');if(floor.teacherId===id)floor.teacherId=null;else{removePersonAssignments(id,floor);floor.studentIds=floor.studentIds.filter(studentId=>studentId!==id);floor.teacherId=id;if(!floor.taughtSkill)floor.taughtSkill=masteredSkills(person)[0]}resetSchoolTimer(floor);save();render();openSchool(activeRoomIndex);toast(floor.teacherId?`${person.name} 成为教师，教授${floor.taughtSkill}`:'已取消教师')}
  function toggleSchoolStudent(id){const floor=state.floors[activeRoomIndex],person=residentById(id);if(!person||person.age<13)return toast('12 岁及以下儿童需要就读小学');if(floor.teacherId===id)return toast('教师不能同时作为学生');const selected=floor.studentIds.includes(id);if(!selected&&floor.studentIds.length>=3)return toast('社区学校最多容纳 3 名学生');if(selected)floor.studentIds=floor.studentIds.filter(studentId=>studentId!==id);else{removePersonAssignments(id,floor);floor.studentIds.push(id)}resetSchoolTimer(floor);save();render();openSchool(activeRoomIndex);toast(selected?`${person.name} 已停止上课`:`${person.name} 开始学习${floor.taughtSkill||'待选课程'}`)}
  function primaryReady(floor){const teacher=residentById(floor.teacherId);return Boolean(canTeachPrimary(teacher)&&floor.taughtSkill&&floor.studentIds.length)}
  function resetPrimaryTimer(floor){floor.schoolStartedAt=primaryReady(floor)?Date.now():null}
  function openPrimary(index){const floor=state.floors[index],teacher=residentById(floor.teacherId),teacherCandidates=state.people.filter(canTeachPrimary);activeRoomIndex=index;$('roomSheetName').textContent=`F${index+1} · 小学`;$('roomSheetMeta').textContent=`教师：${teacher?.name||'未选择'} · 课程：${floor.taughtSkill||'未选择'} · 学生：${floor.studentIds.length}/4 · 仅限12岁及以下`;$('workerOptions').innerHTML=`<div class="school-section"><h3>1. 选择课程</h3><div class="skill-choices">${SKILLS.map(skill=>`<button class="${floor.taughtSkill===skill?'selected':''}" data-primary-skill="${skill}">${skill}</button>`).join('')}</div></div><div class="school-section"><h3>2. 可任教人物（学历≥社区学校、科研≥1，${teacherCandidates.length}名）</h3>${teacherCandidates.length?teacherCandidates.map(person=>{const selected=floor.teacherId===person.id;return`<button class="worker-option ${selected?'selected':''}" data-primary-teacher="${person.id}"><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name} · ${person.education}</strong><small>科研 ${person.skills['科研']} · 当前：${currentPosition(person,floor)}</small></span><em>${selected?'取消':'选择'}</em></button>`}).join(''):'<small>当前没有学历、健康和科研技能均达标的教师。</small>'}</div><div class="school-section"><h3>3. 选择学生（12岁及以下，${floor.studentIds.length}/4）</h3>${state.people.map(person=>{const selected=floor.studentIds.includes(person.id),complete=SKILLS.every(skill=>(person.skills[skill]||0)>=1),tooOld=person.age>12;return`<button class="worker-option ${selected?'selected':''}" data-primary-student="${person.id}" ${floor.teacherId===person.id||tooOld?'disabled':''}><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name} · ${person.age}岁</strong><small>${tooOld?'年龄超过12岁，请去社区学校':`学历 ${person.education||'无'} · ${complete?'小学课程已全部完成':`${floor.taughtSkill||'待选'} ${person.skills[floor.taughtSkill]||0}/1`}`}</small></span><em>${selected?'取消':'选择'}</em></button>`}).join('')}</div>`;document.querySelectorAll('[data-primary-skill]').forEach(button=>button.onclick=()=>setPrimarySkill(button.dataset.primarySkill));document.querySelectorAll('[data-primary-teacher]').forEach(button=>button.onclick=()=>setPrimaryTeacher(button.dataset.primaryTeacher));document.querySelectorAll('[data-primary-student]').forEach(button=>button.onclick=()=>togglePrimaryStudent(button.dataset.primaryStudent));closeSheets();$('roomSheet').classList.add('show');$('backdrop').classList.add('show')}
  const renderPrimaryPanel=openPrimary;openPrimary=function(index){renderPrimaryPanel(index);const floor=state.floors[index];document.querySelectorAll('[data-primary-student]').forEach(button=>{const person=residentById(button.dataset.primaryStudent),small=button.querySelector('small');if(person&&small)small.textContent+=` · 当前：${currentPosition(person,floor)}`})}
  function setPrimarySkill(skill){const floor=state.floors[activeRoomIndex];floor.taughtSkill=skill;resetPrimaryTimer(floor);save();render();openPrimary(activeRoomIndex);toast(`小学课程已改为${skill}`)}
  function setPrimaryTeacher(id){const floor=state.floors[activeRoomIndex],person=residentById(id);if(!canTeachPrimary(person))return toast('小学教师需要学历至少为社区学校、健康、超过16岁且科研技能至少为 1');if(floor.teacherId===id)floor.teacherId=null;else{removePersonAssignments(id,floor);floor.studentIds=floor.studentIds.filter(studentId=>studentId!==id);floor.teacherId=id}resetPrimaryTimer(floor);save();render();openPrimary(activeRoomIndex);toast(floor.teacherId?`${person.name} 成为小学教师`:'已取消小学教师')}
  function togglePrimaryStudent(id){const floor=state.floors[activeRoomIndex],person=residentById(id);if(!person)return;if(person.age>12)return toast('超过 12 岁需要去社区学校进修');if(floor.teacherId===id)return toast('教师不能同时作为学生');const selected=floor.studentIds.includes(id);if(!selected&&floor.studentIds.length>=4)return toast('小学最多容纳 4 名学生');if(selected)floor.studentIds=floor.studentIds.filter(studentId=>studentId!==id);else{removePersonAssignments(id,floor);floor.studentIds.push(id)}resetPrimaryTimer(floor);save();render();openPrimary(activeRoomIndex);toast(selected?`${person.name} 已离开小学`:`${person.name} 开始上小学`)}
  function sanitizeStudentAges(){let changed=false;state.floors.filter(floor=>floor.type==='primary'||floor.type==='school').forEach(floor=>{const before=floor.studentIds.length;floor.studentIds=floor.studentIds.filter(id=>{const student=residentById(id);return student&&(floor.type==='primary'?student.age<=12:student.age>=13)});if(floor.studentIds.length!==before){floor.schoolStartedAt=null;changed=true}});if(changed){save();render()}return changed}
  function sanitizeTeacherQualifications(){let changed=false;state.floors.filter(floor=>floor.type==='primary'||floor.type==='school').forEach(floor=>{const teacher=residentById(floor.teacherId),qualified=floor.type==='primary'?canTeachPrimary(teacher):canTeachSchool(teacher,floor.taughtSkill);if(floor.teacherId&&!qualified){floor.teacherId=null;floor.schoolStartedAt=null;changed=true}});if(changed){save();render()}return changed}
  function assignWorker(workerId){
    const floor=state.floors[activeRoomIndex];if(!floor)return;const candidate=workerId?residentById(workerId):null;if(candidate&&candidate.age<=16&&floor.type!=='park')return toast('角色需要超过16岁才能工作');if(candidate?.sick)return toast('生病期间不能工作');
    if(candidate&&floor.type!=='park'&&!meetsWorkerSkill(candidate,floor))return toast(`需要${requirementText(floor)}才能在这里工作`);
    if(!workerId){floor.workerIds=[];floor.cycleStartedAt=null;save();render();openRoom(activeRoomIndex);return toast('已清空员工安排')}
    const selected=floor.workerIds.includes(workerId);
    if(!selected&&floor.workerIds.length>=roomCapacity(floor))return toast(`这个房间最多容纳 ${roomCapacity(floor)} 人`);
    if(selected){floor.workerIds=floor.workerIds.filter(id=>id!==workerId)}else{removePersonAssignments(workerId,floor);floor.workerIds.push(workerId)}
    floor.cycleStartedAt=floor.workerIds.length?Date.now():null;checkRelationships(Date.now());save();render();openRoom(activeRoomIndex);toast(selected?`${residentById(workerId).name} 已离开${floor.type==='park'?'花园':'工作'}`:`${residentById(workerId).name} 已进入${floor.type==='park'?'花园':'工作'}`);
  }
  function closeSheets(){$('personSheet').classList.remove('show');$('roomSheet').classList.remove('show');if($('deathNotice')?.hidden)$('backdrop').classList.remove('show')}

  function checkRelationships(now){
    let changed=false;
    state.people.forEach(person=>{if(person.spouseId&&!residentById(person.spouseId)){person.spouseId=null;changed=true}});
    state.floors.filter(floor=>floor.type==='park').forEach(garden=>{
      const visitors=garden.workerIds.map(residentById).filter(Boolean),singleMen=visitors.filter(person=>person.age>=18&&person.gender==='男'&&!person.spouseId&&person.satisfaction>=100),singleWomen=visitors.filter(person=>person.age>=18&&person.gender==='女'&&!person.spouseId&&person.satisfaction>=100);
      while(singleMen.length&&singleWomen.length){const husband=singleMen.shift(),wife=singleWomen.shift();husband.spouseId=wife.id;wife.spouseId=husband.id;changed=true;toast(`${husband.name} 和 ${wife.name} 结婚了！`)}
      visitors.filter(person=>person.gender==='女'&&person.age<=40&&person.spouseId&&!person.pregnancy&&person.satisfaction>=100).forEach(wife=>{const husband=residentById(wife.spouseId);if(!husband||husband.satisfaction<100||!garden.workerIds.includes(husband.id))return;if(state.people.length+activePregnancies()>=bedCapacity())return;wife.pregnancy={fatherId:husband.id,dueAt:now+PREGNANCY_MS,deliveryWarned:false,laborWarned:false};changed=true;toast(`${wife.name} 怀孕了，预计 9 天后生产`);celebrate(state.people.map(person=>person.id),'新生命即将到来！')});
    });
    return changed;
  }
  function createChild(mother,father){const gender=Math.random()<.5?'男':'女',parentSurnames=[father?.surname||father?.name?.slice(0,1),mother?.surname||mother?.name?.slice(0,1)].filter(Boolean),surname=random(parentSurnames.length?parentSurnames:SURNAMES),used=state.people.map(person=>person.name),now=Date.now(),name=randomName(gender,used,surname),sprites=gender==='男'?[0,2,4,6]:[1,3,5,7],currentSlot=mealSlotAt(now,state.createdAt),currentMilkSlot=milkSlotAt(now,state.createdAt);return{id:`p-${now}-${state.people.length}`,name,surname,gender,age:0,education:'无',talent:'无',satisfaction:60,satiety:100,satietyZeroSince:null,deathPending:false,foodPreference:'auto',milkPreference:'auto',lastMealSlot:currentSlot,lastMilkSlot:currentMilkSlot,spouseId:null,pregnancy:null,sick:false,sickCause:null,sickUntil:null,clinicFloorId:null,parentIds:[father?.id,mother.id].filter(Boolean),skills:Object.fromEntries(SKILLS.map(skill=>[skill,0])),sprite:random(sprites)}}
  function processBirths(now){
    let changed=false;
    state.people.filter(mother=>mother.pregnancy).forEach(mother=>{const pregnancy=mother.pregnancy,father=residentById(pregnancy.fatherId),remaining=pregnancy.dueAt-now;if(remaining<=DAY_MS&&!pregnancy.deliveryWarned){pregnancy.deliveryWarned=true;changed=true;toast(`${mother.name} 将在 1 天内足月，请安排父母进入助产室`)}if(remaining>0)return;const maternity=state.floors.find(floor=>floor.type==='maternity'&&floor.workerIds.some(id=>{const doctor=residentById(id);return doctor&&!doctor.sick&&doctor.age>16&&meetsWorkerSkill(doctor,floor)})&&floor.maternityFamilyIds.includes(mother.id)&&floor.maternityFamilyIds.includes(father?.id));if(maternity&&state.people.length<bedCapacity()){const dorm=state.floors.find(floor=>floor.type==='dorm'&&(floor.residents||[]).length<6);if(dorm){const child=createChild(mother,father);state.people.push(child);dorm.residents.push(child.id);mother.pregnancy=null;state.floors.filter(floor=>floor.type==='maternity').forEach(floor=>floor.maternityFamilyIds=floor.maternityFamilyIds.filter(id=>id!==mother.id&&id!==father?.id));changed=true;toast(`${mother.name} 在助产室生下了 ${child.name}！`);const celebrants=state.people.filter(person=>person.surname===child.surname||person.id===mother.id||person.id===father?.id).map(person=>person.id);celebrate(celebrants,`${child.name} 出生了！`);return}}if(!pregnancy.laborWarned){pregnancy.laborWarned=true;changed=true;toast(`${mother.name} 已足月，必须在 2 天内与配偶进入有医生的助产室`)}if(now>=pregnancy.dueAt+DAY_MS*2){mother.pregnancy=null;state.floors.filter(floor=>floor.type==='maternity').forEach(floor=>floor.maternityFamilyIds=floor.maternityFamilyIds.filter(id=>id!==mother.id&&id!==father?.id));changed=true;toast(`${mother.name} 未能及时进入助产室，妊娠终止`)}});
    return changed;
  }

  function renderClock(now=Date.now()){const elapsed=Math.max(0,now-state.createdAt),totalDay=Math.floor(elapsed/DAY_MS),year=Math.floor(totalDay/DAYS_PER_YEAR)+1,day=totalDay%DAYS_PER_YEAR+1,dayProgress=(elapsed%DAY_MS)/DAY_MS,totalMinutes=Math.floor(dayProgress*1440),hours=String(Math.floor(totalMinutes/60)).padStart(2,'0'),minutes=String(totalMinutes%60).padStart(2,'0');$('gameClock').textContent=`第${year}年第${day}天 ${hours}:${minutes}`}
  function personFloorIndex(person){const assigned=workerFloor(person.id);if(assigned)return state.floors.indexOf(assigned);const dorm=state.floors.find(floor=>floor.type==='dorm'&&floor.residents.includes(person.id));return Math.max(0,state.floors.indexOf(dorm))}
  function mealPending(id){return elevator.trip?.personId===id||elevator.queue.some(trip=>trip.personId===id)}
  function chooseMeal(person,originFloor){
    const order=person.foodPreference==='meat'?['meat','vegetables']:person.foodPreference==='vegetables'?['vegetables','meat']:(Math.random()<.5?['vegetables','meat']:['meat','vegetables']);
    for(const item of order){const type=item==='vegetables'?'garden':'farm',candidates=state.floors.map((floor,index)=>({floor,index})).filter(entry=>entry.floor.type===type&&(entry.floor.stock[item]||0)>0).sort((a,b)=>Math.abs(a.index-originFloor)-Math.abs(b.index-originFloor));if(candidates.length)return{item,foodFloor:candidates[0].index}}
    return null;
  }
  function requestMeal(person){
    const originFloor=personFloorIndex(person),choice=chooseMeal(person,originFloor);person.lastMealSlot+=1;person.satiety=Math.max(0,person.satiety-34);
    if(!choice){toast(`${person.name} 没找到可吃的餐食`);return false}
    state.floors[choice.foodFloor].stock[choice.item]-=1;syncInventory();elevator.queue.push({personId:person.id,originFloor,foodFloor:choice.foodFloor,item:choice.item,kind:'meal',direct:originFloor===choice.foodFloor});return true;
  }
  function mealTick(now){const currentSlot=mealSlotAt(now,state.createdAt);let changed=false;state.people.forEach(person=>{if(person.lastMealSlot<currentSlot&&!mealPending(person.id)){requestMeal(person);changed=true}});if(changed){save();renderInventory();renderTower()}return changed}
  function wantsMilk(person,hour){return person.milkPreference==='auto'||person.milkPreference==='both'||(person.milkPreference==='morning'&&hour===6)||(person.milkPreference==='evening'&&hour===20)}
  function requestMilk(person){const eventHour=MILK_TIMES[person.lastMilkSlot%MILK_TIMES.length],originFloor=personFloorIndex(person);person.lastMilkSlot+=1;if(!wantsMilk(person,eventHour))return false;const candidates=state.floors.map((floor,index)=>({floor,index})).filter(entry=>entry.floor.type==='farm'&&(entry.floor.stock.milk||0)>0).sort((a,b)=>Math.abs(a.index-originFloor)-Math.abs(b.index-originFloor));if(!candidates.length)return false;const foodFloor=candidates[0].index;state.floors[foodFloor].stock.milk-=1;syncInventory();elevator.queue.push({personId:person.id,originFloor,foodFloor,item:'milk',kind:'milk',direct:originFloor===foodFloor});return true}
  function milkTick(now){const currentSlot=milkSlotAt(now,state.createdAt);let changed=false;state.people.forEach(person=>{if(person.lastMilkSlot<currentSlot&&!mealPending(person.id)){requestMilk(person);changed=true}});if(changed){save();renderInventory();renderTower()}return changed}
  function moveElevator(target,duration){const car=$('elevatorCar');if(!car){elevator.floor=target;return}car.style.transitionDuration=`${duration}ms`;car.offsetHeight;car.style.setProperty('--elevator-floor',target);elevator.floor=target}
  function updateElevatorVisual(){const car=$('elevatorCar'),passenger=$('elevatorPassenger'),trip=elevator.trip;if(!car||!passenger)return;car.style.setProperty('--elevator-floor',elevator.floor);document.querySelectorAll('.meal-visitor').forEach(visitor=>visitor.remove());if(!trip){passenger.hidden=true;car.classList.remove('open');return}const person=residentById(trip.personId),riding=!trip.direct&&['boarding','toFood','toHome'].includes(trip.stage);passenger.hidden=!riding;if(person){passenger.style.backgroundPosition=spritePosition(person.sprite)}car.classList.toggle('open',!trip.direct&&(trip.stage==='boarding'||trip.stage==='eating'));if(trip.stage==='eating'&&person){const body=document.querySelectorAll('.floor')[trip.foodFloor]?.querySelector('.floor-body');if(body){const visitor=document.createElement('button');visitor.className=`person meal-visitor ${trip.direct?'direct-meal ':''}sprite-row-${Math.floor(person.sprite/4)}`;visitor.dataset.person=person.id;visitor.style.backgroundPosition=spritePosition(person.sprite);visitor.onclick=event=>{event.stopPropagation();openPerson(person.id)};body.appendChild(visitor)}}}
  function elevatorTick(now){
    if(!elevator.trip&&elevator.queue.length){const next=elevator.queue.shift(),person=residentById(next.personId);if(next.direct){elevator.trip=Object.assign(next,{stage:'eating',until:now+1800});if(person){if(next.kind==='milk')person.satisfaction=Math.min(100,person.satisfaction+1);else person.satiety=Math.min(100,person.satiety+34)}renderTower();toast(next.kind==='milk'?`${person?.name||'居民'} 在本楼层喝了牛奶，满意度＋1`:`${person?.name||'居民'} 在本楼层吃了${next.item==='vegetables'?'蔬菜':'肉'}`);save();return}const duration=350+Math.abs(elevator.floor-next.originFloor)*650;elevator.trip=Object.assign(next,{stage:'toPickup',until:now+duration});renderTower();moveElevator(next.originFloor,duration);return}
    const trip=elevator.trip;if(!trip||now<trip.until)return;const person=residentById(trip.personId);if(!person){elevator.trip=null;return renderTower()}
    if(trip.stage==='toPickup'){trip.stage='boarding';trip.until=now+650;updateElevatorVisual();return}
    if(trip.stage==='boarding'){const duration=350+Math.abs(trip.foodFloor-trip.originFloor)*650;trip.stage='toFood';trip.until=now+duration;moveElevator(trip.foodFloor,duration);updateElevatorVisual();return}
    if(trip.stage==='toFood'){trip.stage='eating';trip.until=now+1800;if(trip.kind==='milk'){person.satisfaction=Math.min(100,person.satisfaction+1);toast(`${person.name} 喝了牛奶，满意度＋1`)}else{person.satiety=Math.min(100,person.satiety+34);toast(`${person.name} 吃了${trip.item==='vegetables'?'蔬菜':'肉'}`)}save();updateElevatorVisual();return}
    if(trip.stage==='eating'){if(trip.direct){elevator.trip=null;save();renderTower();return}const duration=350+Math.abs(trip.foodFloor-trip.originFloor)*650;trip.stage='toHome';trip.until=now+duration;moveElevator(trip.originFloor,duration);updateElevatorVisual();return}
    if(trip.stage==='toHome'){elevator.trip=null;save();renderTower()}
  }

  function barberTick(){const now=Date.now();let changed=false;state.floors.filter(floor=>floor.type==='barber').forEach(floor=>{if(!floor.barberId)return;if(!floor.currentClientId){let nextId;while(floor.barberQueue.length&&!nextId){const candidate=floor.barberQueue.shift();if(candidate!==floor.barberId&&residentById(candidate))nextId=candidate}if(nextId){floor.currentClientId=nextId;floor.barberStartedAt=now;changed=true}return}if(!floor.barberStartedAt)floor.barberStartedAt=now;const elapsed=now-floor.barberStartedAt;if(elapsed>=CYCLE_MS){const client=residentById(floor.currentClientId);if(client){client.satisfaction=Math.min(100,client.satisfaction+5);toast(`${client.name} 理发完成，满意度＋5`)}floor.currentClientId=null;floor.barberStartedAt=null;changed=true;return}const index=state.floors.indexOf(floor),element=document.querySelector(`[data-production-floor="${index}"]`);if(element){element.querySelector('.production-fill').style.width=`${Math.min(100,elapsed/CYCLE_MS*100)}%`;element.querySelector('.production-time').textContent=`${Math.max(0,Math.ceil((CYCLE_MS-elapsed)/1000))}s`}});if(changed){save();render()}}
  function primaryTick(){const now=Date.now();let changed=false;state.floors.filter(floor=>floor.type==='primary').forEach(floor=>{if(!primaryReady(floor))return;if(!floor.schoolStartedAt)floor.schoolStartedAt=now;const elapsed=now-floor.schoolStartedAt;if(elapsed>=PRIMARY_MS){floor.studentIds.map(residentById).filter(Boolean).forEach(student=>{student.skills[floor.taughtSkill]=Math.min(1,(student.skills[floor.taughtSkill]||0)+1);if(SKILLS.every(skill=>(student.skills[skill]||0)>=1))student.education='小学'});floor.schoolStartedAt+=PRIMARY_MS;changed=true;return}const index=state.floors.indexOf(floor),element=document.querySelector(`[data-primary-floor="${index}"]`);if(element){element.querySelector('.production-fill').style.width=`${Math.min(100,elapsed/PRIMARY_MS*100)}%`;element.querySelector('.production-time').textContent=`${Math.max(0,Math.ceil((PRIMARY_MS-elapsed)/1000))}s`}});if(changed){save();render()}}
  function clinicForPatient(){return state.floors.find(floor=>floor.type==='clinic'&&floor.workerIds.some(id=>{const doctor=residentById(id);return doctor&&!doctor.sick&&doctor.age>16&&meetsWorkerSkill(doctor,floor)}))}
  function showNextDeathNotice(){if(!$('deathNotice').hidden)return;const person=state.people.find(resident=>resident.deathPending);if(!person)return;$('deathNoticeSprite').style.backgroundPosition=spritePosition(person.sprite);$('deathNoticeSprite').classList.toggle('no-clothes',!person.hasClothes);$('deathNoticeSprite').classList.toggle('dressed',Boolean(person.hasClothes));$('deathNoticeName').textContent=`${person.name} · ${person.age}岁`;$('deathNoticeSituation').textContent='饱腹感为 0 已持续 3 天，身体未能恢复';$('deathNoticeCause').textContent='长期饥饿';$('deathNoticeSummary').textContent=`我们遗憾地告知，${person.name} 已经去世。`;$('deathNotice').dataset.personId=person.id;$('deathNotice').hidden=false;$('backdrop').classList.add('show');closeSheets()}
  function confirmDeath(){const notice=$('deathNotice'),id=notice.dataset.personId,person=residentById(id);if(person){removePersonAssignments(id);state.floors.forEach(floor=>floor.residents=(floor.residents||[]).filter(personId=>personId!==id));state.people.forEach(resident=>{if(resident.spouseId===id)resident.spouseId=null});elevator.queue=elevator.queue.filter(trip=>trip.personId!==id);if(elevator.trip?.personId===id)elevator.trip=null;state.people=state.people.filter(resident=>resident.id!==id);save()}notice.hidden=true;delete notice.dataset.personId;$('backdrop').classList.remove('show');render();showNextDeathNotice()}
  function ageSicknessTick(){const now=Date.now(),elapsed=Math.max(0,now-state.createdAt),year=Math.floor(elapsed/(DAY_MS*DAYS_PER_YEAR)),day=Math.floor(elapsed/DAY_MS);let changed=false;if(year>state.ageYear){const years=year-state.ageYear;state.people.forEach(person=>person.age+=years);state.ageYear=year;changed=true;toast(`新的一年开始了，所有居民年龄＋${years}`)}if(day>state.lastSicknessDay){for(let current=state.lastSicknessDay+1;current<=day;current++)state.people.filter(person=>person.age>60&&!person.sick).forEach(person=>{if(Math.random()<.15){person.sick=true;person.sickCause='age';person.sickUntil=null;person.clinicFloorId=null;removePersonAssignments(person.id);toast(`${person.name} 生病了，暂时不能工作`);changed=true}});state.lastSicknessDay=day;changed=true}state.people.forEach(person=>{if(person.satiety>0){if(person.satietyZeroSince!==null){person.satietyZeroSince=null;changed=true}return}if(!Number.isFinite(person.satietyZeroSince)){person.satietyZeroSince=now;changed=true}const zeroDuration=now-person.satietyZeroSince;if(zeroDuration>=DAY_MS&&!person.deathPending&&person.sickCause!=='starvation'){person.sick=true;person.sickCause='starvation';person.sickUntil=null;person.clinicFloorId=null;removePersonAssignments(person.id);toast(`${person.name} 已经挨饿 1 天，因饥饿生病了`);changed=true}if(zeroDuration>=DAY_MS*3&&!person.deathPending){person.deathPending=true;person.sickUntil=null;person.clinicFloorId=null;removePersonAssignments(person.id);changed=true}});state.people.filter(person=>person.sick&&!person.deathPending).forEach(person=>{if(!person.clinicFloorId){const clinic=clinicForPatient();if(clinic){person.clinicFloorId=clinic.id;person.sickUntil=now+CLINIC_MS;toast(`${person.name} 已进入诊所治疗`);changed=true}}else if(person.sickUntil&&now>=person.sickUntil){const starvation=person.sickCause==='starvation';person.sick=false;person.sickCause=null;person.sickUntil=null;person.clinicFloorId=null;if(starvation){person.satiety=30;person.satietyZeroSince=null}toast(starvation?`${person.name} 已康复，饱腹感恢复到 30%`:`${person.name} 已康复`);changed=true}});if(changed){save();render()}showNextDeathNotice()}
  function productionTick(){
    const now=Date.now();renderClock(now);mealTick(now);milkTick(now);elevatorTick(now);let changed=false;state.floors.forEach(floor=>{const room=ROOMS[floor.type];if(floor.type==='clothing'){if(!floor.workerIds.length)return;if(!floor.cycleStartedAt)floor.cycleStartedAt=now;const cycles=Math.floor((now-floor.cycleStartedAt)/GARDEN_MS);if(cycles<=0)return;floor.clothingStock+=cycles*floor.workerIds.length;const sold=Math.max(0,floor.clothingStock-floor.clothingReserve);if(sold){floor.clothingStock-=sold;state.money+=sold*50}floor.cycleStartedAt+=cycles*GARDEN_MS;changed=true;return}if(floor.type==='school'){if(!schoolReady(floor))return;if(!floor.schoolStartedAt)floor.schoolStartedAt=now;const cycles=Math.floor((now-floor.schoolStartedAt)/GARDEN_MS);if(cycles<=0)return;floor.studentIds.map(residentById).filter(Boolean).forEach(student=>{student.skills[floor.taughtSkill]=Math.min(5,(student.skills[floor.taughtSkill]||0)+cycles)});floor.schoolStartedAt+=cycles*GARDEN_MS;changed=true;return}const production=room?.production,effect=room?.effect,workerCount=floor.workerIds.length;if((!production&&!effect)||!workerCount)return;const duration=effect?GARDEN_MS:CYCLE_MS;if(!floor.cycleStartedAt)floor.cycleStartedAt=now;const cycles=Math.floor((now-floor.cycleStartedAt)/duration);if(cycles<=0)return;if(production)Object.entries(production).forEach(([item,amount])=>{if(item==='label')return;const total=amount*cycles*workerCount;if(item==='money')state.money+=total;else floor.stock[item]+=total});if(effect)floor.workerIds.map(residentById).filter(Boolean).forEach(person=>{person.satisfaction=Math.min(100,person.satisfaction+effect.satisfaction*cycles)});floor.cycleStartedAt+=cycles*duration;changed=true});
    if(checkRelationships(now))changed=true;if(processBirths(now)){changed=true;checkRelationships(now)}
    if(changed){syncInventory();save();render()}
    document.querySelectorAll('[data-production-floor]').forEach(element=>{const floor=state.floors[Number(element.dataset.productionFloor)],isSchool=floor?.type==='school',active=isSchool?schoolReady(floor):floor?.workerIds.length;if(!active)return;const duration=isSchool||floor.type==='clothing'||ROOMS[floor.type].effect?GARDEN_MS:CYCLE_MS,startedAt=isSchool?floor.schoolStartedAt:floor.cycleStartedAt,elapsed=(now-startedAt)%duration;element.querySelector('.production-fill').style.width=`${Math.min(100,elapsed/duration*100)}%`;element.querySelector('.production-time').textContent=`${Math.max(0,Math.ceil((duration-elapsed)/1000))}s`});
  }

  document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>showView(button.dataset.view));$('goBuild').onclick=()=>showView('build');$('closeSheet').onclick=closeSheets;$('closeRoomSheet').onclick=closeSheets;$('backdrop').onclick=closeSheets;$('confirmDeath').onclick=confirmDeath;
  $('resetGame').onclick=()=>{if(!window.confirm('确定要重新开始游戏吗？当前大楼、人物、库存和家庭数据都会被清除。'))return;localStorage.removeItem(SAVE_KEY);state=freshGame();save();const url=new URL(location.href);url.searchParams.set('reset',Date.now());location.replace(url)};
  const acceptedKey='one-building-accepted-version',notice=$('updateNotice'),updateText=$('updateText'),updateButton=$('updateButton');let available=VERSION;
  function showUpdate(version,isRemote=false){available=version;updateText.textContent=isRemote?`发现新版本 ${version}`:`游戏更新到 ${version} 版本`;updateButton.textContent=isRemote?'立即更新':'知道了';notice.hidden=false}
  if(localStorage.getItem(acceptedKey)!==VERSION)showUpdate(VERSION);
  async function checkForUpdate(){try{const response=await fetch(`build-info.js?check=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error(response.status);const match=(await response.text()).match(/BUILD_VERSION\s*=\s*['"]([^'"]+)/);if(match&&match[1]!==VERSION)showUpdate(match[1],true)}catch(error){console.debug('检查更新失败',error)}}
  updateButton.onclick=()=>{localStorage.setItem(acceptedKey,available);if(available===VERSION){notice.hidden=true;return}const url=new URL(location.href);url.searchParams.set('version',available);location.replace(url)};checkForUpdate();setInterval(checkForUpdate,20000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkForUpdate()});
  sanitizeStudentAges();sanitizeTeacherQualifications();render();save();showNextDeathNotice();setInterval(productionTick,250);setInterval(ageSicknessTick,1000);setInterval(sanitizeStudentAges,1000);setInterval(sanitizeTeacherQualifications,1000);setInterval(primaryTick,250);setInterval(barberTick,250);
})();
