(function(){
  const VERSION=window.BUILD_VERSION||'unknown',SAVE_KEY='one-building-game-v1',CYCLE_MS=20000,GARDEN_MS=60000,PREGNANCY_MS=300000;
  const SKILLS=['食品','物流','技术','艺术','服务','科研'];
  const SURNAMES=['林','周','陈','陆','许','顾','沈','江','苏','叶','唐','程'];
  const GIVEN_NAMES={男:['川','野','星河','远','舟','安','一','辰','晨宇','泽','然','航'],女:['夏','禾','月','晴','宁','岚','秋','棠','悦','安然','星月','念']};
  const ROOMS={
    dorm:{name:'宿舍',category:'居住类',cost:600,description:'最多可供 6 名居民入住。新建宿舍为空。'},
    garden:{name:'菜园',category:'食品类',cost:400,description:'最多 2 名员工，每人每 20 秒收获 1 份蔬菜。',production:{vegetables:1,label:'🥬 蔬菜'}},
    farm:{name:'牧场',category:'食品类',cost:500,description:'最多 2 名员工，每人每 20 秒产出 1 份肉和 1 份牛奶。',production:{meat:1,milk:1,label:'🥩 肉＋🥛 奶'}},
    park:{name:'花园',category:'满意类',cost:300,capacity:4,description:'最多容纳 4 人，每分钟为其中每人增加 1 满意度。',effect:{satisfaction:1,label:'♥ 满意度 +1'}},
    market:{name:'超市',category:'经济类',cost:500,description:'最多 2 名员工，每人每 20 秒赚取 €10。',production:{money:10,label:'💶 收入 €10'}},
    school:{name:'社区学校',category:'技能类',cost:450,description:'学习基础技能的教育房间。'}
  };
  const $=id=>document.getElementById(id),random=array=>array[Math.floor(Math.random()*array.length)],euro=n=>'€'+Math.round(n).toLocaleString('en-US');

  function randomName(gender,used=[]){let name;for(let attempts=0;attempts<30;attempts++){name=random(SURNAMES)+random(GIVEN_NAMES[gender]);if(!used.includes(name))return name}return`${name}${used.length+1}`}
  function createResident(index,used,forcedTalent){const gender=Math.random()<.5?'男':'女',name=randomName(gender,used),talent=forcedTalent||random(SKILLS),matchingSprites=gender==='男'?[0,2,4,6]:[1,3,5,7];return{id:`p-${Date.now()}-${index}`,name,gender,age:20+Math.floor(Math.random()*16),talent,satisfaction:0,spouseId:null,pregnancy:null,skills:Object.fromEntries(SKILLS.map(skill=>[skill,skill===talent?5:0])),sprite:matchingSprites[index%4]}}
  function floorId(index){return`floor-${index+1}-${Date.now()}`}
  function freshGame(){const people=[],startingTalents=['物流','食品','科研',random(SKILLS)];for(let i=0;i<4;i++)people.push(createResident(i,people.map(p=>p.name),startingTalents[i]));return{money:1000,people,inventory:{vegetables:0,meat:0,milk:0},floors:[{id:floorId(0),type:'dorm',residents:people.map(p=>p.id),workerIds:[],cycleStartedAt:null}],createdAt:Date.now()}}
  function normalizeState(data){data.inventory=Object.assign({vegetables:0,meat:0,milk:0},data.inventory||{});data.people=(data.people||[]).map(person=>Object.assign({satisfaction:0,spouseId:null,pregnancy:null},person));data.floors=(data.floors||[]).map((floor,index)=>{const normalized=Object.assign({id:`floor-${index+1}-${data.createdAt||Date.now()}`,residents:[],workerIds:[],cycleStartedAt:null},floor);if(!Array.isArray(floor.workerIds))normalized.workerIds=floor.workerId?[floor.workerId]:[];delete normalized.workerId;return normalized});return data}
  function loadGame(){try{return normalizeState(JSON.parse(localStorage.getItem(SAVE_KEY))||freshGame())}catch{return freshGame()}}
  let state=loadGame(),activeRoomIndex=null,toastQueue=[],toastShowing=false;
  function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
  function residentById(id){return state.people.find(person=>person.id===id)}
  function workerFloor(id){return state.floors.find(floor=>(floor.workerIds||[]).includes(id))}
  function roomCapacity(floor){return ROOMS[floor.type].capacity||2}
  function bedCapacity(){return state.floors.filter(floor=>floor.type==='dorm').length*6}
  function activePregnancies(){return state.people.filter(person=>person.pregnancy).length}
  function spritePosition(variant){const col=variant%4,row=Math.floor(variant/4);return`${col*(100/3)}% ${row*100}%`}
  function toast(message){toastQueue.push(message);if(toastShowing)return;const showNext=()=>{const next=toastQueue.shift();if(!next){toastShowing=false;return}toastShowing=true;$('toast').textContent=next;$('toast').classList.add('show');setTimeout(()=>{$('toast').classList.remove('show');setTimeout(showNext,220)},1600)};showNext()}
  function showView(name){document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.id===`view-${name}`));document.querySelectorAll('nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===name));window.scrollTo(0,0)}

  function buildRoom(type){const room=ROOMS[type];if(!room)return;if(state.money<room.cost)return toast('资金不足');state.money-=room.cost;state.floors.push({id:floorId(state.floors.length),type,residents:[],workerIds:[],cycleStartedAt:null});save();render();showView('building');toast(`F${state.floors.length} ${room.name}建造完成`)}
  function productionMarkup(floor,index){const room=ROOMS[floor.type],production=room.production,effect=room.effect,workerCount=floor.workerIds.length;if(!production&&!effect)return`<span class="room-worker-hint">${workerCount?`${workerCount}/${roomCapacity(floor)} 人工作`:'点击选择员工'}</span>`;const duration=effect?GARDEN_MS:CYCLE_MS,progress=workerCount&&floor.cycleStartedAt?Math.min(100,(Date.now()-floor.cycleStartedAt)/duration*100):0,label=effect?`${effect.label} · ${workerCount}人`:`${production.label} ×${workerCount||0}`;return`<div class="production-ui" data-production-floor="${index}"><div class="production-label"><span>${label}</span><span class="production-time">${workerCount?Math.max(0,Math.ceil((duration-(Date.now()-floor.cycleStartedAt))/1000))+'s':'待命'}</span></div><div class="production-track"><i class="production-fill" style="width:${progress}%"></i></div></div>`}
  function personButton(person){return`<button class="person sprite-row-${Math.floor(person.sprite/4)}" data-person="${person.id}" style="background-position:${spritePosition(person.sprite)}" aria-label="查看 ${person.name}"></button>`}
  function renderTower(){
    $('tower').innerHTML=state.floors.map((floor,index)=>{const room=ROOMS[floor.type],residents=(floor.residents||[]).map(residentById).filter(Boolean),workers=(floor.workerIds||[]).map(residentById).filter(Boolean),visible=floor.type==='dorm'?residents.filter(person=>!workerFloor(person.id)):workers,role=floor.type==='park'?'休闲':'员工',status=floor.type==='dorm'?`${residents.length}/6 人`:`${role} ${workers.length}/${roomCapacity(floor)}${workers.length?' · '+workers.map(worker=>worker.name).join('、'):''}`;return`<article class="floor room-${floor.type}" ${floor.type!=='dorm'?`data-room="${index}"`:''}><div class="floor-head"><b>F${index+1} · ${room.name}</b><span>${status}</span></div><div class="floor-body">${visible.map(personButton).join('')}${floor.type!=='dorm'?productionMarkup(floor,index):''}</div></article>`}).join('');
    document.querySelectorAll('[data-person]').forEach(button=>button.onclick=event=>{event.stopPropagation();openPerson(button.dataset.person)});document.querySelectorAll('[data-room]').forEach(room=>room.onclick=()=>openRoom(Number(room.dataset.room)));
  }
  function renderCatalog(){$('roomCatalog').innerHTML=Object.entries(ROOMS).map(([type,room])=>`<article class="room-card"><div class="room-thumb room-${type}" aria-hidden="true"></div><div><h3>${room.name} · ${room.category}</h3><p>${room.description}</p></div><button type="button" data-build="${type}" ${state.money<room.cost?'disabled':''}>${euro(room.cost)}</button></article>`).join('');document.querySelectorAll('[data-build]').forEach(button=>button.onclick=()=>buildRoom(button.dataset.build))}
  function renderTasks(){const facility=state.floors.some(f=>f.type!=='dorm'),working=state.floors.some(f=>f.workerIds.length),tasks=[{name:'建造第二层',description:'让大楼拥有至少 2 层。',done:state.floors.length>=2,progress:`${Math.min(state.floors.length,2)}/2`},{name:'安排第一名员工',description:'点击非宿舍楼层选择员工。',done:working,progress:working?'1/1':'0/1'},{name:'建设第一项设施',description:'建造任意一个非宿舍房间。',done:facility,progress:facility?'1/1':'0/1'}];$('taskList').innerHTML=tasks.map(task=>`<article class="task ${task.done?'done':''}"><div class="task-mark">${task.done?'✓':'·'}</div><div><h3>${task.name}</h3><p>${task.description}</p></div><strong>${task.progress}</strong></article>`).join('')}
  function renderInventory(){$('vegetableCount').textContent=state.inventory.vegetables;$('meatCount').textContent=state.inventory.meat;$('milkCount').textContent=state.inventory.milk}
  function renderOverview(){const counts=Object.entries(ROOMS).map(([type,room])=>`${room.name} ${state.floors.filter(f=>f.type===type).length}`).join(' · '),working=state.floors.filter(f=>f.type!=='park').reduce((total,floor)=>total+floor.workerIds.length,0),couples=state.people.filter(person=>person.spouseId).length/2;$('overview').innerHTML=`<div class="overview-card"><span>当前资金</span><b>${euro(state.money)}</b></div><div class="overview-card"><span>大楼层数</span><b>${state.floors.length}</b></div><div class="overview-card"><span>居民／床位</span><b>${state.people.length}/${bedCapacity()}</b></div><div class="overview-card"><span>在职人数</span><b>${working}</b></div><div class="overview-card"><span>已婚家庭</span><b>${couples}</b></div><div class="overview-card"><span>怀孕人数</span><b>${activePregnancies()}</b></div><div class="overview-card room-summary"><span>食物库存</span><b>蔬菜 ${state.inventory.vegetables} · 肉 ${state.inventory.meat} · 牛奶 ${state.inventory.milk}</b></div><div class="overview-card room-summary"><span>房间组成</span><b>${counts}</b></div>`}
  function render(){const beds=state.floors.filter(f=>f.type==='dorm').length*6;$('headerMoney').textContent=euro(state.money);$('floorCount').textContent=state.floors.length;$('populationCount').textContent=state.people.length;$('bedCount').textContent=Math.max(0,beds-state.people.length);$('shortVersion').textContent=VERSION.replace(/^v/,'').split('+')[0];$('currentVersion').textContent=VERSION;renderInventory();renderTower();renderCatalog();renderTasks();renderOverview()}

  function openPerson(id){const person=residentById(id);if(!person)return;const job=workerFloor(id),floorIndex=job?state.floors.indexOf(job):-1,spouse=residentById(person.spouseId),place=job?(job.type==='park'?`在 F${floorIndex+1} 花园休闲`:`就职 F${floorIndex+1} ${ROOMS[job.type].name}`):'未安排';$('sheetSprite').style.backgroundPosition=spritePosition(person.sprite);$('sheetName').textContent=person.name;$('sheetMeta').textContent=`${person.gender} · ${person.age} 岁 · ${place}${spouse?` · 配偶 ${spouse.name}`:''}${person.pregnancy?` · 怀孕中（${Math.max(0,Math.ceil((person.pregnancy.dueAt-Date.now())/60000))}分钟）`:''}`;$('sheetSkills').innerHTML=`<div class="skill-row"><span>满意度</span><div class="skill-track"><i style="width:${person.satisfaction}%"></i></div><b>${person.satisfaction}</b></div>`+SKILLS.map(skill=>`<div class="skill-row"><span>${skill}</span><div class="skill-track"><i style="width:${person.skills[skill]*20}%"></i></div><b>${person.skills[skill]}</b></div>`).join('');closeSheets();$('personSheet').classList.add('show');$('backdrop').classList.add('show')}
  function openRoom(index){
    const floor=state.floors[index],room=ROOMS[floor?.type];if(!floor||floor.type==='dorm')return;const capacity=roomCapacity(floor),isGarden=floor.type==='park';activeRoomIndex=index;$('roomSheetName').textContent=`F${index+1} · ${room.name}（${floor.workerIds.length}/${capacity}）`;$('roomSheetMeta').textContent=isGarden?`${room.description} 满意度达到 100 的未婚男女可能结婚并组建家庭。`:(room.production?`${room.description} 生产只在有人工作时进行。`:`最多选择 ${capacity} 名居民在这里工作。`);
    const none=`<button class="worker-option ${!floor.workerIds.length?'selected':''}" data-worker=""><span class="room-sheet-icon" style="width:36px;height:36px;margin:0;font-size:16px">休</span><span><strong>清空员工</strong><small>取消本房间的全部安排</small></span><em>${!floor.workerIds.length?'✓':''}</em></button>`;
    $('workerOptions').innerHTML=none+state.people.map(person=>{const selected=floor.workerIds.includes(person.id),job=workerFloor(person.id),jobIndex=job?state.floors.indexOf(job):-1,status=person.age<18?'未成年，不能安排':(job?(job===floor?(isGarden?'正在花园休闲':'本房间员工'):`当前在 F${jobIndex+1} ${ROOMS[job.type].name}`):'目前未安排');return`<button class="worker-option ${selected?'selected':''}" data-worker="${person.id}" ${person.age<18?'disabled':''}><span class="worker-mini" style="background-position:${spritePosition(person.sprite)}"></span><span><strong>${person.name}</strong><small>满意 ${person.satisfaction} · ${status}</small></span><em>${selected?'取消':'选择'}</em></button>`}).join('');document.querySelectorAll('[data-worker]').forEach(button=>button.onclick=()=>assignWorker(button.dataset.worker||null));closeSheets();$('roomSheet').classList.add('show');$('backdrop').classList.add('show');
  }
  function assignWorker(workerId){
    const floor=state.floors[activeRoomIndex];if(!floor)return;if(workerId&&residentById(workerId)?.age<18)return toast('未成年居民暂时不能安排');
    if(!workerId){floor.workerIds=[];floor.cycleStartedAt=null;save();render();openRoom(activeRoomIndex);return toast('已清空员工安排')}
    const selected=floor.workerIds.includes(workerId);
    if(!selected&&floor.workerIds.length>=roomCapacity(floor))return toast(`这个房间最多容纳 ${roomCapacity(floor)} 人`);
    if(selected){floor.workerIds=floor.workerIds.filter(id=>id!==workerId)}else{state.floors.forEach(other=>{if(other===floor)return;const before=other.workerIds.length;other.workerIds=other.workerIds.filter(id=>id!==workerId);if(other.workerIds.length!==before)other.cycleStartedAt=other.workerIds.length?Date.now():null});floor.workerIds.push(workerId)}
    floor.cycleStartedAt=floor.workerIds.length?Date.now():null;checkRelationships(Date.now());save();render();openRoom(activeRoomIndex);toast(selected?`${residentById(workerId).name} 已离开${floor.type==='park'?'花园':'工作'}`:`${residentById(workerId).name} 已进入${floor.type==='park'?'花园':'工作'}`);
  }
  function closeSheets(){$('personSheet').classList.remove('show');$('roomSheet').classList.remove('show');$('backdrop').classList.remove('show')}

  function checkRelationships(now){
    let changed=false;
    state.floors.filter(floor=>floor.type==='park').forEach(garden=>{
      const visitors=garden.workerIds.map(residentById).filter(Boolean),singleMen=visitors.filter(person=>person.age>=18&&person.gender==='男'&&!person.spouseId&&person.satisfaction>=100),singleWomen=visitors.filter(person=>person.age>=18&&person.gender==='女'&&!person.spouseId&&person.satisfaction>=100);
      while(singleMen.length&&singleWomen.length){const husband=singleMen.shift(),wife=singleWomen.shift();husband.spouseId=wife.id;wife.spouseId=husband.id;changed=true;toast(`${husband.name} 和 ${wife.name} 结婚了！`)}
      visitors.filter(person=>person.gender==='女'&&person.spouseId&&!person.pregnancy&&person.satisfaction>=100).forEach(wife=>{const husband=residentById(wife.spouseId);if(!husband||husband.satisfaction<100||!garden.workerIds.includes(husband.id))return;if(state.people.length+activePregnancies()>=bedCapacity())return;wife.pregnancy={fatherId:husband.id,dueAt:now+PREGNANCY_MS};changed=true;toast(`${wife.name} 怀孕了，5 分钟后生产`)});
    });
    return changed;
  }
  function createChild(mother,father){const gender=Math.random()<.5?'男':'女',surname=father?.surname||father?.name?.slice(0,1)||random(SURNAMES),used=state.people.map(person=>person.name);let name=surname+random(GIVEN_NAMES[gender]);if(used.includes(name))name=`${surname}${random(GIVEN_NAMES[gender])}${state.people.length+1}`;const sprites=gender==='男'?[0,2,4,6]:[1,3,5,7];return{id:`p-${Date.now()}-${state.people.length}`,name,surname,gender,age:0,talent:'无',satisfaction:0,spouseId:null,pregnancy:null,parentIds:[father?.id,mother.id].filter(Boolean),skills:Object.fromEntries(SKILLS.map(skill=>[skill,0])),sprite:random(sprites)}}
  function processBirths(now){
    let changed=false;
    state.people.filter(mother=>mother.pregnancy&&mother.pregnancy.dueAt<=now).forEach(mother=>{if(state.people.length>=bedCapacity())return;const father=residentById(mother.pregnancy.fatherId),dorm=state.floors.find(floor=>floor.type==='dorm'&&(floor.residents||[]).length<6);if(!dorm)return;const child=createChild(mother,father);state.people.push(child);dorm.residents.push(child.id);mother.pregnancy=null;changed=true;toast(`${mother.name} 生下了 ${child.name}！`)});
    return changed;
  }

  function productionTick(){
    const now=Date.now();let changed=false;state.floors.forEach(floor=>{const room=ROOMS[floor.type],production=room?.production,effect=room?.effect,workerCount=floor.workerIds.length;if((!production&&!effect)||!workerCount)return;const duration=effect?GARDEN_MS:CYCLE_MS;if(!floor.cycleStartedAt)floor.cycleStartedAt=now;const cycles=Math.floor((now-floor.cycleStartedAt)/duration);if(cycles<=0)return;if(production)Object.entries(production).forEach(([item,amount])=>{if(item==='label')return;const total=amount*cycles*workerCount;if(item==='money')state.money+=total;else state.inventory[item]+=total});if(effect)floor.workerIds.map(residentById).filter(Boolean).forEach(person=>{person.satisfaction=Math.min(100,person.satisfaction+effect.satisfaction*cycles)});floor.cycleStartedAt+=cycles*duration;changed=true});
    if(checkRelationships(now))changed=true;if(processBirths(now)){changed=true;checkRelationships(now)}
    if(changed){save();render()}
    document.querySelectorAll('[data-production-floor]').forEach(element=>{const floor=state.floors[Number(element.dataset.productionFloor)];if(!floor?.workerIds.length)return;const duration=ROOMS[floor.type].effect?GARDEN_MS:CYCLE_MS,elapsed=(now-floor.cycleStartedAt)%duration;element.querySelector('.production-fill').style.width=`${Math.min(100,elapsed/duration*100)}%`;element.querySelector('.production-time').textContent=`${Math.max(0,Math.ceil((duration-elapsed)/1000))}s`});
  }

  document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>showView(button.dataset.view));$('goBuild').onclick=()=>showView('build');$('closeSheet').onclick=closeSheets;$('closeRoomSheet').onclick=closeSheets;$('backdrop').onclick=closeSheets;
  $('resetGame').onclick=()=>{if(!confirm('确定要清空当前存档并重新开始吗？'))return;state=freshGame();save();render();showView('building');toast('新游戏已开始')};
  const acceptedKey='one-building-accepted-version',notice=$('updateNotice'),updateText=$('updateText'),updateButton=$('updateButton');let available=VERSION;
  function showUpdate(version,isRemote=false){available=version;updateText.textContent=isRemote?`发现新版本 ${version}`:`游戏更新到 ${version} 版本`;updateButton.textContent=isRemote?'立即更新':'知道了';notice.hidden=false}
  if(localStorage.getItem(acceptedKey)!==VERSION)showUpdate(VERSION);
  async function checkForUpdate(){try{const response=await fetch(`build-info.js?check=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error(response.status);const match=(await response.text()).match(/BUILD_VERSION\s*=\s*['"]([^'"]+)/);if(match&&match[1]!==VERSION)showUpdate(match[1],true)}catch(error){console.debug('检查更新失败',error)}}
  updateButton.onclick=()=>{localStorage.setItem(acceptedKey,available);if(available===VERSION){notice.hidden=true;return}const url=new URL(location.href);url.searchParams.set('version',available);location.replace(url)};checkForUpdate();setInterval(checkForUpdate,20000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkForUpdate()});
  render();save();setInterval(productionTick,250);
})();
