/* Persistent pixel-room behavior and a single stateful elevator. */
state.pantry??=0;state.meat??=0;state.milk??=0;state.foodQueue??=[];state.people.forEach((p,i)=>{p.satiety??=72+i*5;p.walkX??=10+i*17;p.travel=null});
const openPersonBase=openPerson;openPerson=function(i){openPersonBase(i);$('sheetStats').insertAdjacentHTML('beforeend',`<div><span>饱腹感</span><b>${Math.round(state.people[i].satiety)}%</b></div>`)};
let trips=[],elevator={floor:0,target:0,moving:false,passengers:[],arrived:false},harvestActive=false,ranchActive=false,harvestElapsed=state.harvestElapsed||0,lastHarvestClock=performance.now();
const gardenFloor=()=>state.floors.findIndex(f=>f.type==='garden');const ranchFloor=()=>state.floors.findIndex(f=>f.type==='ranch');const statusFloor=p=>typeof p.place==='number'?p.place:0;const workerInGarden=()=>{let g=gardenFloor();return g>=0&&state.people.some(p=>p.place===g&&!p.travel)};
function foodSources(){let list=[],g=gardenFloor(),r=ranchFloor();if(g>=0&&state.pantry>0)list.push({floor:g,type:'vegetable',stock:state.pantry});if(r>=0&&state.meat>0)list.push({floor:r,type:'meat',stock:state.meat});return list}function nearestFood(p){let from=statusFloor(p);return foodSources().sort((a,b)=>Math.abs(a.floor-from)-Math.abs(b.floor-from))[0]}function consumeFood(source,count){if(source.type==='meat')state.meat-=count;else state.pantry-=count}function drinkMilk(p){if(state.milk<1)return false;state.milk--;p.morale=Math.min(100,p.morale+8);return true}
function travelMs(a,b){return 650+Math.abs(a-b)*700}function setStage(group,stage){group.forEach(i=>{let p=state.people[i];if(p?.travel)p.travel.stage=stage});decorateBehavior()}
function moveElevator(target,done){let ms=travelMs(elevator.floor,target);elevator.target=target;elevator.moving=elevator.floor!==target;elevator.arrived=false;decorateBehavior();setTimeout(()=>{elevator.floor=target;elevator.moving=false;elevator.arrived=true;decorateBehavior();setTimeout(()=>{elevator.arrived=false;decorateBehavior();done()},550)},ms)}
function queueHungry(){state.people.forEach((p,i)=>{if(p.satiety<35&&!p.travel&&!state.foodQueue.includes(i))state.foodQueue.push(i)});serveNext()}
function serveNext(){if(trips.length||!state.foodQueue.length)return;let first=state.foodQueue[0],p=state.people[first],source=p&&nearestFood(p);if(!p||!source)return;if(statusFloor(p)===source.floor)return serveLocal(first,source);let home=statusFloor(p),capacity=Math.min(3,source.stock),group=state.foodQueue.filter(i=>statusFloor(state.people[i])===home).slice(0,capacity);state.foodQueue=state.foodQueue.filter(i=>!group.includes(i));trips=group;group.forEach(i=>state.people[i].travel={stage:'walking-to-elevator',home,foodFloor:source.floor,foodType:source.type});group.forEach(i=>state.people[i].walkX=78);decorateBehavior(true);setTimeout(()=>{setStage(group,'waiting-elevator');moveElevator(home,()=>board(group,source))},1500)}
function board(group,source){setStage(group,'riding-to-food');elevator.passengers=[...group];moveElevator(source.floor,()=>arriveForFood(group,source))}function arriveForFood(group,source){elevator.passengers=[];setStage(group,'walking-to-table');setTimeout(()=>eatGroup(group,source),1300)}
function eatGroup(group,source){let available=source.type==='meat'?state.meat:state.pantry,served=group.slice(0,available);consumeFood(source,served.length);served.forEach(i=>{let p=state.people[i];p.satiety=Math.min(100,p.satiety+68);p.mealsToday=(p.mealsToday||0)+1;if(source.floor===ranchFloor())drinkMilk(p);p.travel.stage='eating'});decorateBehavior();setTimeout(()=>{setStage(group,'walking-back-to-elevator');setTimeout(()=>{setStage(group,'waiting-return-elevator');moveElevator(source.floor,()=>returnHome(group))},1200)},1600)}
function returnHome(group){let home=state.people[group[0]]?.travel?.home??0;setStage(group,'riding-home');elevator.passengers=[...group];moveElevator(home,()=>{elevator.passengers=[];group.forEach(i=>{if(state.people[i])state.people[i].travel=null});trips=[];decorateBehavior();serveNext()})}
function serveLocal(i,source){state.foodQueue=state.foodQueue.filter(x=>x!==i);trips=[i];let p=state.people[i];p.travel={stage:'walking-to-table',home:source.floor,local:true,foodFloor:source.floor,foodType:source.type};p.walkX=70;decorateBehavior(true);setTimeout(()=>{let available=source.type==='meat'?state.meat:state.pantry;if(available){consumeFood(source,1);p.satiety=Math.min(100,p.satiety+68);p.mealsToday=(p.mealsToday||0)+1;if(source.floor===ranchFloor())drinkMilk(p);p.travel.stage='eating';decorateBehavior()}setTimeout(()=>{p.travel=null;p.walkX=18+Math.random()*38;trips=[];decorateBehavior(true);serveNext()},1500)},1400)}
function productionTick(){if(window.scheduleOwnsProduction)return;let now=performance.now(),delta=now-lastHarvestClock;lastHarvestClock=now;let g=gardenFloor(),workers=state.people.filter(p=>p.place===g&&!p.travel);if(workers.length){harvestElapsed+=delta;if(harvestElapsed>=20000){harvestElapsed-=20000;state.pantry++;harvestActive=true;workers.forEach(p=>p.walkX=70);log(`菜园生产完成：蔬菜 +1，现有 ${state.pantry} 份。`);decorateBehavior(true);setTimeout(()=>{harvestActive=false;workers.forEach(p=>p.walkX=18+Math.random()*28);decorateBehavior(true)},900);serveNext()}}state.harvestElapsed=harvestElapsed;updateProductionUI(workers.length>0)}
function updateProductionUI(running){let g=gardenFloor(),garden=g>=0?document.querySelector(`.room[data-floor="${g}"]`):null;if(!garden)return;let widget=garden.querySelector('.production-widget');if(!widget){garden.insertAdjacentHTML('beforeend','<div class="production-widget"><span>下一份菜</span><div class="production-track"><i class="production-fill"></i></div><span class="production-time"></span></div>');widget=garden.querySelector('.production-widget')}let progress=Math.min(100,harvestElapsed/20000*100);widget.classList.toggle('paused',!running);widget.querySelector('.production-fill').style.width=progress+'%';widget.querySelector('.production-time').textContent=running?Math.max(0,Math.ceil((20000-harvestElapsed)/1000))+'s':'等待工人'}
function hungerStep(){if(window.scheduleOwnsMeals)return;state.people.forEach(p=>{if(!p.travel)p.satiety=Math.max(0,p.satiety-(personStatus(p)==='工作中'?2.2:1.1))});queueHungry();decorateBehavior()}
function wander(){state.people.forEach(p=>{let type=typeof p.place==='number'?state.floors[p.place]?.type:null;if(!p.travel&&personStatus(p)!=='待命'&&!['housing','garden','ranch'].includes(type))p.walkX=10+Math.random()*58});decorateBehavior(true)}
function nodeFor(i,extra=''){let el=document.createElement('div');el.className=`person-sprite ${extra}`;el.dataset.person=i;el.style.cssText=spriteStyle(spriteType(state.people[i],i));return el}
function updateStats(){ $('years').textContent=(state.months/12).toFixed(1)+'年';$('population').textContent=state.people.length;$('money').textContent=cash(state.money);$('food').textContent=Math.round(state.food);$('science').textContent=Math.floor(state.science);$('morale').textContent=Math.round(state.morale)+'%' }
const renderBase=render;let structure='';render=function(){let next=JSON.stringify([state.floors,state.people.map(p=>p.place),state.cat,state.mode,state.research]);if(next!==structure){let car=document.querySelector('.elevator-car-animated');car?.remove();renderBase();structure=next;if(car)document.querySelector('.tower')?.appendChild(car)}else updateStats();setTimeout(()=>decorateBehavior(),0)};
function decorateBehavior(walking=false){state.people.forEach((p,i)=>document.querySelectorAll(`.occupants .person-sprite[data-person="${i}"]`).forEach(el=>{el.style.setProperty('--walk-x',p.walkX+'%');if(walking)el.style.setProperty('--walk-time','3.8s');let type=typeof p.place==='number'?state.floors[p.place]?.type:null;el.classList.toggle('walking',walking&&!p.travel&&type!=='housing');let riding=p.travel?.stage?.startsWith('riding'),away=!!p.travel&&!p.travel.local&&['walking-to-table','eating','walking-back-to-elevator','waiting-return-elevator'].includes(p.travel.stage);el.style.opacity=riding||away?'0':'1'}));let g=gardenFloor(),garden=g>=0?document.querySelector(`.room[data-floor="${g}"]`):null,r=ranchFloor(),ranch=r>=0?document.querySelector(`.room[data-floor="${r}"]`):null;if(garden&&!garden.querySelector('.harvest-table'))garden.insertAdjacentHTML('beforeend','<div class="harvest-table"></div><div class="harvest-count"></div>');garden?.querySelector('.harvest-table')?.classList.toggle('working',harvestActive);if(garden?.querySelector('.harvest-count'))garden.querySelector('.harvest-count').textContent=`蔬菜 ${state.pantry} 份`;if(ranch&&!ranch.querySelector('.ranch-count'))ranch.insertAdjacentHTML('beforeend','<div class="ranch-count"></div>');if(ranch?.querySelector('.ranch-count'))ranch.querySelector('.ranch-count').textContent=`肉 ${state.meat} · 奶 ${state.milk}`;
 document.querySelectorAll('.food-wait,.traveller-in-room').forEach(x=>x.remove());if(state.foodQueue.length)document.querySelector('.tower')?.insertAdjacentHTML('beforeend',`<div class="food-wait">等饭 ${state.foodQueue.length} 人</div>`);trips.forEach((i,n)=>{let p=state.people[i],stage=p?.travel?.stage;if(!p||p.travel.local||!['walking-to-table','eating','walking-back-to-elevator','waiting-return-elevator'].includes(stage))return;let target=document.querySelector(`.room[data-floor="${p.travel.foodFloor}"]`);if(target){let el=nodeFor(i,'traveller-in-room');el.style.left=(stage==='eating'?70:62+n*7)+'%';target.appendChild(el)}});
 updateProductionUI(workerInGarden());let tower=document.querySelector('.tower'),car=tower?.querySelector('.elevator-car-animated');if(tower&&!car){car=document.createElement('div');car.className='elevator-car-animated';car.innerHTML='<div class="elevator-passengers"></div>';tower.appendChild(car)}if(car){let dest=elevator.moving?elevator.target:elevator.floor,ms=travelMs(elevator.floor,elevator.target);car.style.setProperty('--elevator-bottom',dest*131+'px');car.style.setProperty('--travel-time',ms+'ms');car.classList.toggle('moving',elevator.moving);car.classList.toggle('arrived',elevator.arrived);let box=car.querySelector('.elevator-passengers')||car.appendChild(document.createElement('div'));box.className='elevator-passengers';box.replaceChildren(...elevator.passengers.map(i=>nodeFor(i)))}}
setInterval(wander,5200);setInterval(hungerStep,2000);setInterval(productionTick,100);setInterval(()=>decorateBehavior(),500);render();decorateBehavior();let scheduleScript=document.createElement('script');scheduleScript.src=asset('schedule.js');document.body.appendChild(scheduleScript);
