(function(global){
  'use strict';
  const RULES=global.BuildingGameRules;
  if(!RULES)throw Error('game-rules.js must load before game-engine.js');
  const byId=(state,id)=>(state.people||[]).find(person=>person.id===id);
  const floorById=(state,id)=>(state.floors||[]).find(floor=>floor.id===id);
  const parentIds=person=>person?.parentIds||[person?.fatherId,person?.motherId].filter(Boolean);
  function ancestorIds(state,person,depth=4,found=new Set()){if(!person||depth<=0)return found;for(const id of parentIds(person)){if(found.has(id))continue;found.add(id);ancestorIds(state,byId(state,id),depth-1,found)}return found}
  function related(state,a,b){if(!a||!b||a.id===b.id)return true;const aa=ancestorIds(state,a),bb=ancestorIds(state,b);return aa.has(b.id)||bb.has(a.id)||[...aa].some(id=>bb.has(id))}
  function homeOwners(floor){return[floor?.ownerId,...(floor?.coOwnerIds||[])].filter(Boolean)}
  function privateHomeOf(state,a,b){return(state.floors||[]).find(floor=>RULES.ROOMS[floor.type]?.privateHome&&homeOwners(floor).includes(a?.id)&&homeOwners(floor).includes(b?.id))}
  function canMarry(state,a,b,park){return Boolean(a&&b&&park?.type==='park'&&(park.workerIds||[]).includes(a.id)&&(park.workerIds||[]).includes(b.id)&&a.gender!==b.gender&&!a.spouseId&&!b.spouseId&&!a.sick&&!b.sick&&a.age>=18&&b.age>=18&&a.satisfaction>=100&&b.satisfaction>=100&&!related(state,a,b))}
  function canConceive(state,mother,father,park){if(!mother||!father||mother.gender!=='女'||father.gender!=='男'||mother.spouseId!==father.id||father.spouseId!==mother.id||mother.pregnancy)return false;if(mother.age<20||mother.age>40||father.age<20||father.age>40||mother.satisfaction<100||father.satisfaction<100)return false;if(!park||!(park.workerIds||[]).includes(mother.id)||!(park.workerIds||[]).includes(father.id))return false;const home=privateHomeOf(state,mother,father);return Boolean(home&&(home.residents||[]).length<RULES.housingCapacity(home.type))}
  function qualifiedMaternity(state,floor){return floor?.type==='maternity'&&(floor.workerIds||[]).some(id=>RULES.canWork(byId(state,id),'maternity'))}
  function canDeliver(state,mother,now){if(!mother?.pregnancy||now<mother.pregnancy.dueAt||now>mother.pregnancy.dueAt+(state.dayMs||300000)*2)return null;const father=byId(state,mother.pregnancy.fatherId),home=privateHomeOf(state,mother,father),room=(state.floors||[]).find(floor=>qualifiedMaternity(state,floor)&&(floor.maternityFamilyIds||[]).includes(mother.id)&&(floor.maternityFamilyIds||[]).includes(father?.id));return father&&home&&(home.residents||[]).length<RULES.housingCapacity(home.type)&&room?{father,home,room}:null}
  function isAssigned(state,person){return Boolean((state.floors||[]).find(room=>(room.workerIds||[]).includes(person.id)||room.teacherId===person.id||room.mayorId===person.id))}
  function legal(state,action,now=state.now||0){const person=byId(state,action.personId),target=byId(state,action.targetId),floor=floorById(state,action.floorId);if(action.type==='assignWorker')return Boolean(person&&floor&&RULES.canWork(person,floor.type)&&(floor.workerIds||[]).length<RULES.roomCapacity(floor.type));if(action.type==='setMayor')return Boolean(person&&person.age>16&&!person.sick&&floor?.type==='cityhall');if(action.type==='marry')return canMarry(state,person,target,floor);if(action.type==='conceive')return canConceive(state,person,target,floor);if(action.type==='deliver')return Boolean(canDeliver(state,person,now));if(action.type==='buildRoom')return Number(state.money||0)>=RULES.roomCost(action.roomType)&&RULES.canAddStaffedRoom(action.roomType,state.floors,state.people,p=>isAssigned(state,p));return false}
  function removeAssignments(state,id){for(const floor of state.floors||[]){if(floor.mayorId===id)floor.mayorId=null;floor.workerIds=(floor.workerIds||[]).filter(x=>x!==id);if(floor.teacherId===id)floor.teacherId=null;floor.studentIds=(floor.studentIds||[]).filter(x=>x!==id);if(floor.barberId===id)floor.barberId=null;floor.barberQueue=(floor.barberQueue||[]).filter(x=>x!==id);if(floor.currentClientId===id)floor.currentClientId=null;floor.maternityFamilyIds=(floor.maternityFamilyIds||[]).filter(x=>x!==id)}}
  function clinicFor(state){return(state.floors||[]).find(floor=>floor.type==='clinic'&&(floor.workerIds||[]).some(id=>RULES.canWork(byId(state,id),'clinic')))}
  function advanceLife(state,now,options={}){
    const dayMs=state.dayMs||300000,daysPerYear=state.daysPerYear||12,clinicMs=state.clinicMs||60000,rand=options.rand||Math.random,events=[];
    const elapsed=Math.max(0,now-state.createdAt),year=Math.floor(elapsed/(dayMs*daysPerYear)),day=Math.floor(elapsed/dayMs);
    if(!Number.isInteger(state.ageYear))state.ageYear=year;
    if(!Number.isInteger(state.lastSicknessDay))state.lastSicknessDay=day;
    if(year>state.ageYear){const years=year-state.ageYear;for(const person of state.people||[])person.age+=years;state.ageYear=year;events.push({type:'newYear',years})}
    for(const person of state.people||[])if(person.age>=100&&!person.deathPending){person.deathPending=true;person.deathCause='年老';person.sickUntil=null;person.clinicFloorId=null;removeAssignments(state,person.id);events.push({type:'deathPending',personId:person.id,cause:'年老'})}
    if(day>state.lastSicknessDay){for(let current=state.lastSicknessDay+1;current<=day;current++)for(const person of state.people||[])if(person.age>60&&person.age<100&&!person.sick&&!person.deathPending&&rand()<.15){person.sick=true;person.sickCause='age';person.sickUntil=null;person.clinicFloorId=null;removeAssignments(state,person.id);events.push({type:'sick',personId:person.id,cause:'age'})}state.lastSicknessDay=day}
    for(const person of state.people||[]){if(person.deathPending)continue;if(person.satiety>0){person.satietyZeroSince=null;continue}if(!Number.isFinite(person.satietyZeroSince))person.satietyZeroSince=now;const zero=now-person.satietyZeroSince;if(zero>=dayMs&&person.sickCause!=='starvation'){person.sick=true;person.sickCause='starvation';person.sickUntil=null;person.clinicFloorId=null;removeAssignments(state,person.id);events.push({type:'sick',personId:person.id,cause:'starvation'})}if(zero>=dayMs*3&&!person.deathPending){person.deathPending=true;person.deathCause='饥饿';person.sickUntil=null;person.clinicFloorId=null;removeAssignments(state,person.id);events.push({type:'deathPending',personId:person.id,cause:'饥饿'})}}
    for(const person of state.people||[])if(person.sick&&!person.deathPending){if(!person.clinicFloorId){const clinic=clinicFor(state);if(clinic){person.clinicFloorId=clinic.id;person.sickUntil=now+clinicMs;events.push({type:'clinicEnter',personId:person.id,floorId:clinic.id})}}else if(person.sickUntil&&now>=person.sickUntil){const starvation=person.sickCause==='starvation';person.sick=false;person.sickCause=null;person.sickUntil=null;person.clinicFloorId=null;if(starvation){person.satiety=30;person.satietyZeroSince=null}events.push({type:'recovered',personId:person.id,starvation})}}
    return events;
  }
  function advancePregnancies(state,now){const events=[],dayMs=state.dayMs||300000;for(const mother of state.people||[]){if(!mother.pregnancy)continue;const pregnancy=mother.pregnancy,father=byId(state,pregnancy.fatherId),remaining=pregnancy.dueAt-now;if(remaining<=dayMs&&!pregnancy.deliveryWarned){pregnancy.deliveryWarned=true;events.push({type:'deliverySoon',personId:mother.id})}if(remaining>0)continue;const delivery=canDeliver(state,mother,now);if(delivery){events.push({type:'birthReady',personId:mother.id,fatherId:father.id,homeId:delivery.home.id,maternityId:delivery.room.id});continue}if(!pregnancy.laborWarned){pregnancy.laborWarned=true;events.push({type:'labor',personId:mother.id})}if(now>=pregnancy.dueAt+dayMs*2){mother.pregnancy=null;for(const floor of state.floors||[])floor.maternityFamilyIds=(floor.maternityFamilyIds||[]).filter(id=>id!==mother.id&&id!==father?.id);events.push({type:'miscarriage',personId:mother.id})}}
    return events;
  }
  function advanceTimeline(state,now,options={}){state.dayMs=state.dayMs||300000;state.daysPerYear=state.daysPerYear||12;state.clinicMs=state.clinicMs||60000;return[...advanceLife(state,now,options),...advancePregnancies(state,now)]}
  function cloneState(state){return typeof structuredClone==='function'?structuredClone(state):JSON.parse(JSON.stringify(state))}
  function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])]));return value}
  function stateHash(state){const text=JSON.stringify(stable(state));let hash=2166136261;for(let index=0;index<text.length;index++){hash^=text.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16).padStart(8,'0')}
  global.BuildingGameEngine={byId,floorById,parentIds,ancestorIds,related,homeOwners,privateHomeOf,canMarry,canConceive,qualifiedMaternity,canDeliver,isAssigned,legal,removeAssignments,clinicFor,advanceLife,advancePregnancies,advanceTimeline,cloneState,stateHash};
})(globalThis);
