const VERSION=window.BUILD_VERSION||'v0.3.0-local';
const asset=file=>`${file}?v=${encodeURIComponent(VERSION)}`;
['room-backgrounds.css','motion.css','simple-theme.css','production-ui.css','label-fix.css','update.css'].forEach(file=>document.head.insertAdjacentHTML('beforeend',`<link rel="stylesheet" href="${asset(file)}">`));
function loadRuntime(){let script=document.createElement('script');script.src=asset('behavior.js');document.body.appendChild(script);let update=document.createElement('script');update.src=asset('update.js');document.body.appendChild(update)}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',loadRuntime);else loadRuntime();
const ROOMS={housing:{name:'住宿层',icon:'▣',cat:'生活',cost:3000,unlock:0,skills:[],effect:'容纳 6 人'},garden:{name:'室内菜园',icon:'🌿',cat:'食物',cost:2400,unlock:0,skills:[],effect:'每人每月 +20 食物'},ranch:{name:'室内牧场',icon:'♞',cat:'食物',cost:3600,unlock:0,skills:['农业'],effect:'每人每月 +28 食物'},market:{name:'超市',icon:'▤',cat:'服务',cost:5000,unlock:500,skills:['物流','食品'],effect:'提升满意度'},hospital:{name:'医院',icon:'✚',cat:'服务',cost:12000,unlock:1500,skills:['医疗'],science:12,effect:'治疗并允许生育'},garment:{name:'服装工坊',icon:'♢',cat:'经济',cost:5500,unlock:700,skills:['设计'],effect:'每人每月 +¥900'},restaurant:{name:'饭店',icon:'♨',cat:'经济',cost:6800,unlock:600,skills:['食品'],effect:'每人每月 +¥1,000'},school:{name:'社区学校',icon:'▧',cat:'教育',cost:4500,unlock:300,skills:['教育'],effect:'培养基础技能'},lab:{name:'科研室',icon:'⌬',cat:'科研',cost:9000,unlock:1000,skills:['科研'],effect:'每人每月 +2 科研'}};
const NAMES={女:['林夏','周岚','叶青','沈禾','苏木','乔安','白露','江月','顾宁','唐梨','许棠','温晴'],男:['程野','许星','顾川','陆遥','陈屿','江辰','闻舟','贺川','季安','秦越','方野','沈砚']};
function randomName(gender,used=[]){let pool=NAMES[gender].filter(n=>!used.includes(n));return pool[Math.floor(Math.random()*pool.length)]||`${gender==='女'?'小夏':'小川'}${Date.now()%1000}`}
function newResident(gender,skill,degree,age=20,used=[]){return{name:randomName(gender,used),gender,age,skill,degree,health:100,morale:100,place:0,variant:Math.floor(Math.random()*2)}}
const fresh=()=>{let people=[];[['女','食品','社区学校'],['男','物流','社区学校'],['女','教育','大学'],['男','科研','研究院']].forEach(x=>people.push(newResident(x[0],x[1],x[2],20,people.map(p=>p.name))));return{months:0,totalDays:0,money:8000,food:120,science:0,morale:100,speed:1,mode:'player',cat:'全部',people,floors:[{type:'housing',level:1},{type:'garden',level:1},{type:'ranch',level:1}],unlocked:['housing','garden','ranch'],research:[],logs:[`${people.map(p=>p.name).join('、')}抵达大楼，开始第 1 代生活。`,'提示：拖动小人到房间安排工作，拖到电梯则待命。']}};
let state=(()=>{try{return JSON.parse(localStorage.getItem('one-building-save-v3'))}catch{return null}})()||fresh(),timer;const $=x=>document.getElementById(x),cash=n=>'¥'+Math.round(n).toLocaleString('zh-CN');
function spriteType(p,i=0){if(p.age<16)return p.gender==='女'?4:5;if(p.age>=60)return p.gender==='女'?6:7;if(p.gender==='女')return (p.variant??i%2)?2:0;return (p.variant??i%2)?3:1}
function spriteStyle(type){let positions=[0,14.65,28.57,43.25,57.14,71.43,85.71,100];return `--sprite-pos:${positions[type]}% 0;transition-timing-function:steps(24,end)`}
function personStatus(p){if(p.place==='elevator')return'待命';return state.floors[p.place]?.type==='housing'?'休息中':'工作中'}
function load(){try{return JSON.parse(localStorage.getItem('one-building-save-v2'))}catch{return null}}function toast(x){$('toast').textContent=x;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1600)}function log(x){state.logs.unshift(x);state.logs=state.logs.slice(0,40)}function peopleAt(i){return state.people.filter(p=>p.place===i)}function skills(s){return state.people.filter(p=>p.skill===s).length}function canUnlock(k){let r=ROOMS[k];return state.money>=r.unlock&&(r.science||0)<=state.science&&r.skills.every(s=>skills(s))}
function roomAction(k){let r=ROOMS[k];if(!state.unlocked.includes(k)){if(!canUnlock(k))return toast('尚未满足解锁条件');state.money-=r.unlock;state.unlocked.push(k);log(`解锁了${r.name}`)}else{if(state.money<r.cost)return toast('资金不足');state.money-=r.cost;state.floors.push({type:k,level:1});log(`第 ${state.floors.length} 层建成：${r.name}`);showView('building')}render()}
function assign(i,floor){let p=state.people[i];p.place=floor;log(floor==='elevator'?`${p.name}进入电梯待命`:`${p.name}被安排到 F${floor+1} ${ROOMS[state.floors[floor].type].name}`);render()}
function tick(){state.months++;let work=t=>state.floors.reduce((n,f,i)=>n+(f.type===t?peopleAt(i).length:0),0);state.food+=work('garden')*20+work('ranch')*28-state.people.length*5.5;state.money+=work('garment')*900+work('restaurant')*1000-state.floors.length*80;state.science+=work('lab')*2;state.people.forEach(p=>{p.age+=1/12;if(state.food<0){p.health-=6;p.morale-=5}else p.morale=Math.min(100,p.morale+.2)});state.people=state.people.filter(p=>p.age<100&&p.health>0);state.morale=state.people.reduce((a,p)=>a+p.morale,0)/(state.people.length||1);if(state.mode==='ai'){let g=state.floors.findIndex(f=>f.type==='garden'),i=state.people.findIndex(p=>p.place==='elevator');if(state.food<state.people.length*20&&g>=0&&i>=0)assign(i,g)}render()}
function sprite(i,extra=''){let t=spriteType(state.people[i],i);return `<div class="person-sprite ${extra}" style="${spriteStyle(t)}" data-person="${i}" role="button"></div>`}
function render(){
 $('version').textContent=VERSION;$('years').textContent=(state.months/12).toFixed(1)+'年';$('population').textContent=state.people.length;$('money').textContent=cash(state.money);$('food').textContent=Math.round(state.food);$('science').textContent=Math.floor(state.science);$('morale').textContent=Math.round(state.morale)+'%';$('speedButton').textContent='×'+state.speed;
 $('tower').innerHTML=state.floors.map((f,i)=>`<div class="floor ${f.type}"><div class="room drop-zone" data-floor="${i}"><div class="room-label">F${i+1} · <b>${ROOMS[f.type].name}</b> · ${peopleAt(i).length}人</div><div class="occupants">${peopleAt(i).map(p=>sprite(state.people.indexOf(p))).join('')}</div></div><div class="elevator drop-zone" data-floor="elevator">${i===0?peopleAt('elevator').map(p=>sprite(state.people.indexOf(p))).join(''):''}</div></div>`).join('');
 let cats=['全部',...new Set(Object.values(ROOMS).map(r=>r.cat))];$('categoryTabs').innerHTML=cats.map(c=>`<button class="${state.cat===c?'active':''}" data-cat="${c}">${c}</button>`).join('');$('roomCatalog').innerHTML=Object.entries(ROOMS).filter(([,r])=>state.cat==='全部'||r.cat===state.cat).map(([k,r])=>{let u=state.unlocked.includes(k);return `<div class="room-card ${u?'':'locked'}" data-room="${k}"><div class="room-icon">${r.icon}</div><div><b>${r.name}${u?'':' · 未解锁'}</b><small>${u?r.effect:`解锁：${cash(r.unlock)} · ${r.skills.join('+')||'无技能门槛'} · ${r.science||0}科研`}</small></div><strong>${cash(u?r.cost:r.unlock)}</strong></div>`}).join('');
 $('peopleList').innerHTML=state.people.map((p,i)=>`<div class="person-card" data-card="${i}">${sprite(i,'card-sprite')}<div><b>${p.name} · ${p.skill}</b><small>${p.degree} · ${p.place==='elevator'?'电梯待命':`F${p.place+1} ${ROOMS[state.floors[p.place]?.type]?.name||'未安排'}`}</small><div class="health"><i style="width:${p.health}%"></i></div></div><span class="age">${Math.floor(p.age)}岁</span></div>`).join('');
 let rs=[['agri','立体农业','菜园产量提升',10],['medicine','预防医学','降低居民生病率',20],['automation','楼宇自动化','减少岗位需求',35]];$('researchTree').innerHTML=rs.map(r=>`<div class="research-node ${state.research.includes(r[0])?'done':''}"><b>${state.research.includes(r[0])?'✓ ':''}${r[1]}</b><small>${r[2]} · 需要 ${r[3]} 科研点</small><button data-research="${r[0]}" data-cost="${r[3]}">${state.research.includes(r[0])?'已完成':'开始研究'}</button></div>`).join('');$('eventLog').innerHTML=state.logs.map((x,i)=>`<p><em>${i?'记录':'现在'}</em>　${x}</p>`).join('');$('modeButton').classList.toggle('active',state.mode==='ai');$('modeButton').textContent=state.mode==='ai'?'AI 正在自动经营':'切换 AI 自动经营';bind()}
function bind(){document.querySelectorAll('[data-room]').forEach(x=>x.onclick=()=>roomAction(x.dataset.room));document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>{state.cat=x.dataset.cat;render()});document.querySelectorAll('[data-research]').forEach(x=>x.onclick=()=>{let c=+x.dataset.cost;if(state.research.includes(x.dataset.research))return;if(state.science<c)return toast('科研点不足');state.science-=c;state.research.push(x.dataset.research);render()});document.querySelectorAll('.person-sprite').forEach(x=>{x.onclick=()=>{if(!drag.moved)openPerson(+x.dataset.person)};x.onpointerdown=e=>startDrag(e,+x.dataset.person)});document.querySelectorAll('[data-card]').forEach(x=>x.onclick=()=>openPerson(+x.dataset.card))}
const drag={i:null,ghost:null,moved:false,x:0,y:0};function startDrag(e,i){drag.i=i;drag.moved=false;drag.x=e.clientX;drag.y=e.clientY;e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.onpointermove=moveDrag;e.currentTarget.onpointerup=endDrag}function moveDrag(e){if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<8)return;if(!drag.ghost){drag.moved=true;drag.ghost=document.createElement('div');drag.ghost.className='person-sprite drag-ghost';drag.ghost.style.cssText=spriteStyle(spriteType(state.people[drag.i],drag.i));document.body.appendChild(drag.ghost);document.querySelectorAll('.drop-zone').forEach(x=>x.classList.add('drop-active'))}drag.ghost.style.left=e.clientX-22+'px';drag.ghost.style.top=e.clientY-60+'px'}function endDrag(e){if(drag.ghost){drag.ghost.remove();document.querySelectorAll('.drop-zone').forEach(x=>x.classList.remove('drop-active'));let el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.drop-zone');if(el)assign(drag.i,el.dataset.floor==='elevator'?'elevator':+el.dataset.floor)}setTimeout(()=>Object.assign(drag,{i:null,ghost:null,moved:false}),0)}
function openPerson(i){let p=state.people[i],avatar=$('sheetAvatar');avatar.className='sheet-avatar person-sprite';avatar.style.cssText=spriteStyle(spriteType(p,i));$('sheetName').textContent=p.name;$('sheetRole').textContent=p.skill+' · '+p.degree;$('sheetStats').innerHTML=`<div><span>年龄</span><b>${Math.floor(p.age)} 岁</b></div><div><span>健康</span><b>${Math.round(p.health)}%</b></div><div><span>满意度</span><b>${Math.round(p.morale)}%</b></div><div><span>性别</span><b>${p.gender}</b></div><div><span>状态</span><b>${personStatus(p)}</b></div><div><span>位置</span><b>${p.place==='elevator'?'电梯':`F${p.place+1}`}</b></div>`;$('personSheet').classList.add('show');$('backdrop').classList.add('show')}function closeSheet(){$('personSheet').classList.remove('show');$('backdrop').classList.remove('show')}function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));scrollTo(0,0)}
document.querySelectorAll('nav button').forEach(x=>x.onclick=()=>showView(x.dataset.view));$('speedButton').onclick=()=>{state.speed=state.speed===1?2:state.speed===2?4:1;start();render()};$('modeButton').onclick=()=>{state.mode=state.mode==='ai'?'player':'ai';render()};$('saveButton').onclick=()=>{localStorage.setItem('one-building-save-v3',JSON.stringify(state));toast('已保存到本机')};document.querySelector('.sheet-close').onclick=closeSheet;$('backdrop').onclick=closeSheet;function start(){clearInterval(timer);timer=null}render();start();
