(function(global){
  'use strict';
  const RULES=global.BuildingGameRules;
  if(!RULES)throw Error('game-rules.js must load before game-engine.js');
  const byId=(state,id)=>(state.people||[]).find(person=>person.id===id);
  const floorById=(state,id)=>(state.floors||[]).find(floor=>floor.id===id);
  const parentIds=person=>person?.parentIds||[person?.fatherId,person?.motherId].filter(Boolean);
  function ancestorIds(state,person,depth=4,found=new Set()){if(!person||depth<=0)return found;for(const id of parentIds(person)){if(found.has(id))continue;found.add(id);ancestorIds(state,byId(state,id),depth-1,found)}return found}
  function related(state,a,b){if(!a||!b||a.id===b.id)return true;const aa=ancestorIds(state,a),bb=ancestorIds(state,b);return aa.has(b.id)||bb.has(a.id)||[...aa].some(id=>bb.has(id))}
  function homeOwners(floor){return[floor?.ownerId,...(floor?.coOwnerIds||[])].filter(Boolean)}
  function privateHomeOf(state,a,b){return(state.floors||[]).find(floor=>RULES.ROOMS[floor.type]?.privateHome&&homeOwners(floor).includes(a?.id)&&homeOwners(floor).includes(b?.id))}
  function canMarry(state,a,b,park){return Boolean(a&&b&&park?.type==='park'&&(park.workerIds||[]).includes(a.id)&&(park.workerIds||[]).includes(b.id)&&a.gender!==b.gender&&!a.spouseId&&!b.spouseId&&!a.sick&&!b.sick&&a.age>=18&&b.age>=18&&a.satisfaction>=100&&b.satisfaction>=100&&!related(state,a,b))}
  function canConceive(state,mother,father,park){if(!mother||!father||mother.gender!=='女'||father.gender!=='男'||mother.spouseId!==father.id||father.spouseId!==mother.id||mother.pregnancy)return false;if(mother.age<20||mother.age>40||father.age<20||father.age>40||mother.satisfaction<100||father.satisfaction<100)return false;if(!park||!(park.workerIds||[]).includes(mother.id)||!(park.workerIds||[]).includes(father.id))return false;const home=privateHomeOf(state,mother,father);return Boolean(home&&(home.residents||[]).length<RULES.housingCapacity(home.type))}
  function qualifiedMaternity(state,floor){return floor?.type==='maternity'&&(floor.workerIds||[]).some(id=>RULES.canWork(byId(state,id),'maternity'))}
  function canDeliver(state,mother,now){if(!mother?.pregnancy||now<mother.pregnancy.dueAt||now>mother.pregnancy.dueAt+(state.dayMs||300000)*2)return null;const father=byId(state,mother.pregnancy.fatherId),home=privateHomeOf(state,mother,father),room=(state.floors||[]).find(floor=>qualifiedMaternity(state,floor)&&(floor.maternityFamilyIds||[]).includes(mother.id)&&(floor.maternityFamilyIds||[]).includes(father?.id));return father&&home&&(home.residents||[]).length<RULES.housingCapacity(home.type)&&room?{father,home,room}:null}
  function isAssigned(state,person){return Boolean((state.floors||[]).find(room=>(room.workerIds||[]).includes(person.id)||room.teacherId===person.id||room.mayorId===person.id))}
  function legal(state,action,now=state.now||0){const person=byId(state,action.personId),target=byId(state,action.targetId),floor=floorById(state,action.floorId);if(action.type==='assignWorker')return Boolean(person&&floor&&RULES.canWork(person,floor.type)&&(floor.workerIds||[]).length<RULES.roomCapacity(floor.type));if(action.type==='setMayor')return Boolean(person&&person.age>16&&!person.sick&&floor?.type==='cityhall');if(action.type==='marry')return canMarry(state,person,target,floor);if(action.type==='conceive')return canConceive(state,person,target,floor);if(action.type==='deliver')return Boolean(canDeliver(state,person,now));if(action.type==='buildRoom')return Number(state.money||0)>=RULES.roomCost(action.roomType)&&RULES.canAddStaffedRoom(action.roomType,state.floors,state.people,p=>isAssigned(state,p));return false}
  function removeAssignments(state,id){for(const floor of state.floors||[]){if(floor.mayorId===id)floor.mayorId=null;floor.workerIds=(floor.workerIds||[]).filter(x=>x!==id);if(floor.teacherId===id)floor.teacherId=null;floor.studentIds=(floor.studentIds||[]).filter(x=>x!==id);if(floor.barberId===id)floor.barberId=null;floor.barberQueue=(floor.barberQueue||[]).filter(x=>x!==id);if(floor.currentClientId===id)floor.currentClientId=null;floor.maternityFamilyIds=(floor.maternityFamilyIds||[]).filter(x=>x!==id)}}
  function clinicFor(state){return(state.floors||[]).find(floor=>floor.type==='clinic'&&(floor.workerIds||[]).some(id=>RULES.canWork(byId(state,id),'clinic')))}
  function advanceLife(state,now,options={}){
    const dayMs=state.dayMs||300000,daysPerYear=state.daysPerYear||12,clinicMs=state.clinicMs||60000,rand=options.rand||Math.random,events=[];
    const elapsed=Math.max(0,now-state.createdAt),year=Math.floor(elapsed/(dayMs*daysPerYear)),day=Math.floor(elapsed/dayMs);
    if(!Number.isInteger(state.ageYear))state.ageYear=year;
    if(!Number.isInteger(state.lastSicknessDay))state.lastSicknessDay=day;
    if(year>state.ageYear){const years=year-state.ageYear;for(const person of state.people||[])person.age+=years;state.ageYear=year;events.push({type:'newYear',years})}
    for(const person of state.people||[])if(person.age>=100&&!person.deathPending){person.deathPending=true;person.deathCause='年老';person.sickUntil=null;person.clinicFloorId=null;removeAssignments(state,person.id);events.push({type:'deathPending',personId:person.id,cause:'年老'})}
    if(day>state.lastSicknessDay){for(let current=state.lastSicknessDay+1;current<=day;current++)for(const person of state.people||[])if(person.age>60&&person.age<100&&!person.sick&&!person.deathPending&&rand()<.15){person.sick=true;person.sickCause='age';person.sickUntil=null;person.clinicFloorId=null;removeAssignments(state,person.id);events.push({type:'sick',personId:person.id,cause:'age'})}state.lastSicknessDay=day}
    for(const person of state.people||[]){if(person.deathPending)continue;if(person.satiety>0){person.satietyZeroSince=null;continue}if(!Number.isFinite(person.satietyZeroSince))person.satietyZeroSince=now;const zero=now-person.satietyZeroSince;if(zero>=dayMs&&person.sickCause!=='starvation'){person.sick=true;person.sickCause='starvation';person.sickUntil=null;person.clinicFloorId=null;removeAssignments(state,person.id);events.push({type:'sick',personId:person.id,cause:'starvation'})}if(zero>=dayMs*3&&!person.deathPending){person.deathPending=true;person.deathCause='饥饿';person.sickUntil=null;person.clinicFloorId=null;removeAssignments(state,person.id);events.push({type:'deathPending',personId:person.id,cause:'饥饿'})}}
    for(const person of state.people||[])if(person.sick&&!person.deathPending){if(!person.clinicFloorId){const clinic=clinicFor(state);if(clinic){person.clinicFloorId=clinic.id;person.sickUntil=now+clinicMs;events.push({type:'clinicEnter',personId:person.id,floorId:clinic.id})}}else if(person.sickUntil&&now>=person.sickUntil){const starvation=person.sickCause==='starvation';person.sick=false;person.sickCause=null;person.sickUntil=null;person.clinicFloorId=null;if(starvation){person.satiety=30;person.satietyZeroSince=null}events.push({type:'recovered',personId:person.id,starvation})}}
    return events;
  }
  function advancePregnancies(state,now){const events=[],dayMs=state.dayMs||300000;for(const mother of state.people||[]){if(!mother.pregnancy)continue;const pregnancy=mother.pregnancy,father=byId(state,pregnancy.fatherId),remaining=pregnancy.dueAt-now;if(remaining<=dayMs&&!pregnancy.deliveryWarned){pregnancy.deliveryWarned=true;events.push({type:'deliverySoon',personId:mother.id})}if(remaining>0)continue;const delivery=canDeliver(state,mother,now);if(delivery){events.push({type:'birthReady',personId:mother.id,fatherId:father.id,homeId:delivery.home.id,maternityId:delivery.room.id});continue}if(!pregnancy.laborWarned){pregnancy.laborWarned=true;events.push({type:'labor',personId:mother.id})}if(now>=pregnancy.dueAt+dayMs*2){mother.pregnancy=null;for(const floor of state.floors||[])floor.maternityFamilyIds=(floor.maternityFamilyIds||[]).filter(id=>id!==mother.id&&id!==father?.id);events.push({type:'miscarriage',personId:mother.id})}}
    return events;
  }
  const money=value=>Math.round(Number(value||0)*1000)/1000;
  function paymentMembers(state,person){if(!person)return[];let members=[];if(person.age<18){members=parentIds(person).map(id=>byId(state,id)).filter(Boolean);if(members.length)members=[...members,...members.map(parent=>byId(state,parent.spouseId)).filter(Boolean)]}if(!members.length)members=[person,byId(state,person.spouseId)].filter(Boolean);return[...new Map(members.map(member=>[member.id,member])).values()]}
  function spendableMoney(state,person){return money(paymentMembers(state,person).reduce((sum,member)=>sum+Number(member.money||0),0))}
  function charge(state,person,amount){amount=money(amount);if(amount<0||spendableMoney(state,person)<amount)return false;let remaining=amount;for(const member of paymentMembers(state,person)){const deduction=Math.min(Number(member.money||0),remaining);member.money=money(Number(member.money||0)-deduction);remaining=money(remaining-deduction);if(remaining<=0)break}return true}
  function splitIncome(state,floor,amount){amount=money(amount);const workers=(floor?.workerIds||[]).map(id=>byId(state,id)).filter(Boolean),staff=amount/2;if(workers.length){const share=staff/workers.length;workers.forEach(worker=>worker.money=money(Number(worker.money||0)+share))}state.money=money(Number(state.money||0)+amount/2)}
  function payWorkers(state,floor,amount){const workers=(floor?.workerIds||[]).map(id=>byId(state,id)).filter(Boolean);if(!workers.length)return false;const share=amount/workers.length;workers.forEach(worker=>worker.money=money(Number(worker.money||0)+share));return true}
  function ensureFoodReserves(floor){floor.stock=floor.stock||{};for(const [key,value] of Object.entries({gardenDirectReserve:3,gardenMarketReserve:3,gardenMarketStock:0,farmDirectReserve:3,farmMarketReserve:3,farmMarketStock:0,farmMilkReserve:3,marketVegetableReserve:3,marketMeatReserve:3,marketVegetableInputs:0,marketMeatInputs:0}))if(!Number.isFinite(floor[key]))floor[key]=value}
  function trimFoodSurplus(state,floor,directKey,marketKey,directReserve,marketReserve,price){ensureFoodReserves(floor);const directExcess=Math.max(0,Number(floor.stock[directKey]||0)-floor[directReserve]),marketNeeded=Math.max(0,floor[marketReserve]-floor[marketKey]),toMarket=Math.min(directExcess,marketNeeded);floor.stock[directKey]-=toMarket;floor[marketKey]+=toMarket;const directSale=Math.max(0,floor.stock[directKey]-floor[directReserve]),marketSale=Math.max(0,floor[marketKey]-floor[marketReserve]),sold=directSale+marketSale;if(sold){floor.stock[directKey]-=directSale;floor[marketKey]-=marketSale;splitIncome(state,floor,sold*price)}return sold}
  function allocateGarden(state,floor,total){ensureFoodReserves(floor);const direct=Math.min(total,Math.max(0,floor.gardenDirectReserve-Number(floor.stock.vegetables||0)));floor.stock.vegetables=Number(floor.stock.vegetables||0)+direct;total-=direct;const market=Math.min(total,Math.max(0,floor.gardenMarketReserve-floor.gardenMarketStock));floor.gardenMarketStock+=market;total-=market;if(total>0)splitIncome(state,floor,total*RULES.ECONOMY.vegetablePrice)}
  function takeMarketInputs(state,market,kind,needed){const meat=kind==='meat',inputKey=meat?'marketMeatInputs':'marketVegetableInputs',marketKey=meat?'farmMarketStock':'gardenMarketStock',sourceType=meat?'farm':'garden',queueKey=meat?'cannedMeatSources':'cannedVegetableSources';market[queueKey]=Array.isArray(market[queueKey])?market[queueKey]:Array(Number(market[inputKey]||0)).fill(null);let taken=0;for(const source of (state.floors||[]).filter(floor=>floor.type===sourceType&&Number(floor[marketKey]||0)>0)){const amount=Math.min(needed-taken,source[marketKey]);source[marketKey]-=amount;market[inputKey]=Number(market[inputKey]||0)+amount;for(let index=0;index<amount;index++)market[queueKey].push(source.id);taken+=amount;if(taken>=needed)break}return taken}
  function sellCannedSurplus(state,market,item,count){const meat=item==='cannedMeat',price=meat?RULES.ECONOMY.cannedMeatPrice:RULES.ECONOMY.cannedVegetablePrice,rate=meat?.05:.2,queue=meat?market.cannedMeatSources:market.cannedVegetableSources;for(let index=0;index<count;index++){const source=floorById(state,Array.isArray(queue)&&queue.length?queue.shift():null),afterTax=price*.5,upstream=afterTax*rate,paid=source?payWorkers(state,source,upstream):false;state.money=money(Number(state.money||0)+price*.5);payWorkers(state,market,afterTax-(paid?upstream:0))}}
  function rebalanceFloor(state,floor){ensureFoodReserves(floor);let sold=0;if(floor.type==='garden')sold+=trimFoodSurplus(state,floor,'vegetables','gardenMarketStock','gardenDirectReserve','gardenMarketReserve',RULES.ECONOMY.vegetablePrice);if(floor.type==='farm'){sold+=trimFoodSurplus(state,floor,'meat','farmMarketStock','farmDirectReserve','farmMarketReserve',RULES.ECONOMY.meatPrice);const milk=Math.max(0,Number(floor.stock.milk||0)-floor.farmMilkReserve);if(milk){floor.stock.milk-=milk;splitIncome(state,floor,milk*RULES.ECONOMY.milkPrice);sold+=milk}}if(floor.type==='market'){const vegetables=Math.max(0,Number(floor.stock.cannedVegetables||0)-floor.marketVegetableReserve),meat=Math.max(0,Number(floor.stock.cannedMeat||0)-floor.marketMeatReserve);if(vegetables){floor.stock.cannedVegetables-=vegetables;sellCannedSurplus(state,floor,'cannedVegetables',vegetables)}if(meat){floor.stock.cannedMeat-=meat;sellCannedSurplus(state,floor,'cannedMeat',meat)}sold+=vegetables+meat}return sold}
  function advanceProduction(state,now,config={}){
    const durations={cityhall:30000,garden:15000,market:20000,clothing:60000,bookstore:state.dayMs||300000,school:60000,farm:20000,park:60000,...config.durations},events=[];
    for(const floor of state.floors||[]){ensureFoodReserves(floor);floor.stock=floor.stock||{};const workers=(floor.workerIds||[]).length;
      if(floor.type==='cityhall'){if(!floor.cycleStartedAt)floor.cycleStartedAt=now;const cycles=Math.floor((now-floor.cycleStartedAt)/durations.cityhall);if(cycles>0){const mayor=byId(state,floor.mayorId),average=(state.people||[]).length?(state.people||[]).reduce((sum,p)=>sum+Math.max(0,p.satisfaction||0),0)/state.people.length:0,income=RULES.cityHallIncome(state.people.length,average,Boolean(mayor),1),mayorIncome=Math.min(100,income.mayor);state.money=money(Number(state.money||0)+(income.total-mayorIncome)*cycles);if(mayor)mayor.money=money(Number(mayor.money||0)+mayorIncome*cycles);floor.cycleStartedAt+=cycles*durations.cityhall;events.push({type:'produced',floorId:floor.id,cycles});}continue}
      if(floor.type==='school'){const teacher=byId(state,floor.teacherId),skill=floor.taughtSkill,education=['无','小学','中学','社区学校','大学','硕士','博士'].indexOf(teacher?.education||'无'),ready=teacher&&!teacher.sick&&education>=3&&Number(teacher.skills?.[skill]||0)>=10&&(floor.studentIds||[]).length;if(!ready)continue;if(!floor.schoolStartedAt)floor.schoolStartedAt=now;const cycles=Math.floor((now-floor.schoolStartedAt)/durations.school);if(cycles<=0)continue;(floor.studentIds||[]).map(id=>byId(state,id)).filter(Boolean).forEach(student=>student.skills[skill]=Math.min(10,Number(student.skills?.[skill]||0)+cycles));floor.schoolStartedAt+=cycles*durations.school;events.push({type:'produced',floorId:floor.id,cycles});continue}
      if(!workers)continue;if(!floor.cycleStartedAt)floor.cycleStartedAt=now;const duration=durations[floor.type];if(!duration)continue;const cycles=Math.floor((now-floor.cycleStartedAt)/duration);if(cycles<=0)continue;
      if(floor.type==='garden')allocateGarden(state,floor,cycles*workers);
      else if(floor.type==='farm'){floor.stock.meat=Number(floor.stock.meat||0)+cycles*workers;floor.stock.milk=Number(floor.stock.milk||0)+cycles*workers}
      else if(floor.type==='market'){const meat=floor.marketProduct==='cannedMeat',input=meat?'marketMeatInputs':'marketVegetableInputs',product=meat?'cannedMeat':'cannedVegetables',capacity=cycles*workers;takeMarketInputs(state,floor,meat?'meat':'vegetables',Math.max(0,capacity-Number(floor[input]||0)));const made=Math.min(capacity,Number(floor[input]||0));floor[input]-=made;floor.stock[product]=Number(floor.stock[product]||0)+made}
      else if(floor.type==='clothing'){floor.clothingStock=Number(floor.clothingStock||0)+cycles*workers;const sold=Math.max(0,floor.clothingStock-Number(floor.clothingReserve||0));if(sold){floor.clothingStock-=sold;splitIncome(state,floor,sold*RULES.ECONOMY.clothingPrice)}}
      else if(floor.type==='bookstore'){floor.bookStock=Number(floor.bookStock||0)+cycles*workers;const sold=Math.max(0,floor.bookStock-Number(floor.bookReserve||0));if(sold){floor.bookStock-=sold;splitIncome(state,floor,sold*RULES.ECONOMY.bookPrice)}}
      else if(floor.type==='park')(floor.workerIds||[]).map(id=>byId(state,id)).filter(Boolean).forEach(person=>person.satisfaction=Math.min(100,person.satisfaction+5*cycles));
      floor.cycleStartedAt+=cycles*duration;events.push({type:'produced',floorId:floor.id,cycles});
    }
    for(const floor of state.floors||[])rebalanceFloor(state,floor);
    return events;
  }
  function employed(state,person,day=null){if(Number.isInteger(day)&&person.lastTravelDay===day)return false;return(state.floors||[]).some(floor=>(floor.type!=='park'&&(floor.workerIds||[]).includes(person.id))||floor.mayorId===person.id||floor.teacherId===person.id||floor.barberId===person.id)}
  function settleRent(state,days){const events=[];for(const floor of state.floors||[]){if(floor.type!=='rental')continue;for(const id of [...(floor.residents||[])]){const person=byId(state,id),fee=3*days;if(!person){floor.residents=floor.residents.filter(personId=>personId!==id);continue}if(charge(state,person,fee)){state.money=money(Number(state.money||0)+fee);continue}floor.residents=floor.residents.filter(personId=>personId!==id);if(person.rentalHousingBonus){person.satisfaction=Math.max(0,person.satisfaction-person.rentalHousingBonus);person.rentalHousingBonus=0}events.push({type:'rentEviction',personId:id,fee})}}return events}
  function advancePayroll(state,now){const dayMs=state.dayMs||300000,currentDay=Math.floor(Math.max(0,now-state.createdAt)/dayMs),events=[];if(!Number.isInteger(state.lastPayrollDay))state.lastPayrollDay=currentDay;if(currentDay<=state.lastPayrollDay)return events;const days=currentDay-state.lastPayrollDay,entries=[];events.push(...settleRent(state,days));for(const floor of state.floors||[]){const dailyWage=floor.type==='clinic'?10:floor.type==='maternity'?15:0;if(dailyWage)(floor.workerIds||[]).map(id=>byId(state,id)).filter(Boolean).forEach(person=>entries.push({person,gross:dailyWage*days,payout:dailyWage*days,cost:dailyWage*days}));if(floor.type==='primary'){const teacher=byId(state,floor.teacherId);if(teacher)entries.push({person:teacher,gross:10*days,payout:5*days,cost:5*days})}}state.lastPayrollDay=currentDay;if(!entries.length)return events;const totalCost=entries.reduce((sum,entry)=>sum+entry.cost,0),totalGross=entries.reduce((sum,entry)=>sum+entry.gross,0),budget=Math.min(Number(state.money||0),totalCost),ratio=totalCost?budget/totalCost:0;let paid=0;for(const entry of entries){const amount=Math.floor(entry.payout*ratio*1000)/1000;entry.person.money=money(Number(entry.person.money||0)+amount);paid=money(paid+amount)}state.money=money(Math.max(0,Number(state.money||0)-budget));events.push({type:'payroll',gross:totalGross,cost:budget,paid,shortfall:budget<totalCost});return events}
  function advanceWellbeing(state,now){const dayMs=state.dayMs||300000,daysPerYear=state.daysPerYear||12,currentDay=Math.floor(Math.max(0,now-state.createdAt)/dayMs),events=[];if(!Number.isInteger(state.lastWellbeingDay))state.lastWellbeingDay=currentDay;if(currentDay<=state.lastWellbeingDay)return events;for(let day=state.lastWellbeingDay+1;day<=currentDay;day++)for(const person of state.people||[]){if(!Number.isInteger(person.workDaysThisYear))person.workDaysThisYear=0;if(employed(state,person,day-1))person.workDaysThisYear++;if(day%daysPerYear===0){let loss=0;const reasons=[];if(person.workDaysThisYear>=daysPerYear){loss+=20;reasons.push('全年没有休息')}if(!person.traveledThisYear){loss+=20;reasons.push('全年没有旅游')}if(loss){person.satisfaction=Math.max(0,person.satisfaction-loss);events.push({type:'wellbeingLoss',personId:person.id,loss,reasons})}person.workDaysThisYear=0;person.traveledThisYear=false}}state.lastWellbeingDay=currentDay;return events}
  function advanceDaily(state,now){return[...advancePayroll(state,now),...advanceWellbeing(state,now)]}
  function advanceTimeline(state,now,options={}){state.dayMs=state.dayMs||300000;state.daysPerYear=state.daysPerYear||12;state.clinicMs=state.clinicMs||60000;return[...advanceLife(state,now,options),...advancePregnancies(state,now)]}
  function cloneState(state){return typeof structuredClone==='function'?structuredClone(state):JSON.parse(JSON.stringify(state))}
  function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])]));return value}
  function stateHash(state){const text=JSON.stringify(stable(state));let hash=2166136261;for(let index=0;index<text.length;index++){hash^=text.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16).padStart(8,'0')}
  global.BuildingGameEngine={byId,floorById,parentIds,ancestorIds,related,homeOwners,privateHomeOf,canMarry,canConceive,qualifiedMaternity,canDeliver,isAssigned,legal,removeAssignments,clinicFor,advanceLife,advancePregnancies,advanceTimeline,paymentMembers,spendableMoney,charge,splitIncome,payWorkers,rebalanceFloor,advanceProduction,employed,settleRent,advancePayroll,advanceWellbeing,advanceDaily,cloneState,stateHash};
})(globalThis);
