(function(global){
  'use strict';
  const VERSION=21,FEATURES=24,HIDDEN=16;
  const ACTIONS=['wait','buildGarden','buildFarm','buildMarket','buildClinic','buildMaternity','buildPark','buildRental','buildOldApartment','buildApartment','buildVilla','assignJob','setMayor','marry','conceive','deliver','setFood','buyHome','moveRental','study','teach','buyClothes','haircut','play','buyBook','useBook','travel','setReserve','setMarketProduct'];
  const WEIGHTS=FEATURES*HIDDEN+HIDDEN+ACTIONS.length*HIDDEN+ACTIONS.length;
  function seeded(seed){let x=seed>>>0;return()=>((x=(x*1664525+1013904223)>>>0)/4294967296)}
  function randomPolicy(rand=Math.random){return{format:'action-network-v1',features:FEATURES,hidden:HIDDEN,actions:ACTIONS.slice(),weights:Array.from({length:WEIGHTS},()=>rand()*2-1)}}
  function valid(policy){return Boolean(policy&&policy.format==='action-network-v1'&&policy.features===FEATURES&&policy.hidden===HIDDEN&&Array.isArray(policy.actions)&&policy.actions.join('|')===ACTIONS.join('|')&&Array.isArray(policy.weights)&&policy.weights.length===WEIGHTS&&policy.weights.every(Number.isFinite))}
  function score(policy,action){const w=policy.weights,f=action.features||[],hidden=[],h0=FEATURES*HIDDEN;for(let h=0;h<HIDDEN;h++){let sum=w[h0+h];for(let i=0;i<FEATURES;i++)sum+=w[i*HIDDEN+h]*(f[i]||0);hidden[h]=Math.tanh(sum)}const ai=ACTIONS.indexOf(action.type),o0=h0+HIDDEN;let sum=w[o0+ACTIONS.length*HIDDEN+ai];for(let h=0;h<HIDDEN;h++)sum+=w[o0+ai*HIDDEN+h]*hidden[h];return sum}
  function choose(policy,candidates,rand=Math.random,explore=0){if(!valid(policy)||!candidates.length)return null;if(explore&&rand()<explore)return candidates[Math.floor(rand()*candidates.length)];let best=candidates[0],value=-Infinity;for(const candidate of candidates){const next=score(policy,candidate)+(candidate.jitter||0)*rand();if(next>value){value=next;best=candidate}}return best}
  function mutate(parent,rand=Math.random,rate=.08,scale=.3){const child={...parent,actions:parent.actions.slice(),weights:parent.weights.slice()};for(let i=0;i<child.weights.length;i++)if(rand()<rate)child.weights[i]=Math.max(-4,Math.min(4,child.weights[i]+(rand()*2-1)*scale));return child}
  function crossover(a,b,rand=Math.random){const child=randomPolicy(rand);child.weights=child.weights.map((_,i)=>rand()<.5?a.weights[i]:b.weights[i]);return child}
  const clamp=(n,min=0,max=1)=>Math.max(min,Math.min(max,n));
  function vector(s,p=null,target=null,extra={}){const people=s.people||[],alive=people.filter(x=>x.alive!==false),adults=alive.filter(x=>x.age>=18),fertile=alive.filter(x=>x.age>=20&&x.age<=40),food=(s.food||0),avg=alive.length?alive.reduce((n,x)=>n+(x.satiety||0),0)/alive.length:0;return[
    clamp(alive.length/30),clamp(adults.length/20),clamp(fertile.length/12),clamp((s.children||0)/20),clamp((s.money||0)/2000),clamp(food/Math.max(1,alive.length*12)),clamp(avg/100),clamp((s.satisfaction||50)/100),clamp((s.homes||0)/10),clamp((s.freeBeds||0)/12),clamp((s.gardens||0)/5),clamp((s.foodWorkers||0)/8),clamp((s.medicalWorkers||0)/4),clamp((s.teachers||0)/4),clamp((s.day||0)/2400),p?clamp(p.age/100):0,p?clamp((p.money||0)/500):0,p?clamp((p.satiety||0)/100):0,p&&p.spouseId?1:0,p&&p.homeId?1:0,target?clamp(target.age/100):0,target&&target.spouseId?1:0,extra.urgent?1:0,clamp(extra.value||0)
  ];}
  function simulate(policy,seed,horizon=2400){const rand=seeded(seed),people=[];for(let i=0;i<6;i++)people.push({id:i+1,age:i<4?20+Math.floor(rand()*19):16+Math.floor(rand()*24),gender:i<3?'男':'女',family:i+1,motherId:null,fatherId:null,spouseId:null,homeId:null,satiety:100,money:0,alive:true,born:false});const s={day:0,money:0,food:8,gardens:0,farms:0,markets:0,clinics:0,maternity:0,homes:0,freeBeds:0,foodWorkers:0,medicalWorkers:0,teachers:0,births:0,deaths:0,starvationDeaths:0,adultDescendants:0,maxGeneration:0,satisfaction:50,people,nextId:7,pregnancies:[]};
    const alive=()=>people.filter(p=>p.alive),related=(a,b)=>a.family===b.family||a.motherId===b.id||a.fatherId===b.id||b.motherId===a.id||b.fatherId===a.id||Boolean(a.motherId&&[b.motherId,b.fatherId].includes(a.motherId))||Boolean(a.fatherId&&[b.motherId,b.fatherId].includes(a.fatherId));
    const act=a=>{const p=a.person,t=a.target;switch(a.type){case'buildGarden':s.money-=6;s.gardens++;break;case'buildFarm':s.money-=60;s.farms++;break;case'buildMarket':s.money-=200;s.markets++;break;case'buildMaternity':s.money-=250;s.maternity++;break;case'buildOldApartment':s.money-=200;s.homes++;s.freeBeds+=3;break;case'assignJob':s.foodWorkers=Math.min(8,s.foodWorkers+1);break;case'setMayor':s.mayorId=p.id;break;case'marry':if(!p.spouseId&&!t.spouseId){p.spouseId=t.id;t.spouseId=p.id;t.family=Math.min(p.family,t.family)}break;case'buyHome':if(!p.homeId&&s.freeBeds>=2){p.homeId=s.homes;s.freeBeds-=2;t.homeId=p.homeId}break;case'conceive':if(!s.pregnancies.some(q=>q.mother.id===p.id||q.mother.id===t.id))s.pregnancies.push({mother:p.gender==='女'?p:t,father:p.gender==='男'?p:t,due:s.day+9});break;case'deliver':{const q=a.pregnancy;if(!s.pregnancies.includes(q))break;const m=q.mother,f=q.father,generation=Math.max(m.generation||0,f.generation||0)+1,baby={id:s.nextId++,age:0,gender:rand()<.5?'男':'女',family:m.family,motherId:m.id,fatherId:f.id,spouseId:null,homeId:m.homeId,satiety:100,money:0,alive:true,born:true,generation};people.push(baby);s.births++;s.maxGeneration=Math.max(s.maxGeneration,generation);s.freeBeds--;s.pregnancies=s.pregnancies.filter(x=>x!==q);break}}};
    for(let day=0;day<horizon&&alive().length;day++){s.day=day;const ap=alive(),avgSat=ap.reduce((n,p)=>n+p.satiety,0)/ap.length;s.money+=ap.length*(s.satisfaction/100)*(s.mayorId?1.8:1);s.food+=s.foodWorkers*(s.gardens*2+s.farms*1.5);const candidates=[{type:'wait',features:vector(s)}];if(s.money>=6)candidates.push({type:'buildGarden',features:vector(s,null,null,{value:ap.length/Math.max(1,s.gardens+1)})});if(s.money>=60)candidates.push({type:'buildFarm',features:vector(s)});if(s.money>=200)candidates.push({type:'buildMarket',features:vector(s)});if(s.money>=250&&!s.maternity)candidates.push({type:'buildMaternity',features:vector(s,null,null,{urgent:s.pregnancies.length>0})});if(s.money>=200)candidates.push({type:'buildOldApartment',features:vector(s,null,null,{urgent:s.freeBeds<2})});for(const p of ap.filter(x=>x.age>=18)){if(s.foodWorkers<s.gardens*2)candidates.push({type:'assignJob',person:p,features:vector(s,p)});if(!s.mayorId)candidates.push({type:'setMayor',person:p,features:vector(s,p)});if(p.spouseId){const spouse=people.find(x=>x.id===p.spouseId&&x.alive);if(spouse&&!p.homeId&&s.freeBeds>=2)candidates.push({type:'buyHome',person:p,target:spouse,features:vector(s,p,spouse,{urgent:true})});if(spouse&&p.homeId&&s.freeBeds>0&&p.age>=20&&p.age<=40&&spouse.age>=20&&spouse.age<=40&&!s.pregnancies.some(q=>q.mother.id===p.id||q.mother.id===spouse.id))candidates.push({type:'conceive',person:p,target:spouse,features:vector(s,p,spouse,{value:s.freeBeds/6})})}else for(const q of ap){if(q.id>p.id&&!q.spouseId&&q.age>=20&&q.age<=40&&p.age<=40&&p.gender!==q.gender&&!related(p,q))candidates.push({type:'marry',person:p,target:q,features:vector(s,p,q,{value:1-Math.abs(p.age-q.age)/30})})}}for(const q of s.pregnancies.filter(x=>x.due<=day))if(s.maternity&&s.medicalWorkers>0)candidates.push({type:'deliver',pregnancy:q,person:q.mother,target:q.father,features:vector(s,q.mother,q.father,{urgent:true})});if(s.maternity&&!s.medicalWorkers&&ap.some(p=>p.age>=18))s.medicalWorkers=1;for(let step=0;step<4;step++){const selected=choose(policy,candidates,rand,.015);if(selected&&selected.type!=='wait')act(selected)}for(const p of ap){if(s.food>=1){s.food--;p.satiety=Math.min(100,p.satiety+20)}p.satiety=Math.max(0,p.satiety-10);p.zeroDays=p.satiety===0?(p.zeroDays||0)+1:0;if(p.zeroDays>=3){p.alive=false;s.deaths++;s.starvationDeaths++}}if(day%12===11)for(const p of alive()){p.age++;if(p.born&&p.age===18)s.adultDescendants++;if(p.age>=100){p.alive=false;s.deaths++}}s.satisfaction=clamp((s.satisfaction+(avgSat>40?.05:-.2)),0,100)}const survivors=alive().length,days=Math.min(horizon,s.day+1),fitness=(survivors>0?1e9:0)+s.maxGeneration*2e8+s.adultDescendants*5e7+s.births*2e6+days*1e5-s.starvationDeaths*5e6+s.satisfaction*1e3;return{fitness,days,population:survivors,births:s.births,deaths:s.deaths,starvationDeaths:s.starvationDeaths,satisfaction:s.satisfaction,money:s.money,lineageGeneration:s.maxGeneration,adultDescendants:s.adultDescendants}}
  global.BuildingLearningAI={VERSION,FEATURES,HIDDEN,ACTIONS,WEIGHTS,seeded,randomPolicy,valid,score,choose,mutate,crossover,vector,simulate};
})(window);
