/* One real-time day = 600 seconds. Work: 09–12 and 13–18 (8 productive hours). */
window.scheduleOwnsProduction=true;window.scheduleOwnsMeals=true;
state.clockMinutes??=360;state.day??=1;state.totalDays??=Math.max(0,state.day-1);state.people.forEach(p=>{p.homeFloor??=state.floors.findIndex(f=>f.type==='housing');p.jobPlace??=null;p.schoolFloor??=null;p.skillPoints??={};p.mealsToday??=0;p.lastMealKey??=''});
if(!state.satisfactionDecayV2){state.people.forEach(p=>p.morale=100);state.morale=100;state.satisfactionDecayV2=true}
let scheduleLast=performance.now(),scheduleHarvest=state.harvestElapsed||0,scheduleRanch=state.ranchElapsed||0,lastClockMinute=Math.floor(state.clockMinutes),commuteQueue=[];
const isAtWork=m=>m>=540&&m<1080;const isProductive=m=>(m>=540&&m<720)||(m>=780&&m<1080);const hhmm=m=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;
const SCHOOL_SUBJECTS=['物流','食品','农业','医疗','教育','设计'];function schoolData(floor){let f=state.floors[floor];if(!f||f.type!=='school')return null;f.school??={teacher:null,students:[],subject:'物流',lastTaughtDay:0};f.school.students=f.school.students.filter(i=>state.people[i]);if(!state.people[f.school.teacher])f.school.teacher=null;return f.school}function removeFromSchools(i){state.floors.forEach(f=>{if(f.type!=='school'||!f.school)return;if(f.school.teacher===i)f.school.teacher=null;f.school.students=f.school.students.filter(x=>x!==i)});if(state.people[i])state.people[i].schoolFloor=null}
function ensureClock(){let clock=document.querySelector('.game-clock');if(!clock){clock=document.createElement('div');clock.className='game-clock';clock.innerHTML='<b></b><span><strong></strong><small></small></span>';document.querySelector('header .weather')?.before(clock)}return clock}
function updateClock(){let c=ensureClock();c.querySelector('b').textContent=hhmm(state.clockMinutes);c.querySelector('strong').textContent=`第 ${state.day} 天`;c.querySelector('small').textContent=isProductive(state.clockMinutes)?'工作时间':isAtWork(state.clockMinutes)?'午间休息':'休息时间'}
function mealSlot(minute){if(minute>=1140)return'晚餐';if(minute>=720)return'午餐';if(minute>=420)return'早餐';return null}function mealKey(slot){return`${state.day}-${slot}`}
function requestScheduledMeal(slot){if(!slot)return;let key=mealKey(slot);state.people.forEach((p,i)=>{if(p.lastMealKey===key)return;p.lastMealKey=key;p.satiety=Math.min(p.satiety,30);if(!state.foodQueue.includes(i)&&!p.travel)state.foodQueue.push(i)});log(`${slot}时间到了，居民开始排队取餐。`);serveNext()}
function homeFloorOf(p){return p.homeFloor>=0?p.homeFloor:state.floors.findIndex(f=>f.type==='housing')}
function enqueueCommute(i,to,kind){let p=state.people[i];if(!p||p.place===to||commuteQueue.some(x=>x.i===i))return;commuteQueue.push({i,from:statusFloor(p),to,kind})}
function beginSchoolDay(){state.floors.forEach((f,floor)=>{if(f.type!=='school')return;let school=schoolData(floor);school.session={day:state.day,teacher:school.teacher,students:[...school.students],subject:school.subject}})}
function startShift(){beginSchoolDay();state.people.forEach((p,i)=>{let destination=typeof p.schoolFloor==='number'?p.schoolFloor:p.jobPlace;if(typeof destination==='number')enqueueCommute(i,destination,typeof p.schoolFloor==='number'?'上学':'上班')});log('08:45，上班和上学的居民前往电梯；09:00 正式到岗。');processCommute()}
function completeSchoolDay(){state.floors.forEach((f,floor)=>{if(f.type!=='school')return;let school=schoolData(floor),session=school.session;if(!session||session.day!==state.day||session.teacher===null||school.lastTaughtDay===state.day)return;let teacher=state.people[session.teacher];if(!teacher||teacher.place!==floor||teacher.travel)return;let attending=session.students.filter(i=>school.students.includes(i)&&state.people[i]?.place===floor&&!state.people[i].travel);if(!attending.length)return;attending.forEach(i=>{let p=state.people[i];p.skillPoints[session.subject]=(p.skillPoints[session.subject]||0)+1});school.lastTaughtDay=state.day;log(`F${floor+1} 社区学校完成${session.subject}课程：${attending.map(i=>state.people[i].name).join('、')}各 +1 点。`)})}
function endShift(){completeSchoolDay();state.people.forEach((p,i)=>{if(typeof p.jobPlace==='number'||typeof p.schoolFloor==='number')enqueueCommute(i,homeFloorOf(p),'放学/下班')});log('18:00，下班和放学的居民乘电梯返回住宿层。');processCommute()}
const ELEVATOR_CAPACITY=6;
function finishCommuteRoute(batch){elevator.passengers=[];trips=[];let names=batch.map(x=>state.people[x.i]?.name).filter(Boolean);log(`${batch[0].kind}合乘完成：${names.join('、')}已分别到达目标楼层。`);render();serveNext();processCommute()}
function serviceCommuteStop(batch,stops,index,direction){let floor=stops[index],arrivals=batch.filter(x=>x.to===floor&&elevator.passengers.includes(x.i)),departures=batch.filter(x=>x.from===floor&&!elevator.passengers.includes(x.i)&&state.people[x.i]?.travel);let wait=arrivals.some(x=>x.kind==='上班')&&state.clockMinutes<540?(540-state.clockMinutes)/(2.4*state.speed)*1000:0;setTimeout(()=>{arrivals.forEach(x=>{let p=state.people[x.i];elevator.passengers=elevator.passengers.filter(i=>i!==x.i);p.place=x.to;p.travel=null;p.walkX=15+Math.random()*45});departures.forEach(x=>{let p=state.people[x.i];p.travel.stage='riding-commute';elevator.passengers.push(x.i)});if(arrivals.length||departures.length)log(`电梯停靠 F${floor+1}：${departures.length?departures.length+' 人上车':''}${departures.length&&arrivals.length?'，':''}${arrivals.length?arrivals.length+' 人下车':''}。`);decorateBehavior();if(index===stops.length-1)return finishCommuteRoute(batch);moveElevator(stops[index+1],()=>serviceCommuteStop(batch,stops,index+1,direction))},wait)}
function processCommute(){if(trips.length||elevator.moving||!commuteQueue.length)return;let first=commuteQueue[0],direction=Math.sign(first.to-first.from),batch=commuteQueue.filter(x=>Math.sign(x.to-x.from)===direction).slice(0,ELEVATOR_CAPACITY);commuteQueue=commuteQueue.filter(x=>!batch.includes(x));let group=batch.map(x=>x.i),stops=[...new Set(batch.flatMap(x=>[x.from,x.to]))].sort((a,b)=>direction>0?a-b:b-a);trips=group;batch.forEach(x=>{let p=state.people[x.i];p.travel={stage:'walking-to-elevator',home:x.from,commuteTo:x.to};p.walkX=78});decorateBehavior(true);setTimeout(()=>{setStage(group,'waiting-elevator');moveElevator(stops[0],()=>serviceCommuteStop(batch,stops,0,direction))},1300)}
function cross(prev,now,mark){return prev<mark&&now>=mark}
function handleSchedule(prev,now){if(cross(prev,now,420))requestScheduledMeal('早餐');if(cross(prev,now,525))startShift();if(cross(prev,now,720))requestScheduledMeal('午餐');if(cross(prev,now,1080))endShift();if(cross(prev,now,1140))requestScheduledMeal('晚餐')}
function workersAt(floor){if(!isProductive(state.clockMinutes)||floor<0)return[];return state.people.filter(p=>p.jobPlace===floor&&p.place===floor&&!p.travel).slice(0,2)}function assignedCount(floor){return floor<0?0:state.people.filter(p=>p.jobPlace===floor).length}
function scheduleProduction(delta){let g=gardenFloor(),r=ranchFloor(),gardenWorkers=workersAt(g),ranchWorkers=workersAt(r);if(gardenWorkers.length){scheduleHarvest+=delta*state.speed;if(scheduleHarvest>=20000){scheduleHarvest-=20000;state.pantry+=gardenWorkers.length;harvestActive=true;gardenWorkers.forEach(p=>p.walkX=70);log(`菜园完成生产：蔬菜 +${gardenWorkers.length}。`);decorateBehavior(true);setTimeout(()=>{harvestActive=false;gardenWorkers.forEach(p=>p.walkX=18+Math.random()*28);decorateBehavior(true)},900);serveNext()}}if(ranchWorkers.length){scheduleRanch+=delta*state.speed;if(scheduleRanch>=20000){scheduleRanch-=20000;state.meat+=ranchWorkers.length;state.milk+=ranchWorkers.length;ranchActive=true;ranchWorkers.forEach(p=>p.walkX=70);log(`牧场完成生产：肉 +${ranchWorkers.length}，牛奶 +${ranchWorkers.length}。`);decorateBehavior(true);setTimeout(()=>{ranchActive=false;ranchWorkers.forEach(p=>p.walkX=18+Math.random()*28);decorateBehavior(true)},900);serveNext()}}state.harvestElapsed=scheduleHarvest;state.ranchElapsed=scheduleRanch;harvestElapsed=scheduleHarvest;updateAllProductionUI()}
function updateRoomProductionUI(floor,workerCount,elapsed,label){let room=floor>=0?document.querySelector(`.room[data-floor="${floor}"]`):null;if(!room)return;let w=room.querySelector('.production-widget');if(!w){room.insertAdjacentHTML('beforeend','<div class="production-widget"><span></span><div class="production-track"><i class="production-fill"></i></div><span class="production-time"></span></div>');w=room.querySelector('.production-widget')}let active=isProductive(state.clockMinutes)&&workerCount>0,percent=Math.min(100,elapsed/20000*100),fill=w.querySelector('.production-fill');w.classList.toggle('paused',!active);w.firstElementChild.textContent=label;fill.style.setProperty('width',percent+'%','important');fill.style.setProperty('background','#000','important');w.querySelector('.production-time').textContent=active?`${Math.floor(percent)}% ${Math.ceil((20000-elapsed)/1000)}s`:isAtWork(state.clockMinutes)?'休息':'停产'}
function updateAllProductionUI(){let g=gardenFloor(),r=ranchFloor();updateRoomProductionUI(g,workersAt(g).length,scheduleHarvest,`菜${state.pantry} · 岗位${assignedCount(g)}/2`);updateRoomProductionUI(r,workersAt(r).length,scheduleRanch,`肉${state.meat} 奶${state.milk} · ${assignedCount(r)}/2`)}
updateProductionUI=updateAllProductionUI;
function isSchoolTeacher(i){return state.floors.some(f=>f.type==='school'&&f.school?.teacher===i)}
function selectSchoolTeacher(floor,i){let school=schoolData(floor),p=state.people[i];if(!school||!p||p.travel)return toast('请等人物抵达后再调整');let old=school.teacher;if(old===i)return;removeFromSchools(i);if(old!==null&&state.people[old]){let former=state.people[old];if(former.jobPlace===floor)former.jobPlace=null;if(isAtWork(state.clockMinutes)&&former.place===floor)enqueueCommute(old,homeFloorOf(former),'教师离岗')}school.teacher=i;p.jobPlace=floor;p.schoolFloor=null;if(isAtWork(state.clockMinutes)&&p.place!==floor)enqueueCommute(i,floor,'教师到岗');log(`${p.name}成为 F${floor+1} 社区学校教师。`);processCommute();render();decorateEmployment();openSchoolPanel(floor)}
function toggleSchoolStudent(floor,i){let school=schoolData(floor),p=state.people[i];if(!school||!p||p.travel)return toast('请等人物抵达后再调整');if(school.teacher===i)return toast('教师不能同时作为学生');if(school.students.includes(i)){school.students=school.students.filter(x=>x!==i);p.schoolFloor=null;if(isAtWork(state.clockMinutes)&&p.place===floor)enqueueCommute(i,homeFloorOf(p),'退学返家');log(`${p.name}停止在 F${floor+1} 上学。`)}else{if(school.students.length>=3)return toast('社区学校最多 3 名学生');removeFromSchools(i);p.jobPlace=null;p.schoolFloor=floor;school.students.push(i);if(isAtWork(state.clockMinutes)&&p.place!==floor)enqueueCommute(i,floor,'入学');log(`${p.name}进入 F${floor+1} 社区学校学习。`)}processCommute();render();decorateEmployment();openSchoolPanel(floor)}
function chooseSchoolSubject(floor,subject){let school=schoolData(floor);if(!school||!SCHOOL_SUBJECTS.includes(subject))return;school.subject=subject;log(`F${floor+1} 社区学校今日教学项目改为${subject}。`);decorateEmployment();openSchoolPanel(floor)}
function openSchoolPanel(floor){let school=schoolData(floor);if(!school)return;$('sheetAvatar').style.display='none';$('sheetName').textContent=`F${floor+1} 社区学校`;$('sheetRole').textContent='每日 09:00–18:00 · 1 教师 · 3 学生';document.querySelector('.employment-control')?.remove();document.querySelector('.school-control')?.remove();let teacher=school.teacher===null?'未选择':state.people[school.teacher]?.name||'未选择';$('sheetStats').innerHTML=`<div><span>教师</span><b>${teacher}</b></div><div><span>学生</span><b>${school.students.length}/3</b></div><div><span>今日课程</span><b>${school.subject}</b></div>`;let subjects=SCHOOL_SUBJECTS.map(s=>`<button type="button" data-subject="${s}" class="${school.subject===s?'selected':''}">${s}</button>`).join(''),teachers=state.people.map((p,i)=>`<button type="button" data-teacher="${i}" class="${school.teacher===i?'selected':''}">${p.name}<small>${p.degree} · ${p.skill}</small></button>`).join(''),students=state.people.filter((p,i)=>i!==school.teacher).map(p=>{let i=state.people.indexOf(p),selected=school.students.includes(i),full=school.students.length>=3&&!selected;return`<button type="button" data-student="${i}" class="${selected?'selected':''}" ${full?'disabled':''}>${p.name}<small>${selected?'已入学':full?'名额已满':'点击入学'}</small></button>`}).join('');$('sheetStats').insertAdjacentHTML('afterend',`<section class="school-control"><b>今日教学项目</b><div class="school-options subjects">${subjects}</div><b>选择教师</b><div class="school-options">${teachers}</div><b>选择学生</b><div class="school-options">${students}</div></section>`);let control=document.querySelector('.school-control');control.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>chooseSchoolSubject(floor,b.dataset.subject));control.querySelectorAll('[data-teacher]').forEach(b=>b.onclick=()=>selectSchoolTeacher(floor,+b.dataset.teacher));control.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>toggleSchoolStudent(floor,+b.dataset.student));$('personSheet').classList.add('show');$('backdrop').classList.add('show')}
function employmentText(p){let study=typeof p.schoolFloor==='number'?` · 在读 F${p.schoolFloor+1} ${schoolData(p.schoolFloor)?.subject}`:'',job=typeof p.jobPlace==='number'?`F${p.jobPlace+1} ${state.floors[p.jobPlace]?.type==='school'?'教师':ROOMS[state.floors[p.jobPlace]?.type]?.name}`:'未就业',current=p.place==='elevator'?'电梯':`F${Number(p.place)+1}`;return`在职：${job}${study} · 当前：${current} ${personStatus(p)}`}
function decorateEmployment(){state.people.forEach((p,i)=>{let card=document.querySelector(`[data-card="${i}"]`),small=card?.querySelector('small');if(small)small.textContent=employmentText(p)});[['garden','菜园'],['ranch','牧场']].forEach(([type,name])=>{let floor=state.floors.findIndex(f=>f.type===type),label=floor>=0?document.querySelector(`.room[data-floor="${floor}"] .room-label`):null;if(label)label.innerHTML=`F${floor+1} · <b>${name}</b> · ${assignedCount(floor)}人工作`});state.floors.forEach((f,floor)=>{if(f.type!=='school')return;let school=schoolData(floor),room=document.querySelector(`.room[data-floor="${floor}"]`),label=room?.querySelector('.room-label');if(label)label.innerHTML=`F${floor+1} · <b>社区学校</b> · ${school.students.length}/3学生`;let widget=room?.querySelector('.school-widget');if(room&&!widget){room.insertAdjacentHTML('beforeend','<button type="button" class="school-widget"></button>');widget=room.querySelector('.school-widget')}if(widget){let teacher=school.teacher===null?'未选教师':state.people[school.teacher]?.name;widget.textContent=`${school.subject} · ${teacher} · ${school.students.length}/3`;widget.onclick=e=>{e.stopPropagation();openSchoolPanel(floor)}}});let elapsedDays=state.totalDays+state.clockMinutes/1440;$('years').textContent=(elapsedDays/365).toFixed(1)+'年';$('morale').textContent=Math.round(state.morale)+'%';updateAllProductionUI();updateClock()}
function jobName(p){if(typeof p.schoolFloor==='number')return`不就业 · 在读 F${p.schoolFloor+1}`;return typeof p.jobPlace==='number'?`F${p.jobPlace+1} ${state.floors[p.jobPlace]?.type==='school'?'社区学校教师':ROOMS[state.floors[p.jobPlace]?.type]?.name}`:'不就业'}
function changeEmployment(i,value){let p=state.people[i];if(!p)return;if(p.travel)return toast('正在乘电梯，请抵达后再调整岗位');if(value==='none'){if(isSchoolTeacher(i))removeFromSchools(i);p.jobPlace=null;let home=homeFloorOf(p);log(`${p.name}选择不就业。`);if(typeof p.schoolFloor!=='number'&&typeof p.place==='number'&&p.place!==home){enqueueCommute(i,home,'离职返家');processCommute()}else if(typeof p.schoolFloor!=='number')p.place=home}else{let floor=Number(value),type=state.floors[floor]?.type;if(!type||['housing','school'].includes(type))return;if(['garden','ranch'].includes(type)&&state.people.filter((x,n)=>n!==i&&x.jobPlace===floor).length>=2)return toast(`${ROOMS[type].name}岗位已满`);if(p.jobPlace===floor)return toast('已经在这个房间就业');removeFromSchools(i);p.jobPlace=floor;log(`${p.name}选择在 F${floor+1} ${ROOMS[type].name}就业，岗位立即生效。`);if(isAtWork(state.clockMinutes)&&p.place!==floor){enqueueCommute(i,floor,'换岗');processCommute()}else if(!isAtWork(state.clockMinutes))p.place=homeFloorOf(p)}render();decorateEmployment();openPerson(i)}
const scheduledOpenPerson=openPerson;openPerson=function(i){$('sheetAvatar').style.display='';document.querySelector('.school-control')?.remove();scheduledOpenPerson(i);let p=state.people[i];document.querySelector('.employment-control')?.remove();let points=Object.entries(p.skillPoints||{}).filter(([,n])=>n>0).map(([s,n])=>`${s}${n}`).join(' · ')||'暂无';$('sheetStats').insertAdjacentHTML('beforeend',`<div><span>今日用餐</span><b>${p.mealsToday}/3</b></div><div class="skill-points-cell"><span>社区学校技能点</span><b>${points}</b></div>`);let rooms=state.floors.map((f,floor)=>({f,floor})).filter(x=>!['housing','school'].includes(x.f.type)),options=[`<button type="button" data-job="none" class="${typeof p.jobPlace!=='number'?'selected':''}">不就业</button>`,...rooms.map(({f,floor})=>{let count=assignedCount(floor),full=['garden','ranch'].includes(f.type)&&count>=2&&p.jobPlace!==floor;return`<button type="button" data-job="${floor}" class="${p.jobPlace===floor?'selected':''}" ${full?'disabled':''}>F${floor+1} ${ROOMS[f.type].name}<small>${full?'岗位已满':count+' 人已就业'}</small></button>`})].join('');$('sheetStats').insertAdjacentHTML('afterend',`<section class="employment-control"><button type="button" class="employment-current"><span>就业（点击选择）</span><b>${jobName(p)}　⌄</b></button><div class="employment-options" hidden>${options}</div></section>`);let control=document.querySelector('.employment-control'),list=control.querySelector('.employment-options');control.querySelector('.employment-current').onclick=()=>{list.hidden=!list.hidden};control.querySelectorAll('[data-job]').forEach(button=>button.onclick=()=>changeEmployment(i,button.dataset.job))};
const scheduledAssign=assign;assign=function(i,floor){let p=state.people[i];if(floor==='elevator'){p.jobPlace=null;p.place='elevator';log(`${p.name}进入电梯间待命`)}else{let type=state.floors[floor]?.type;if(type==='housing'){p.homeFloor=floor;p.place=floor;log(`${p.name}的住宿层设为 F${floor+1}`)}else if(type==='school')return toggleSchoolStudent(floor,i);else{if(['garden','ranch'].includes(type)&&state.people.filter((x,n)=>n!==i&&x.jobPlace===floor).length>=2)return toast(`${ROOMS[type].name}最多安排 2 名员工`);removeFromSchools(i);p.jobPlace=floor;p.place=homeFloorOf(p);log(`${p.name}受雇于 F${floor+1} ${ROOMS[type].name}，将在次日 09:00 乘电梯上班`)}}render();decorateEmployment()};
function scheduleTick(){let now=performance.now(),delta=now-scheduleLast;scheduleLast=now;let gameMinutes=delta/1000*2.4*state.speed,prev=state.clockMinutes;state.clockMinutes+=gameMinutes;state.people.forEach(p=>p.morale=Math.max(0,p.morale-gameMinutes*100/(7*1440)));state.morale=state.people.reduce((sum,p)=>sum+p.morale,0)/(state.people.length||1);if(state.clockMinutes>=1440){state.clockMinutes%=1440;state.day++;state.totalDays++;state.people.forEach(p=>{p.mealsToday=0;p.lastMealKey=''});if(isAtWork(prev))endShift()}handleSchedule(prev,state.clockMinutes);scheduleProduction(delta);processCommute();decorateEmployment()}
setInterval(scheduleTick,250);updateClock();decorateEmployment();
