/* One real-time day = 600 seconds. Work: 09–12 and 13–18 (8 productive hours). */
window.scheduleOwnsProduction=true;window.scheduleOwnsMeals=true;
state.clockMinutes??=360;state.day??=1;state.totalDays??=Math.max(0,state.day-1);state.people.forEach(p=>{p.homeFloor??=state.floors.findIndex(f=>f.type==='housing');p.jobPlace??=null;p.mealsToday??=0;p.lastMealKey??=''});
if(!state.satisfactionDecayV2){state.people.forEach(p=>p.morale=100);state.morale=100;state.satisfactionDecayV2=true}
let scheduleLast=performance.now(),scheduleHarvest=state.harvestElapsed||0,lastClockMinute=Math.floor(state.clockMinutes),commuteQueue=[];
const isAtWork=m=>m>=540&&m<1080;const isProductive=m=>(m>=540&&m<720)||(m>=780&&m<1080);const hhmm=m=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;
function ensureClock(){let clock=document.querySelector('.game-clock');if(!clock){clock=document.createElement('div');clock.className='game-clock';clock.innerHTML='<b></b><span><strong></strong><small></small></span>';document.querySelector('header .weather')?.before(clock)}return clock}
function updateClock(){let c=ensureClock();c.querySelector('b').textContent=hhmm(state.clockMinutes);c.querySelector('strong').textContent=`第 ${state.day} 天`;c.querySelector('small').textContent=isProductive(state.clockMinutes)?'工作时间':isAtWork(state.clockMinutes)?'午间休息':'休息时间'}
function mealSlot(minute){if(minute>=1140)return'晚餐';if(minute>=720)return'午餐';if(minute>=420)return'早餐';return null}function mealKey(slot){return`${state.day}-${slot}`}
function requestScheduledMeal(slot){if(!slot)return;let key=mealKey(slot);state.people.forEach((p,i)=>{if(p.lastMealKey===key)return;p.lastMealKey=key;p.satiety=Math.min(p.satiety,30);if(!state.foodQueue.includes(i)&&!p.travel)state.foodQueue.push(i)});log(`${slot}时间到了，居民开始排队取餐。`);serveNext()}
function homeFloorOf(p){return p.homeFloor>=0?p.homeFloor:state.floors.findIndex(f=>f.type==='housing')}
function enqueueCommute(i,to,kind){let p=state.people[i];if(!p||p.place===to||commuteQueue.some(x=>x.i===i))return;commuteQueue.push({i,from:statusFloor(p),to,kind})}
function startShift(){state.people.forEach((p,i)=>{if(typeof p.jobPlace==='number')enqueueCommute(i,p.jobPlace,'上班')});log('08:45，上班居民前往电梯；09:00 正式到岗。');processCommute()}
function endShift(){state.people.forEach((p,i)=>{if(typeof p.jobPlace==='number')enqueueCommute(i,homeFloorOf(p),'下班')});log('18:00，下班居民前往电梯，准备返回住宿层。');processCommute()}
function finishCommute(batch,group,first){elevator.passengers=[];group.forEach(i=>{let p=state.people[i];p.place=first.to;p.travel=null;p.walkX=15+Math.random()*45});trips=[];log(`${batch[0].kind}通勤完成：${group.map(i=>state.people[i].name).join('、')}抵达 F${first.to+1}。`);render();serveNext();processCommute()}
function processCommute(){if(trips.length||elevator.moving||!commuteQueue.length)return;let first=commuteQueue[0],batch=commuteQueue.filter(x=>x.from===first.from&&x.to===first.to).slice(0,3);commuteQueue=commuteQueue.filter(x=>!batch.includes(x));let group=batch.map(x=>x.i);trips=group;group.forEach(i=>{let p=state.people[i];p.travel={stage:'walking-to-elevator',home:first.from,commuteTo:first.to};p.walkX=78});decorateBehavior(true);setTimeout(()=>{setStage(group,'waiting-elevator');moveElevator(first.from,()=>{setStage(group,'riding-commute');elevator.passengers=[...group];moveElevator(first.to,()=>{let wait=batch[0].kind==='上班'&&state.clockMinutes<540?(540-state.clockMinutes)/(2.4*state.speed)*1000:0;setTimeout(()=>finishCommute(batch,group,first),wait)})})},1300)}
function cross(prev,now,mark){return prev<mark&&now>=mark}
function handleSchedule(prev,now){if(cross(prev,now,420))requestScheduledMeal('早餐');if(cross(prev,now,525))startShift();if(cross(prev,now,720))requestScheduledMeal('午餐');if(cross(prev,now,1080))endShift();if(cross(prev,now,1140))requestScheduledMeal('晚餐')}
function scheduledWorkers(){let g=gardenFloor();if(!isProductive(state.clockMinutes)||g<0)return[];return state.people.filter(p=>p.jobPlace===g&&p.place===g&&!p.travel).slice(0,2)}
function scheduleProduction(delta){let workers=scheduledWorkers();if(workers.length){scheduleHarvest+=delta*state.speed;if(scheduleHarvest>=20000){scheduleHarvest-=20000;state.pantry+=workers.length;harvestActive=true;workers.forEach(p=>p.walkX=70);log(`菜园完成生产：${workers.length} 人在岗，蔬菜 +${workers.length}。`);decorateBehavior(true);setTimeout(()=>{harvestActive=false;workers.forEach(p=>p.walkX=18+Math.random()*28);decorateBehavior(true)},900);serveNext()}}state.harvestElapsed=scheduleHarvest;harvestElapsed=scheduleHarvest;updateScheduleProductionUI(workers.length)}
function assignedGardenCount(){let g=gardenFloor();return g<0?0:state.people.filter(p=>p.jobPlace===g).length}
function updateScheduleProductionUI(workerCount){let g=gardenFloor(),garden=g>=0?document.querySelector(`.room[data-floor="${g}"]`):null;if(!garden)return;let w=garden.querySelector('.production-widget');if(!w){garden.insertAdjacentHTML('beforeend','<div class="production-widget"><span></span><div class="production-track"><i class="production-fill"></i></div><span class="production-time"></span></div>');w=garden.querySelector('.production-widget')}let active=isProductive(state.clockMinutes)&&workerCount>0,percent=Math.min(100,scheduleHarvest/20000*100),fill=w.querySelector('.production-fill');w.classList.toggle('paused',!active);w.firstElementChild.textContent=`菜${state.pantry} · 岗位${assignedGardenCount()}/2`;fill.style.setProperty('width',percent+'%','important');fill.style.setProperty('background','#000','important');w.querySelector('.production-time').textContent=active?`${Math.floor(percent)}% ${Math.ceil((20000-scheduleHarvest)/1000)}s`:isAtWork(state.clockMinutes)?'休息':'停产'}
updateProductionUI=function(){updateScheduleProductionUI(scheduledWorkers().length)};
function employmentText(p){let job=typeof p.jobPlace==='number'?`F${p.jobPlace+1} ${ROOMS[state.floors[p.jobPlace]?.type]?.name}`:'未就业',current=p.place==='elevator'?'电梯':`F${Number(p.place)+1}`;return`在职：${job} · 当前：${current} ${personStatus(p)}`}
function decorateEmployment(){state.people.forEach((p,i)=>{let card=document.querySelector(`[data-card="${i}"]`),small=card?.querySelector('small');if(small)small.textContent=employmentText(p)});let g=gardenFloor(),label=g>=0?document.querySelector(`.room[data-floor="${g}"] .room-label`):null;if(label)label.innerHTML=`F${g+1} · <b>菜园</b> · ${assignedGardenCount()}人工作`;let elapsedDays=state.totalDays+state.clockMinutes/1440;$('years').textContent=(elapsedDays/365).toFixed(1)+'年';$('morale').textContent=Math.round(state.morale)+'%';updateScheduleProductionUI(scheduledWorkers().length);updateClock()}
const scheduledOpenPerson=openPerson;openPerson=function(i){scheduledOpenPerson(i);let p=state.people[i],job=typeof p.jobPlace==='number'?`F${p.jobPlace+1} ${ROOMS[state.floors[p.jobPlace]?.type]?.name}`:'未就业';$('sheetStats').insertAdjacentHTML('beforeend',`<div><span>在职岗位</span><b>${job}</b></div><div><span>今日用餐</span><b>${p.mealsToday}/3</b></div>`)};
const scheduledAssign=assign;assign=function(i,floor){let p=state.people[i];if(floor==='elevator'){p.jobPlace=null;p.place='elevator';log(`${p.name}进入电梯间待命`)}else{let type=state.floors[floor]?.type;if(type==='housing'){p.homeFloor=floor;p.place=floor;log(`${p.name}的住宿层设为 F${floor+1}`)}else{if(type==='garden'&&state.people.filter((x,n)=>n!==i&&x.jobPlace===floor).length>=2)return toast('菜园最多安排 2 名员工');p.jobPlace=floor;p.place=homeFloorOf(p);log(`${p.name}受雇于 F${floor+1} ${ROOMS[type].name}，将在次日 09:00 乘电梯上班`)}}render();decorateEmployment()};
function scheduleTick(){let now=performance.now(),delta=now-scheduleLast;scheduleLast=now;let gameMinutes=delta/1000*2.4*state.speed,prev=state.clockMinutes;state.clockMinutes+=gameMinutes;state.people.forEach(p=>p.morale=Math.max(0,p.morale-gameMinutes*100/(7*1440)));state.morale=state.people.reduce((sum,p)=>sum+p.morale,0)/(state.people.length||1);if(state.clockMinutes>=1440){state.clockMinutes%=1440;state.day++;state.totalDays++;state.people.forEach(p=>{p.mealsToday=0;p.lastMealKey=''});if(isAtWork(prev))endShift()}handleSchedule(prev,state.clockMinutes);scheduleProduction(delta);processCommute();decorateEmployment()}
setInterval(scheduleTick,250);updateClock();decorateEmployment();
